devtron-labs/devtron

scripts/sql/1_insert.up.sql

Updated stable and incubator helm chart repos in the migration scripts.

Updated stable and incubator helm chart repos in the migration scripts

---

docs/SUMMARY.md

changed command bar.md file path

doc: command bar file path

---

docs/user-guide/command-bar.md

doc: command bar line break

---

docs/setup/install.md

- Added AZURE support configurations.
- Curated AWS specific configurations at one place.
- Removed Chartmuseum configurations as it is no more used.
- Removed Dex configurations (SSO setup configurations) as it can be configured from the UI now.
- Made the documentation more detailed.

Updated Devtron installation document

---

scripts/devtron-reference-helm-charts/reference-chart_3-9-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-9-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-9-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-9-0/values.yaml

- Enhanced `ingress.yaml` to consume TLS configs from `values.yaml`
- Enhanced `deployment.yaml` to consume custom pod labels from `values.yaml`

Enabled TLS config and custom pod labels

---

.github/pull_request_template.md

Please delete options that are not relevant.

format correction

---

docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md

Helm repo add command correction
No testing required

Helm repo add command correction

---

README.md

Updated Getting started section and Compatibility sections.
Viewed the README.md on github.

Updated Devtron README.md

---

README.md

devtron can now be deployed on any k8s cluster
NA

removed cloud related limitation support form readme

---

internal/sql/repository/DockerArtifactStoreRepository.go
pkg/pipeline/DockerRegistryConfig.go
pkg/pipeline/PipelineBuilder.go
scripts/sql/8_docker_reg.down.sql
scripts/sql/8_docker_reg.up.sql

- support for docker hub as container registry
- protocol in registry url  is optional
closed: #308
closed: #141 

Docker reg conf 2

---

api/restHandler/CommonRestHanlder.go

global checklist api super admin rbac removed

---

README.md

readme changes to make it more concise 
No testing is required

remove non mandatory information from readme

---

pkg/appstore/AppStoreDeploymentService.go

rollout installation as default component on multicluster. 

---

api/restHandler/UserRestHandler.go

user auth fixes for manager, get user and get and delete role group

---

internal/sql/repository/AppListingRepository.go
internal/sql/repository/appstore/AppStoreDeploymentRepository.go
internal/sql/repository/chartConfig/EnvConfigOverrideRepository.go
internal/sql/repository/cluster/EnvironmentRepository.go
internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
internal/sql/repository/security/CveStoreRepository.go
internal/sql/repository/security/ImageScanDeployInfoRepository.go

Environment soft delete - apply on app listing and other areas

---

internal/util/ChartService.go

Fixes #146
* [x ] I have performed a self-review of my own code

chart versionv2

---

manifests/yamls/dashboard.yaml
manifests/yamls/devtron.yaml
manifests/yamls/migrator.yaml

- Grafana as Reverse proxy orchestrator image updated
- Hot fixes
- Closes #353
Created and tested on Test2 cluster on aws and azure

Latest updates for Orchestrator, Dashboard and Migrator

---

api/bean/AppView.go
api/restHandler/AppListingRestHandler.go
client/argocdServer/k8sClient.go
pkg/app/AppService.go
wire_gen.go

Deployment status

---

manifests/yamls/dashboard.yaml
manifests/yamls/devtron.yaml
manifests/yamls/migrator.yaml

This release updates the latest manifests of Devtron Microservices for the installer
- Handle subpath in configmap for chart version < 3.9
Has been tested on Demo Cluster

Release: Handle Subpath in configmaps

---

manifests/install/devtron-installer.yaml
manifests/installation-script
manifests/yamls/devtron.yaml
manifests/yamls/migrator.yaml

Updates in devtron micro-service

Release PR for v0.2.6

---

manifests/yamls/grafana.yaml

Enables download of latest version of Grafana memory-usage-k8s15 chart.

Install-script: Grafana memory-usage-k8s15 latest version update

---

manifests/installation-script

specify default value of build log bucket when not supplied by user
manifest generated

default for buld log bucket

---

internal/sql/repository/team/TeamRepository.go

user auth error in case of app name reuse. hotfix for rbac object creation
Fixes # (issue) https://github.com/devtron-labs/devtron/issues/428

hotfix for user auth check added on active apps

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/ingress.yaml
scripts/sql/13_insert_chart_ref.down.sql
scripts/sql/13_insert_chart_ref.up.sql

Included changes to support backward-compatibility for #375 and #425 
Fixes #375

Backward compatible changes for #375

---

internal/sql/repository/RoleGroupRepository.go

On user role group update, error occur role mapping doesn't exists, fixed in this PR.

hotfix for - role group mapping doesn't exist 

---

api/restHandler/PipelineConfigRestHandler.go
pkg/app/AppService.go
pkg/pipeline/ChartService.go
pkg/pipeline/PipelineBuilder.go
pkg/pipeline/PropertiesConfig.go
util/helper.go

Reference chart version validation modified and fixed for minor version extraction.

Hotfix chart minor version

---

.github/semantic.yml

semantic config

---

docs/setup/install/install-devtron-helm-3.md
docs/user-guide/creating-application/deployment-template.md

Install and Deployment template documentation updated

DOC:  Install and Deployment template documentation updated

---

pkg/pipeline/DbPipelineOrchestrator.go

remove assumption that git repository url is always suffixed with `.git`
Fixes #453

FEATURE: azure repo support

---

internal/util/GitServiceAzure.go

url corrected for git

---

api/restHandler/ApplicationRestHandler.go
api/router/ApplicationRouter.go

all delete of all group kind from API. currently it was limited to pod only  
Fixes #466

FEATURE: allow all resource type deletion from UI 

---

api/restHandler/NotificationRestHandler.go
api/restHandler/UserRestHandler.go
pkg/user/RoleGroupService.go

User auth - manager access issues for adding groups and notification configs and assigning permission to other users
Fixes # (issue) https://github.com/devtron-labs/devtron/pull/472
https://github.com/devtron-labs/devtron/pull/473
https://github.com/devtron-labs/devtron/pull/474
https://github.com/devtron-labs/devtron/pull/475

FIX: Hotfixes epic bugathon 01 ISSUE: user auth issues

---

manifests/yamls/serviceaccount.yaml

Fixed clusterRole and ClusterRoleMapping for cd workflow

FIX: Fixed clusterRole and ClusterRoleMappinga

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/values.yaml

FIX: by default disable hpa

---

.github/semantic.yml

Changed "in stallation" to "installation" on Line 117
Made a change in the Readme file, "in stallation" to "installation"

fix: Typo, Updated Readme.md

---

docs/setup/install/README.md
docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md
docs/setup/install/install-devtron-using-kubectl.md

Documentation for installing Devtron using helm3, helm2 and kubectl has been improved.

DOC: Updated Docs for Installation

---

client/argocdServer/application/Application.go

init container log

---

client/argocdServer/application/Application.go

init container info on UI for logs
Fixes #516 492

FEATURE: init container log

---

client/telemetry/PosthogClient.go
client/telemetry/TelemetryEventClient.go

New microservice for returning telemetry api key created, integration with devtron to fetch key from rest api instead environment variable for security reason. 
Fixes # (issue) :  https://github.com/devtron-labs/devtron/issues/537

FEATURE: telemetry api key integration for oss

---

api/restHandler/TelemetryRestHandler.go
api/router/TelemetryRouter.go
client/telemetry/PosthogClient.go
client/telemetry/TelemetryEventClient.go

telemetry api for getting info for posthog, has been modified. api key added in response along with posthog url and ucid.
Fixes # (issue): https://github.com/devtron-labs/devtron/issues/542

FIX: telemetry meta info api changes

---

docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md

Corrected BLOB_STORAGE_PROVIDER value in the Helm install document
Installed Devtron and tested

DOC: Corrected BLOB_STORAGE_PROVIDER value

---

sample-docker-templates/django/Dockerfile
sample-docker-templates/django/nginx.default
sample-docker-templates/django/start-server.sh
sample-docker-templates/flask/Dockerfile
sample-docker-templates/flask/nginx.default
sample-docker-templates/flask/start.sh
sample-docker-templates/flask/uwsgi.ini
sample-docker-templates/node/Dockerfile
sample-docker-templates/node/nginx.default
sample-docker-templates/php/Dockerfile
sample-docker-templates/react/Dockerfile

sample-docker-templates directory has been added which consists of sample dockerfile template for different applications.

DOC: Sample Dockerfile Templates added

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/values.yaml

image pull secret

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/values.yaml

add ability to add imagePullSecrets for new objects

feat: image pull secret

---

api/restHandler/BatchOperationRestHandler.go
api/restHandler/ClusterRestHandler.go
api/restHandler/TeamRestHandler.go
api/router/TeamRouter.go
internal/sql/repository/appstore/AppStoreVersionValuesRepository.go
internal/sql/repository/team/TeamRepository.go
pkg/commonService/CommonService.go
pkg/team/TeamService.go
util/rbac/EnforcerUtil.go

Excludes projects which are soft deleted, from listing and other places where they are visible.

FIX: excludes deleted project from listing

---

docs/SUMMARY.md
docs/user-guide/telemetry.md

telemetry overview documentation, added events and its payload

DOC: telemetry overview doc

---

docs/README.md

Devtron compatibility updated in Documentation

DOC: Updated Devtron compatibility in README.md

---

manifests/updates/devtron-nats-server-override.yaml
manifests/updates/devtron-notifier-override.yaml

Metadata name of notifier-override.yaml file has been changed
-

DOC: notifier-override metadata name changed

---

api/router/pubsub/ApplicationStatusUpdateHandler.go
pkg/app/AppService.go
pkg/pipeline/WorkflowDagExecutor.go

Status update for app, cd workflow runner fails, unable to detect in logs #594

FIX: app workflow status logging

---

api/bean/AppView.go
api/restHandler/AppListingRestHandler.go
internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
pkg/user/UserService.go
scripts/sql/16_alter_indexes.down.sql
scripts/sql/16_alter_indexes.up.sql

App listing took longer time than expected. need optimisation in queries and code implementation for enforcer.

FEATURE: App listing optimization

---

CONTRIBUTING.md

Updated contributing.md for the chart contribution guidelines hyperlink

Updated Contributing.md for chart contribution guidelines

---

api/restHandler/AppListingRestHandler.go

Missing apps in app listing, bug introduced in optimisation,  FIXED casbin object. 

FIX: app listing optimisation fixes casbin object. 

---

docs/setup/install/install-devtron-using-kubectl.md

Updated Docs for kubectl install command.

DOC: Updated kubectl installation command

---

pkg/pipeline/WorkflowService.go

in certain cases user wants to expose some data from within ci. 
exposed  named container port for it.

FEATURE: app data port exposed

---

scripts/sql/17_drop_fk_security.down.sql
scripts/sql/17_drop_fk_security.up.sql

removed extra FOREIGN KEY CONSTRAINT from image_scan_deploy_info.
due to this security scan deploy info was failing  

FIX: foreign key deploy info correction

---

README.md
docs/setup/install/README.md
docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md

removed default postgres password change_me  from documentation 

DOC: removed default pg password

---

README.md
docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md

DOC: removed doc warning

---

pkg/pipeline/CdConfig.go
pkg/pipeline/CdWorkflowService.go
pkg/pipeline/CiService.go
pkg/pipeline/WorkflowDagExecutor.go

Integrated azure blob for uploading artifacts in Ci & Cd Pipelines.
The changes are tested on a kops cluster by changing the container image of microservices (devtron-orchestrator & ci-runner) used in the deployment & configMaps.

Azure blob Integration in artifact upload for CI & CD requests

---

docs/README.md
docs/SUMMARY.md
docs/setup/install/README.md
docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md
docs/setup/install/install-devtron-using-kubectl.md
docs/setup/install/installation-configuration.md
docs/user-guide/bulk-update.md
docs/user-guide/creating-application/deployment-template.md
docs/user-guide/creating-application/git-material.md
docs/user-guide/creating-application/workflow/cd-pipeline.md
docs/user-guide/global-configurations/README.md

Minor Docs changes which includes some broken links, sequence correction and deployment metrics content. Installation docs has also been changed, reduced the time duration of installation.

DOC: Docs minor changes

---

docs/user-guide/creating-application/deployment-template.md

Documentation for containers section in Deployment template added.

DOC: Updated Containers section documentation

---

api/restHandler/PipelineConfigRestHandler.go

Issue in Create Git Material and Create App Auth In Case user has only specific app access.

FIX: forbidden issue on create git material for app

---

manifests/install/install.yaml

Updated inception image with vulnerabilities fixed
Tested by crating a cluster and installing devtron on it.

FIX: Updated inception image with vulnerabilities fixed

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/metrics-service-monitor.yaml

FIX: Update metrics-service-monitor.yaml

---

manifests/install/devtron-installer.yaml
manifests/installation-script

Installation script has been fixed with new code.

FIX: Installation script fix

---

docs/user-guide/global-configurations/gitops.md

Added permissions for Personal Access token for Github, As errors were encountered during it's verification.

DOC: Updated PAT permissions for Github

---

docs/user-guide/creating-application/deployment-template.md

- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

DOC: deployment-template-errors-fix

---

docs/setup/install/install-devtron-using-kubectl.md

Postgresql password form is updated for installing devtron through kubectl.

DOC: Postgresql password form updated for kubectl

---

.github/workflows/sync.yml

This github action will sync with repo on gitee after every release

Created github action to synch with gitee 

---

scripts/sql/22_docker_password_length.down.sql
scripts/sql/22_docker_password_length.up.sql

password column length increased in docker_artifact_store table

---

manifests/yamls/dashboard.yaml
manifests/yamls/devtron.yaml
manifests/yamls/gitsensor.yaml
manifests/yamls/migrator.yaml

Updates in dashboard micro-service

RELEASE: PR for v0.2.27

---

client/argocdServer/application/Application.go
client/argocdServer/k8sClient.go
pkg/appstore/AppStoreDeploymentService.go
pkg/pipeline/PipelineBuilder.go
wire_gen.go

chart upgrade fix with lazy context timeout and namespace env driven.
Fixes # (issue): https://github.com/devtron-labs/devtron/issues/642

FIX: chart upgrade fix with lazy context timeout

---

pkg/bean/app.go

FIX: Ci patch validation added for stage

---

pkg/user/RoleGroupService.go
pkg/user/UserService.go

User auth - get roles for user and group duplicate in multiple environment case,

FIX: user auth - user and groups get roles duplicate fix

---

scripts/devtron-reference-helm-charts/reference-chart_3-12-0/.helmignore
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/.image_descriptor_template.json
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/Chart.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/env-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/pipeline-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/release-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/secrets-test-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/NOTES.txt
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/_helpers.tpl
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/hpa.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/metrics-service-monitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/poddisruptionbudget.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/pre-sync-job.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/prometheusrules.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/secret.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/service.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/servicemonitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/sidecar-configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/values.yaml
scripts/sql/23_chart_ref.down.sql
scripts/sql/23_chart_ref.up.sql

Added option in `vlaues.yaml` of chart so that user can pass Environment variable for fieldPath/fieldRef. For this user have to pass environment name and fieldPath value under `EnvVariablesFromFieldPath` of `vlaues.yaml`. It will pass by-default one value that  is getting pod name.
User can also pass resources for initContainer.

Added option to pass environment variable from field path and initContainer resources support.

---

docs/SUMMARY.md
docs/user-guide/deploy-chart/README.md

DOC: URL correction for deploy chart.

---

.github/workflows/sync.yml

Updated sync.yml to to sync with gitee

Gitee sync update

---

manifests/yamls/devtron.yaml
manifests/yamls/migrator.yaml

Updates in devtron micro-service

RELEASE: PR for v0.2.28

---

docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md

DOC: Gitee installation Documentation

---

internal/util/EcrService.go
pkg/pipeline/PipelineBuilder.go

Fixed the bug where CI build was failing when registry type was changed from non-ECR to ECR type or updating the repository in ECR config and the repository was not already present at ECR.

Fixed ECR bug

---

scripts/devtron-reference-helm-charts/reference-chart_4-10-0/.helmignore
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/.image_descriptor_template.json
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/Chart.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/env-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/pipeline-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/release-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/schema.json
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/secrets-test-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/NOTES.txt
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/_helpers.tpl
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/hpa.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/metrics-service-monitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/poddisruptionbudget.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/pre-sync-job.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/prometheusrules.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/secret.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/service.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/servicemonitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/sidecar-configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/values.yaml

K8s 1.22 compatible chart

---

docs/user-guide/creating-application/deployment-template.md

Documentation updated in Deployment template.md

DOC: [DOC]doc update in deployment-template

---

docs/user-guide/creating-application/deployment-template.md
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/deployment.yaml

feat: Allow custom headers on LivenessProbe and ReadinessProbe

---

manifests/yamls/devtron.yaml
manifests/yamls/migrator.yaml

Updates in devtron micro-service

RELEASE: PR for v0.3.0

---

README.md

Added community contributions file in README under contributions section

DOC: Added community contributions in README

---

manifests/installation-script
manifests/yamls/nats-server.yaml
manifests/yamls/nats-streaming.yaml

Nats server multiple replica caused issues.

Intermittent NATS issue fix

---

pkg/pipeline/ChartService.go
util/ValidatorHelper.go

decimal value in memory

---

manifests/installation-script
scripts/sql/1_insert.up.sql

Auto scaler chart added in default devtron OSS installation. 
Index issue fixed for chart repos
Tested using devtron's installation from a local branch.

autoscaler chart added & fix index issue

---

manifests/yamls/nats-server.yaml

Replaces the Docker Image used by container with Quay one.

Replaces docker image with quay

---

docs/user-guide/creating-application/deployment-template.md

Added  'imagePullSecrets' in documentation of deployment template.

DOC: imagePullSecrets-doc-update

---

scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/ingress.yaml

it fixes the separator issue being written infront of apiVersion while deploying an app

Fix: Ingress internal fix

---

internal/sql/repository/AppListingRepository.go

parse material info panic recover

---

scripts/devtron-reference-helm-charts/reference-chart_3-10-0/schema.json
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/schema.json
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/schema.json
scripts/devtron-reference-helm-charts/reference-chart_3-9-0/schema.json
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/schema.json

schema-update

---

manifests/yamls/serviceaccount.yaml

Fix: Updated permissions for devtron clusterrole

---

manifests/yamls/devtron-ingress-legacy.yaml
manifests/yamls/devtron-ingress.yaml

This PR adds grafana path to the ingress
Grafana isn't accessible with the current default ingress file

FIX: Added grafana path in ingress

---

docs/setup/install/README.md

we can Upgrade devtron to newer version.

[DOC]: doc update for upgrade devtron

---

docs/user-guide/creating-application/deployment-template.md

Added reuseContainerImage description inside initContainer in deployment template documentation.

DOC: initContainer-reuseContainerImage-doc

---

Makefile
api/router/router.go
specs/version.yml
util/version.go

added support for version and server info

Version api

---

docs/SUMMARY.md

Added link in the summary section

DOC: Link added in summary.md file 

---

docs/SUMMARY.md
docs/setup/upgrade/README.md

DOC: link updated

---

api/restHandler/AppStoreDeploymentRestHandler.go
authWire.go
internal/sql/repository/appstore/AppStoreDeploymentRepository.go
pkg/appstore/AppStoreDeploymentService.go
wire_gen.go

Updated api response for fetching helm apps as per the response object used in external apps.

Updated helm app list response

---

api/restHandler/AppStoreDeploymentRestHandler.go
internal/sql/repository/appstore/AppStoreApplicationVersionRepository.go
internal/sql/repository/appstore/AppStoreDeploymentRepository.go
pkg/appstore/AppStoreDeploymentService.go
specs/external-app/applist.yaml

Updated chart store GET api with inclusion of clusterIds in api request params and respository query update. Added open api spec.

updated chart store get api

---

docs/user-guide/creating-application/deployment-template.md

This is a small fix in documentation of examples of autoscaling using KEDA

Fix: keda doc in deployment template

---

docs/setup/upgrade/devtron-upgrade-0.2.x-0.3.x.md
docs/user-guide/telemetry.md

DOC: Changes in telemetry file

---

docs/user-guide/creating-application/deployment-template.md

DOC: volume-and-volumemount-example-included

---

docs/SUMMARY.md
docs/user-guide/creating-application/deployment-template.md
sample-docker-templates/java/Gradle_Dockerfile
sample-docker-templates/java/Maven_Dockerfile

Added Sample Dockerfiles for Java using Maven & Gradle.
Deployment template docs fixes and added job-cronjob in the side-bar (Summary.md)

DOC: Added java Sample Dockerfiles & Docs fixes

---

manifests/yamls/grafana.yaml

Grafana test crashloop issue fix.
Tested on a oss cluster

Grafana test crashloop issue fix

---

util/ValidatorHelper.go
util/ValidatorHelper_test.go

Regex to validate cpu and memory was likely causing cpu consumption hence replacing it with apimachinery code.
Fixes #1033 
Unit test cases have been tested.

bug: replaced custom code with apimachinery code

---

docs/user-guide/creating-application/deployment-template.md

DOC: Added fullnameOverride in dep. template

---

docs/user-guide/creating-application/deployment-template.md
docs/user-guide/global-configurations/cluster-and-environments.md

Explained how generate token to add cluster on devtron

DOC: Generate token to add cluster

---

docs/setup/install/installation-configuration.md

Documentation updated new parameters for dashboard configuration.

[DOC]: docs updated in dashboard parameters

---

docs/SUMMARY.md

DOC: edited summary.md

---

docs/user-guide/global-configurations/gitops.md

DOC: GitOps image fix

---

docs/user-guide/creating-application/app-metrics.md

Documentation updated for percentile latency metrics.

[DOC]: docs update for percentile latency

---

authWire.go
go.mod
go.sum
vendor/github.com/devtron-labs/authenticator/client/k8sClient.go
vendor/modules.txt
wire_gen.go

take local dev mode from env variable instead of constant

local dev env mode

---

scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/keda-autoscaling.yaml

Some fields are introduced in new Keda controller version and we had some values of those fields by default in keda-template
This PR fixes the issue of those fields as now the fields will be optional, if used then only those values will be used

FIX: Made some keda-values optional for backward compatibility

---

pkg/pipeline/WorkflowDagExecutor.go

bug-fix_1062

---

pkg/pipeline/WorkflowDagExecutor.go

Bug fix 1062

---

api/helm-app/applicationClient.go

connection reuse

---

docs/user-guide/creating-application/deployment-template/rollout-deployment.md
manifests/yamls/guard.yaml
manifests/yamls/lens.yaml

This PR fixes guard and lens HPAs not working on recent releases

FIX: Guard and Lens HPA deployment apiVersions

---

docs/user-guide/creating-application/workflow/cd-pipeline.md

Added steps to create a sequential pipelines.

DOC: Sequential pipelines doc

---

README.md
docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md
docs/setup/install/install-devtron-using-kubectl.md
manifests/yamls/rollout.yaml

This PR adds a FAQ to the list about rollout-crds and fix docs for devtron delete instructions

DOC: New Readme FAQs and devtron delete instructions

---

manifests/updates/production/devtron-argocd-override.yaml
manifests/updates/production/devtron-clair-override.yaml
manifests/updates/production/devtron-external-secret-override.yaml
manifests/updates/production/devtron-gitsensor-override.yaml
manifests/updates/production/devtron-guard-override.yaml
manifests/updates/production/devtron-image-scanner-override.yaml
manifests/updates/production/devtron-ingress-override.yaml
manifests/updates/production/devtron-lens-override.yaml
manifests/updates/production/devtron-minio-override.yaml
manifests/updates/production/devtron-minio-storage-override.yaml
manifests/updates/production/devtron-nats-streaming-override.yaml
manifests/updates/production/devtron-notifier-override.yaml
manifests/updates/production/devtron-workflow-override.yaml

Production manifests doc indentation issue.

[DOC]: production doc indentaion

---

pkg/user/RoleGroupService.go
pkg/user/UserService.go
scripts/sql/31_alter_roles.down.sql
scripts/sql/31_alter_roles.up.sql

- Ea user auth permission remove issue fixed
- Db migration for roles fixed
- 

Fix: Ea user auth permission remove issue fixed

---

client/k8s/application/Application.go

non namespaced resources fixed for fetching and edit

non namespace resources api call fixed

---

pkg/sso/SSOLoginService.go

sso config update failed issue fixed for empty config map.

sso config update fixed 

---

pkg/cluster/EnvironmentService.go
scripts/casbin/3_insert.down.sql
util/rbac/EnforcerUtil.go

Fixes for user permission on helm apps, impacted by environment indetifier
db migration down script added.
checks added, handle for invalid cluster config on namespace list group cluster api.

Review fix ea

---

manifests/installation-script

script fix

---

README.md

Changed ReadMe according to the new Tagline and Description

ReadMe Updation: 

---

README.md

ReadMe Updation

---

api/helm-app/HelmAppRestHandler.go
util/k8s/k8sApplicationRestHandler.go
util/k8sObjectsUtil/SecretUtil.go
util/k8sObjectsUtil/SecretUtil_test.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
vendor/modules.txt

obfuscation of secret for view access users on:
1. Get resource API
2. Get desired manifest API

obfuscation of secret for 1) get resource 2) get desired manifest

---

manifests/installation-script

Temporary fix for Grafana pod not up and curl scripts not tun.

[FIX] Temporary fix for Grafana curl not done issue

---

api/helm-app/HelmAppRestHandler.go
util/CommonConstant.go
util/k8sObjectsUtil/SecretUtil.go
util/yaml/YamlUtil.go

unfs secret in deployment history (#1144)

---

docs/user-guide/deploy-chart/examples/deploying-mongodb-helm-chart.md

Updated documentation and image for deploying mongodb helm chart

DOC: documentation update for deploying mongodb chart

---

api/cluster/EnvironmentRestHandler.go
api/cluster/EnvironmentRouter.go
client/k8s/informer/K8sInformerFactory.go
pkg/cluster/EnvironmentService.go
pkg/cluster/repository/EnvironmentRepository.go
specs/environment.yaml

Latency issue on app listing and user access for namespace list fixed by few below steps
- Skip auth checks for super admin
- Auth checks apply for specific cluster instead of all cluster all the time.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1176

FIX: Latency issue on app listing and user access for namespace list

---

manifests/yamls/dashboard.yaml

Show Enable app metrics toggle by default in oss stack

FEAT: Show Enable app metrics toggle by default in oss

---

docs/user-guide/deploy-chart/examples/deploying-mysql-helm-chart.md

Update documentation and image for `deploying-mysql-helm-chart.md`.

DOC: Mysql chart doc update

---

manifests/yamls/serviceaccount.yaml

This PR fixes permissions for hyperion

Fix: Updated devtron clusterrole as cluster-admin

---

docs/hyperion/README.md

Updated Hyperion install broken link

DOC: Updated Hyperion install broken link

---

docs/hyperion/README.md

Hyperion installation Guide has been fixed

DOC: Fixed hyperion installation link

---

docs/user-guide/deploy-chart/deployment-of-charts.md

Updated documentation and images in deployment-of-charts.md file.

DOCS: updates in deployment-of-charts

---

docs/user-guide/creating-application/deployment-template/rollout-deployment.md

Documentation update in deployment-template for envoyTimeout.

DOC: Doc update for deployment-template

---

README.md

Updated the menu in README with Trusted By section

DOC: Readme menu updated

---

docs/user-guide/global-configurations/cluster-and-environments.md

Updated images to fetch from s3 in cluster and environments page.

DOC: Updated image in cluster and env to s3

---

docs/user-guide/creating-application/README.md
docs/user-guide/global-configurations/README.md

Link to the Youtube videos(App deployment & Global Configuration) has been added.

DOC: Added Youtube videos

---

pkg/cluster/EnvironmentService.go

Namespace list group by cluster, duplicate entry fixed
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1258

Fix :  namespace list group by cluster, duplicate entry fixed

---

pkg/appStore/AppStoreDeploymentService.go

Hotfix commit and nil pointer on chart install
Fixes # (issue) :

FIx: hotfix commit and nil pointer on chart install

---

docs/SUMMARY.md
docs/user-guide/Deploy-sample-app/nodejs_app.md

Added documentation for deploying sample application through devtron

DOC: Sample-app-deployment-updated

---

docs/user-guide/Deploy-sample-app/nodejs_app.md

Updated changes in demo-app documenation.

DOC: Updated changes in demo-app doc

---

Wire.go
internal/util/ChartService.go
util/GlobalConfig.go
wire_gen.go

configurable prefix for gitops repo name, added opt-out feature for devtron apps for gitops prefix.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1283

FEAT: configurable prefix for gitops repo name

---

pkg/user/UserService.go
pkg/user/casbin/rbac.go

devtron is not able to parse latest token generated by argocd

fix for argocd token

---

manifests/updates/production/devtron-kubelink-override.yaml
manifests/updates/production/devtron-nats-streaming-override.yaml
manifests/updates/production/devtron-postgresql-override.yaml

Fix resources in prod overrides for devtron-nats. devtron-stan, postgresql, kubelink
Resources in prod overrides
Tested by appyling overrides, and then installing the devtron stack

FIX: Resources in prod overrides

---

scripts/devtron-reference-helm-charts/reference-chart_4-10-0/schema.json

Schema.json for chart 4.10 of rollout deployment type was corrupt, resulting into broken user experience.
Updated the schema

fix: fixed schema for chart 4.10

---

docs/SUMMARY.md

Added Link for Devtron Upgrade 0.3.x-0.3.x in Summary.md 

Doc: Added Link for Devtron Upgrade 0.3.x-0.3.x in Summary.md

---

docs/FAQs/devtron-troubleshoot.md

updated few more troubleshooting steps in Devtron's troubleshooting guide.

DOC: Updated Troubleshooting Guide

---

sample-docker-templates/php/php7.4/Dockerfile
sample-docker-templates/php/php7.4/nginx-site.conf

php7.4-nginx microservice sample dockerfile added

---

docs/FAQs/devtron-troubleshoot.md
docs/hyperion/user-guide/global-configurations/user-access.md

Devtron's FAQ images fixed and Hyperion user-access heading fixed

DOCS: Drvtron Faq & Hyperion user-access minor fix

---

.github/ISSUE_TEMPLATE/enhancement_proposal.md
.github/pull_request_template.md

Added section for unit test cases in checklist in PR template and added section for Testing guidelines for new feature enhancements
Fixes #1364 
Documentation update. No application testing.

[DOC] Updated documentation for PR and enhancement proposal

---

docs/setup/install/installation-configuration.md

Added Env var in Installation Configuration
CI_DEFAULT_ADDRESS_POOL_BASE_CIDR
CI_DEFAULT_ADDRESS_POOL_SIZE       
CD_DEFAULT_ADDRESS_POOL_BASE_CIDR
CD_DEFAULT_ADDRESS_POOL_SIZE
GITOPS_REPO_PREFIX

DOC: Docker Network CIDR in Documentation 

---

docs/hyperion/user-guide/global-configurations/cluster-and-environments.md

Doc images for `Cluster and Environments` (Hyperion) were broken. Changed URLs for images used on this page.

DOC: URL change for images in cluster and environments (hyperion)

---

README.md

Video Update README.md 

---

README.md

Minor Changes ReadMe

---

manifests/install/devtron-installer.yaml

This PR does a Rollback for devtron LTAG

Rollback devtron LTAG

---

docs/setup/install/install-devtron-helm-2.md
docs/setup/install/install-devtron-helm-3.md
docs/setup/install/install-devtron-using-kubectl.md

Converted installation status message in tabular form.

DOC : installation status message in tabular form

---

docs/user-guide/deploy-chart/chart-group.md

Updated documentation and images in chart-group.md file.

DOC: Updated documentation for chart group

---

docs/user-guide/creating-application/secrets.md

Typo correction in secrets.md file

DOC: typo correction in secrets

---

pkg/appStore/AppStoreDeploymentService.go
pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go

Hotfix, environment name missing in older apps for gitops repo name for in few cases. fixed in this PR.

FIX: hotfix environment name setup for gitops repo name

---

pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go

Hotfix, ACD context issue for some cases in gitops repo name to fetch from acd. FIXED

Fix: ACD context fix for gitops repo name

---

docs/user-guide/global-configurations/docker-registries.md

Added how can we use private registry to push image and pull image using imagePullSecrets. Also explained how can we create imagePullSecrets using `dt-secrets` charts.

DOC: integrating external container registry doc

---

scripts/sql/40_chart_ref.up.sql

Changed the default chart to rollout 4.11.0

FIX: added default chart as rollout-4.11.0

---

docs/setup/upgrade/devtron-upgrade-0.3.x-0.3.x.md

Added Steps to updrate devtron using kubectl for 0.3.x-03.x

DOC: Added Steps for Upgrading Devtron using Kubectl for 0.3.x

---

api/helm-app/HelmAppRestHandler.go

Few bug fixes in hibernate/unhibernate helm apps.
1) RBAC (checking update RBAC now)
2) request object decoding in unhibernate
Fixes # https://github.com/devtron-labs/devtron/issues/1425
By hitting hibernate & un-hibernate APIs

fix: Bug fixes in hibernate/unhibernate helm apps

---

cmd/external-app/router.go
cmd/external-app/wire.go
cmd/external-app/wire_gen.go

Events and Wire changes for hyperion
Events and Wire changes for hyperion
- [yes ] New feature (non-breaking change which adds functionality)

fix: Wire changes for hyperion[1436]

---

internal/util/EcrService.go

Fixes #1494 
Create ECR type container registry without user name and password and run CI pipeline with security enabled. It should complete it successfully. try this again after it has been idle for 14 hrs.

Ecr role login

---

docs/user-guide/global-configurations/user-access.md

Documentation and image updated for user access.

[DOC]: Doc update for user access

---

docs/user-guide/creating-application/workflow/ci-pipeline.md
docs/user-guide/namespaces-and-environments.md

Added steps and screenshots for creating linked ci pipeline.

DOC:  Steps for creating linked ci pipeline

---

pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go

Added missing source info in deployment history
Fixes # (issue): https://github.com/devtron-labs/devtron/issues/1490

Fix: added missing source info in deployment history

---

manifests/yamls/migrator.yaml
manifests/yamls/postgresql.yaml

Added a new job for database creation

Added a new job for database creation

---

manifests/yamls/image-scanner.yaml

Release fix

---

scripts/sql/1_insert.up.sql

Changed the sequence of helm repos in sql file

update the sequence of helm repos in sql queries

---

docs/user-guide/deploy-chart/chart-group.md
docs/user-guide/deploy-chart/deployment-of-charts.md
docs/user-guide/deploy-chart/overview-of-charts.md

Changed screenshot used in deploy charts documentation. Also added deployment history of Helm applications in the documentation.

DOC: deploy charts images update

---

docs/setup/upgrade/devtron-upgrade-0.3.x-0.3.x.md

Added single quotes to fix kubectl patch for devtron upgrade in 0.3.x-0.3.x 

DOC: Minor Fix for devtron upgrade by kubectl

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/ingress.yaml

Updated ingress.yaml as per https://github.com/devtron-labs/devtron/pull/1349/files for chart 3.11.0-4.10.0

Ingress update for legacy

---

docs/user-guide/creating-application/app-details.md

Correction in format for linking image URL in the documentation.

docs: image url correction in app-details.md

---

docs/user-guide/creating-application/app-details.md

image placing correction in app-details.md. The image was placed inside '>' .

docs: image placing  correction in app-details.md

---

scripts/devtron-reference-helm-charts/reference-chart_4-11-1/.helmignore
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/.image_descriptor_template.json
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/Chart.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/README.md
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/env-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/pipeline-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/release-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/schema.json
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/secrets-test-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/NOTES.txt
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/_helpers.tpl
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/hpa.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/keda-autoscaling.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/metrics-service-monitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/poddisruptionbudget.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/pre-sync-job.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/prometheusrules.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/secret.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/service.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/serviceaccount.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/servicemonitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/templates/sidecar-configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-1/values.yaml

feat : Chart v4.11.1 supports service account 

---

client/argocdServer/application/Application.go

New pods are getting shown in old pods section
Classify pods properly
- [Yes ] Bug fix (non-breaking change which fixes an issue)
- [No ] New feature (non-breaking change which adds functionality)

Workflow chart

---

docs/user-guide/global-configurations/docker-registries.md

Adding the `ECR` container registry type in **Global Configurations > Container registries** to include both Key-based and Role-based authentications.

docs: Adding ECR registry type in Container registries

---

internal/util/K8sUtil.go

Custom error added on resource info.

FIX: custom error handling on inception resource

---

scripts/devtron-reference-helm-charts/reference-chart_4-12-0/templates/serviceaccount.yaml

Updated indent in serviceaccount.yaml of 4-12 chart

Updated indent in serviceaccount of 4-12 chart

---

api/restHandler/WebhookEventHandler.go

Made Event type non mandatory in webhook handler to support Azure Devops git provider. 
Azure Devops PR webhook

fix : made event type non mandatory in webhook handler

---

scripts/casbin/1_insert.up.sql

casbin db migration script failure on startup. 
- table creation conflicts the schema migrations versions to dirty.

FIX: casbin db migration script failure on startup.

---

manifests/yamls/image-scanner.yaml
manifests/yamls/kubewatch.yaml
manifests/yamls/lens.yaml

Image fixes for release v0.4.0

Release 0.4.0 image fixes

---

docs/FAQs/devtron-troubleshoot.md

Added the questions and solutions in troubleshoot guide doc.

DOC: added problem solutions in troubleshoot guide

---

api/deployment/DeploymentConfigRestHandler.go
api/deployment/DeploymentConfigRouter.go
pkg/pipeline/ChartService.go

After uploading user gets to see the uploaded chart name and description then user can save or cancel it if he needs to update name
- [ yes] Bug fix (non-breaking change which fixes an issue)

fix: deployment template

---

api/restHandler/app/DeploymentPipelineRestHandler.go
pkg/security/policyService.go

Response time of artifacts API for cd pipeline increases significanly when security scanning is enabled
Test performance of fetch cd pipeline artifact API with security scanning enabled and also images with critical vulnerabilities are blocked.

FIX: code change to optimize cve listing

---

scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/Cronjob.yaml
scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0/templates/cronjob.yaml

Added parallelism field in jobtemplate spec section

Added parallelism in jobtemplate spec

---

api/restHandler/app/DeploymentPipelineRestHandler.go

In order to decide whether image as vulnerability or not, we were checking presence in map rather than the boolean value in map.

FIX: fixed bug for the cve list

---

docs/setup/install/README.md
docs/setup/install/install-devtron-with-cicd.md
docs/setup/install/install-devtron.md

Updating helm command in installing Devtron page

docs: Updating helm command in installing Devtron page

---

.gitignore
charts/devtron/Chart.yaml
charts/devtron/README.md
charts/devtron/crds/crd-devtron.yaml
charts/devtron/templates/NOTES.txt
charts/devtron/templates/app-sync-job.yaml
charts/devtron/templates/argocd-secret.yaml
charts/devtron/templates/configmap-secret.yaml
charts/devtron/templates/dashboard.yaml
charts/devtron/templates/devtron-ingress.yaml
charts/devtron/templates/devtron-installer.yaml
charts/devtron/templates/devtron-service.yaml
charts/devtron/templates/devtron.yaml
charts/devtron/templates/dex.yaml
charts/devtron/templates/install.yaml
charts/devtron/templates/kubelink.yaml
charts/devtron/templates/migrator.yaml
charts/devtron/templates/postgresql.yaml
charts/devtron/templates/production-overrides.yaml
charts/devtron/templates/rbac.yaml
charts/devtron/values.yaml

Adding Devtron operator helm chart to the main repo for easier maintenance.
Tested on forked Repo

Added Devtron chart into main reppo

---

.github/workflows/chart-sync.yaml
.github/workflows/sync.yml

Added chart-sync workflow to sync charts on devtron-charts.

FEAT: Added chart-sync workflow

---

charts/devtron/Chart.yaml
charts/devtron/values.yaml
docs/setup/install/install-devtron-with-cicd.md

doc: Doc hotfixes

---

docs/setup/upgrade/devtron-upgrade-0.3.x-0.4.x.md

Updating the devtron-bom.yaml file for the latest Devtron tag in the upgrading Devtron "0.3.x-0.4.x" page.

docs: Updating the devtron-bom.yaml file for the latest Devtron tag

---

README.md

Updating the CI/CD hyperlink to the right section in the README file.

Updating the CI/CD hyperlink to the right section

---

docs/user-guide/global-configurations/user-access.md

Corrections in user access documentation

DOC: corrections in user access doc

---

README.md
docs/SUMMARY.md
docs/setup/install/README.md
docs/setup/install/install-devtron.md

Promote Devtron installation with CI/CD on the installation page as well as in the `README.md`.

docs: Promote Devtron installation with CI/CD

---

scripts/sql/51_external_link.down.sql
scripts/sql/51_external_link.up.sql

Migration script has been added for external links

Migration script for external links

---

charts/devtron/templates/NOTES.txt

This PR fixes Notes.txt issues

Fixed NOTES.txt file

---

docs/SUMMARY.md

Adding an entry for custom charts page in the `SUMMARY.md` file.

Adding an entry for custom charts page

---

docs/user-guide/global-configurations/custom-charts.md

Updating the images links from S3 bucket
The links were still pointing to the local storage.

docs: Updating the images links from S3 bucket

---

README.md

readme refactor

---

docs/SUMMARY.md
docs/user-guide/creating-application/deployment-template.md

docs: Hiding the custom charts page until the feature is released.

docs: Hiding the custom charts page

---

api/user/SelfRegistrationRolesHandler.go
pkg/user/UserService.go

User email will be pulled from token instead of payload

fetching data from token instead of payload

---

charts/devtron/Chart.yaml
charts/devtron/devtron-bom.yaml
charts/devtron/templates/dex.yaml
charts/devtron/values.yaml

Fixes an issue in Devtron upgrade where Dex image renders as null

Bug: Dex installation through chart upgrade

---

scripts/devtron-reference-helm-charts/reference-chart_3-2-0/.helmignore
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/.image_descriptor_template.json
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/Chart.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/app-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/env-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/pipeline-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/release-values.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/NOTES.txt
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/_helpers.tpl
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/hpa.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/metrics-service-monitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/pre-sync-job.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/secret.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/service.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/servicemonitor.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/templates/sidecar-configmap.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-2-0/values.yaml

Added back 3.2.0 reference chart that got removed

---

docs/setup/upgrade/README.md

Correction in devtron upgrade README.md

docs: correction in devtron upgrade readme

---

pkg/pipeline/PipelineBuilder.go

Error on cd pipeline delete when there is no ACD app found.

FIX: cd pipeline delete issue for ACD app

---

pkg/app/AppService.go
pkg/pipeline/PipelineBuilder.go

Git repo url missing on charts, error on cd trigger, no git url found for commit files.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1812

Fix: Git repo url missing on charts, error on cd trigger

---

docs/FAQs/devtron-troubleshoot.md
docs/setup/upgrade/devtron-upgrade-0.3.x-0.4.x.md

Some steps in the Devtron stack upgrade were not correct. Fixed upgrade steps and added a new FAQ.

DOC: Fixed Devtron upgrade docs and updated FAQ

---

internal/util/ChartService.go

hotfix for chart push chart attribute panic handling

Fix: hotfix for chart push chart attribute panic handling

---

internal/util/ChartService.go
pkg/app/AppService.go

unused return parameter removed

Fix: unused return parameter removed

---

pkg/pipeline/history/DeployedConfigurationHistoryService.go

Configuration will not show pipeline configuration if there is no data incase of custom charts strategy is not explicitly stored we use it from values.yaml file directly 
Fixes #1847 
Tested by uploading charts and deploying applications using them

Update Pipeline Configuration

---

charts/devtron/templates/app-sync-job.yaml
charts/devtron/templates/migrator.yaml

Fixes an issue where a fresh Devtron installation did not show any helm charts unless a manual refetch charts was done from the UI.
Fixes #1863
Tested by installing via helm on a test k8s cluster

Chart store fetch helm charts job fix

---

client/telemetry/TelemetryEventClientExtended.go
internal/sql/repository/app/AppRepository.go
internal/sql/repository/pipelineConfig/CiPipelineRepository.go
internal/sql/repository/pipelineConfig/CiTemplateRepository.go
internal/sql/repository/pipelineConfig/MaterialRepository.go
internal/sql/repository/pipelineConfig/PipelineRepository.go
pkg/chartRepo/repository/ChartRepoRepository.go
wire_gen.go

Update payload for telemetry events to understand customer requirements
Testing by running application and see the events in PostHog

Task update payload

---

docs/setup/upgrade/devtron-upgrade-0.4.x-0.4.x.md

Doc update for 0.4.x to 0.4.x with labels and annotations

[DOC] Updated labels and annotations for 0.4.x-0.4.x

---

docs/SUMMARY.md

Added custom  charts documentation

DOC: Added custom-charts docs

---

client/pubsub/NatsClient.go
client/pubsub/natsClient_test.go

Logging added for nats client re-connection & disconnection. Would be helpful in debugging any issue. I have also added test cases on NatsClient.
Fixes #1873

nats client logging & test case added

---

docs/setup/install/installation-configuration.md

Added instructions to enable versioning on Azure blob storage for using with Devtron

[DOC] Added instructions to enable versioning on Azure blob storage for using with Devtron

---

internal/util/ChartService.go
internal/util/GitCliUtil.go
internal/util/GitService.go
internal/util/GitServiceAzure.go
internal/util/GitServiceBitbucket.go
pkg/app/AppService.go
pkg/pipeline/PipelineBuilder.go
scripts/argo-assets/APPLICATION_TEMPLATE.JSON

fixes around already existing git repo clone and push, handling branches, ref chart overrides issues
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1918.
Create CD pipeline and Trigger deployment via below use cases

Fix: Existing git repo - clone and push issues fixed

---

docs/setup/install/README.md

Docs: fixed broken link

---

api/cluster/ClusterRestHandler.go
api/restHandler/PipelineTriggerRestHandler.go
pkg/cluster/ClusterService.go
pkg/cluster/ClusterServiceExtended.go

Added fix for issue 1596 where in update cluster request were failing with 500 error
Fixes #1596 
Have tested locally against demo1 environment with valid cluster and trying to update it. Got proper 200 response
* [] I have added all the required unit/api test cases

Fix for 1596: Added check for empty prometheus url

---

.github/workflows/create-release.yml

Added workflow to create a new release after testing

Added workflow to create a new release after testing

---

.github/workflows/create-release.yml

fixed create-release wf

---

pkg/user/casbin/Adapter.go
pkg/user/casbin/rbac.go

Handle Panic on  casbin enforcer and casbin remove and add policy loads failed operation.
Fixes # (issue): https://github.com/devtron-labs/devtron/issues/1678

Hotfix : panic handling casbin loads fails

---

util/k8s/k8sCapacityService.go

Kube capacity node listing page shows error even when no error is found.

fix: kube capacity node error fix

---

api/restHandler/app/PipelineConfigRestHandler.go

Fixed error handling for app clone service.

hotfix for error handling for app clone service

---

pkg/user/casbin/Adapter.go

xormadapter import
- Successful build

FIx: xormadapter import

---

pkg/chart/ChartService.go
scripts/devtron-reference-helm-charts/reference-chart_4-12-0/schema.json
util/ValidatorHelper.go

Currently if user wants to save deployment template for gpu resource configuration, s/he is not able to do it because of mandatory validation on cpu and memory resources which are not required in case of gpu. Bypassed this validation for the latest chart available to enable user to configure gpu.

support for gpu resource in deployment template

---

pkg/user/casbin/rbac.go

Enforcer works on lowercased email id, wo we need to pass emailid as lowercase string.
Upper case Email id was created and tested data for that user.

Enforcer Rbac email case sensitive fix

---

docs/user-guide/global-configurations/README.md

global configuration readme update

docs: global configuration readme update

---

docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
docs/user-guide/creating-application/workflow/ci-pipeline.md

SonarQube doc update
Screenshot update

docs: SonarQube doc update

---

docs/SUMMARY.md
docs/user-guide/creating-application/docker-build-configuration.md

docs: Buildx documentation

---

scripts/devtron-reference-helm-charts/reference-chart_3-10-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-6-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-7-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-8-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-9-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-12-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/generic.yaml

Fixed the issue in generic.yaml in all reference chart till 3.6
Not getting the rawYaml resources to be apply during CD.

fix: Fixed the generic.yaml in all reference charts till 3.6

---

docs/user-guide/creating-application/config-maps.md
docs/user-guide/creating-application/secrets.md

image change for config map and secret data volume

docs: Image change in config-map and secret

---

.github/workflows/azure-devops-issue-sync.yml

This workflow will sync new git hub issues to Azure board work items
Fixes # (No ticket created for this work item)
Will be tested once it's committed by creating a new git hub test issue

Add workflow to sync new github issues to azure board

---

README.md

Readme presentation minor fixes

DOC: Readme minor fixes

---

api/restHandler/app/AutoCompleteRestHandler.go
api/restHandler/app/PipelineConfigRestHandler.go

Dropdown apis authorization  modifications for super admin

Feat: Dropdown apis authorization  modifications for super admin

---

docs/user-guide/creating-application/git-material.md
docs/user-guide/global-configurations/cluster-and-environments.md
docs/user-guide/global-configurations/docker-registries.md
docs/user-guide/global-configurations/git-accounts.md

documentation updates in git-material.md, cluster-and-environments.md, docker-registries.md and git-accounts.md

docs: documentation update

---

pkg/user/SelfRegistrationRolesService.go

corrected userId check in case of self registration 

corrected userId check in case of self registration 

---

pkg/appStore/deployment/common/AppStoreDeploymentCommonService.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

delete duplicate return

---

docs/SUMMARY.md

Docs older version, fixed branch for docs versioning.

DOC: Docs old version, hyperion removed

---

docs/FAQs/devtron-troubleshoot.md

Included errors in devtron FAQs.

docs: included errors in devtron FAQs

---

scripts/sql/70_slack_notification_template.down.sql
scripts/sql/70_slack_notification_template.up.sql

Scripts to update slack notification templates to use event timestamp to show date-time in the current timezone.
Fixes - https://github.com/devtron-labs/devtron/issues/2110
All tests have been performed manually.

Enhancement - Slack notification updates scripts

---

scripts/sql/70_slack_notification_template.up.sql

Replaced eventTimestamp with eventTime

Replaced eventTimestamp with eventTime

---

docs/user-guide/creating-application/workflow/ci-pipeline.md

Added documentation for branch regex

docs: Branch regex doc

---

docs/user-guide/creating-application/workflow/ci-pipeline.md

branch regex pipe seperation correction

docs: branch regex pipe seperation correction

---

README.md

Devtron preview cluster link added.

docs: Added Devtron preview Link

---

README.md

Add Demo link with explanation in the README.md
NA

Add demo text

---

api/router/pubsub/ApplicationStatusUpdateHandler.go
pkg/app/AppService.go

Updated conditions for cd pipeline status timeline. Added logs for better debugging around this areas.

fix: updated conditions for creating pipeline status timeline

---

.github/workflows/azure-devops-issue-sync.yml

Looks like bug in the github action we are using. It's not actively maintained either. Hence removing few triggers to check if it fixes the issue
Removed few triggers which looks like are resulting in duplicate issues getting created in ADO. Will check if this fixes the issue
Fixes # (issue) N/A
Will test it directly after the job is run on a new issue

Fix for duplicate work items

---

docs/user-guide/creating-application/deployment-template/rollout-deployment.md
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/README.md
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/deployment.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/test_values.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/values.yaml

Provide the support for security context in reuse init containers in reference helm chart 4-13

Support for security context in reuse init containers

---

scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/deployment.yaml

Update the 4-13 reference chart for support of context security in init containers

---

charts/devtron/templates/app-sync-job.yaml

Support of backwards compatibility for job and cronjob in devtron helm chart
Fixes #1963

helm: Support of backwards compatibility for job and cronjob in devtron helm chart

---

charts/devtron/templates/devtron.yaml
charts/devtron/values.yaml
docs/setup/install/installation-configuration.md
manifests/yamls/devtron.yaml

Documentation for how to use custom overrides

DOC: Documentation for custom overrides

---

scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/externalsecrets.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/test_values.yaml

This PR enables the ESO support for `AWS Secret Manager`,  `Hashicorp Vault`, `Azure Key Vault` and `GCP Secret Manager`

FEAT: ESO support

---

pkg/pipeline/CdHandler.go
pkg/pipeline/DbPipelineOrchestrator.go
pkg/pipeline/PipelineBuilder.go
pkg/pipeline/WorkflowDagExecutor.go

handled no gitops case for deployment status timeline

---

charts/devtron/devtron-bom.yaml

updated argocd-dex server image and cicdauthenticator image

update argocd-dex server image and cicdauthenticator image

---

internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
pkg/pipeline/CdWorkflowService.go
pkg/pipeline/WorkflowDagExecutor.go

updated deployment details in post cd payload(#1849)

---

api/user/UserRestHandler.go
api/user/UserRouter.go
pkg/user/RoleGroupService.go
pkg/user/UserService.go

The requirement came to download User and group permission data. API for detailed User & group permissions data is created to satisfy this requirement.
Fixes #2287

API for detailed User & group permissions data

---

client/events/EventBuilder.go

Event time sent to notifier in the wrong format, Corrected the format.
Fixes #2284

change reverted back to original layout #2181

---

docs/user-guide/use-cases/devtron-generic-helm-chart-to-run-cron-job-or-one-time-job.md

Documentation update for cronjob and Job chart support.

[DOC]: Cronjob and Job chart support.

---

charts/devtron/templates/argocd-secret.yaml
manifests/installation-script

External Secrets Operator helm repo has been added in the default charts in Devtron's Chart Store

FEAT: Added external-secrets helm repo in Devtron's default chart store

---

scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/generic.yaml
scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0/templates/generic.yaml

Fix the issue during multiple k8s resources  creation using rawYaml for cronjob reference charts(1-2-0 and 1-3-0) 

Update the generic.yaml for cronjob reference charts

---

README.md

Devtron readme update. URL correction for faq and troubleshooting page.

docs: devtron-readme-update-faq

---

charts/devtron/Chart.yaml

updated chart version

---

internal/sql/repository/security/CvePolicyControle.go
pkg/cluster/EnvironmentService.go
pkg/security/policyService.go
scripts/sql/75_security_policy_app_data_correction.sql
scripts/sql/75_security_policy_env_data_correction.sql

These changes will fix the issue with the security policy inheritance issue. 
Fixes #[2340](https://github.com/devtron-labs/devtron/issues/2340)

Security policy update hotfix

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Updated Bug template to remove the icon

Updated Bug template to remove the icon

---

pkg/module/Bean.go
pkg/module/ModuleCacheService.go
pkg/module/ModuleService.go
scripts/sql/77_security_clair_modularisation.down.sql
scripts/sql/77_securty_clair_modularisation.up.sql

Handling security.clair module as assuming first release integration
By testing integration system

fix: handling security clair as first release integration

---

go.mod
go.sum
vendor/modules.txt

Fix: authenticator modified

---

go.mod
go.sum
vendor/github.com/devtron-labs/authenticator/client/k8sClient.go
vendor/github.com/devtron-labs/authenticator/middleware/userLogin.go
vendor/modules.txt

authenticator updates for devtron secret

Fix: authenticator updates for devtron secret

---

.github/workflows/azure-devops-issue-sync.yml

Added right values for other states as well
Added right values for ADO states
Fixes
Not tested. Will test after merging.

Fix for Closed state

---

pkg/pipeline/CiService.go
pkg/pipeline/WorkflowDagExecutor.go

Azure Blob Storage logs are not getting synced.

Azure Blob Storage Logs Sync Fix

---

docs/setup/install/README.md

brustrable instance warning doc

docs: brustrable instance warning doc

---

charts/devtron/Chart.yaml
charts/devtron/values.yaml

Updated git-hash in values.yaml of chart

FIX: Updated git-hash in values.yaml

---

docs/user-guide/integrations/README.md

changed discover integration image

docs: changed discover integration image

---

docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
docs/setup/install/install-devtron-with-cicd.md
docs/setup/install/install-devtron.md

Updated commands for accessing devtron for all installation types.

docs: devtron password command update

---

docs/SUMMARY.md
docs/user-guide/integrations/argocd.md
docs/user-guide/integrations/build-and-deploy-ci-cd.md
docs/user-guide/integrations/clair.md
docs/user-guide/integrations/grafana.md
docs/user-guide/integrations/notifications.md

-  Updated GitOps (Argo CD) integration
- Added Notifications integration
- Added Monitoring (Grafana) integration

Integration documentation

---

pkg/pipeline/PipelineStageService.go

pre and post ci config id added in get api.

Fix: pre and post ci config id added in get api.

---

docs/user-guide/creating-application/app-details.md

- Added a new section for a Project change of the application.

docs: added project change

---

scripts/sql/82_chart_ref_4-15.up.sql

Updated SQL query to set reference-chart_4-15-0 default true.

updated sql query to set reference-chart_4-15-0 default true

---

docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
docs/setup/install/install-devtron-helm-3.md
docs/setup/install/install-devtron-with-cicd.md
docs/setup/install/install-devtron.md

removed $ from devtron password command

docs: removed $ from devtron password command

---

docs/user-guide/global-configurations/custom-charts.md

1. Correction in `image_descriptor_template.json`.
2. Added few more validations

docs: correction in custom chart doc

---

api/appStore/InstalledAppRestHandler.go
api/restHandler/AppListingRestHandler.go

Application status fixed for non-gitops apps.
Fixes # (issue): https://github.com/devtron-labs/devtron/issues/2452

Feat: Application status fixed for non-gitops apps.

---

pkg/pipeline/GitHostConfig.go

handling the webhook case when host url is not set

fix: handling the webhook case when host url is not set

---

charts/devtron/resource-values.yaml
charts/devtron/templates/config-overrides.yaml
charts/devtron/templates/dashboard.yaml
charts/devtron/templates/devtron.yaml
charts/devtron/templates/dex.yaml
charts/devtron/templates/install.yaml
charts/devtron/templates/kubelink.yaml
charts/devtron/templates/migrator.yaml
charts/devtron/templates/workflow.yaml

resource-changes

---

sample-docker-templates/kotlin/Dockerfile

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>
A sample docker-template for kotlin has been added.
Fixes #2477

Added sample-docker-template for kotlin

---

pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go

panic error fix of chart push fails for helm apps

fix: panic error fix of chart push fails for helm apps

---

charts/devtron/templates/configmap-secret.yaml
charts/devtron/templates/postgresql.yaml
charts/devtron/values.yaml
manifests/installation-script
manifests/yamls/lens.yaml

Changes for ARM support in helm chart
Fixes #1473

Changes for ARM support in helm chart

---

charts/devtron/templates/configmap-secret.yaml
charts/devtron/templates/postgresql.yaml
charts/devtron/values.yaml
manifests/installation-script
manifests/yamls/lens.yaml

Changes for ARM support in devtron-operator helm chart

Changes for ARM support in devtron-operator helm chart

---

docs/setup/install/install-devtron-with-cicd.md
docs/setup/install/install-devtron.md

multi architecture doc

---

sample-docker-templates/rust/Dockerfile

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>
A sample docker-template for rust has been added.

Added sample-docker-template for rust

---

docs/user-guide/global-configurations/cluster-and-environments.md

add cluster documentation update

docs: add cluster documentation update

---

docs/FAQs/devtron-troubleshoot.md
docs/setup/install/installation-configuration.md

Removed kubectl for devtron configuration

docs: Removed kubectl for devtron configuration

---

docs/user-guide/global-configurations/cluster-and-environments.md

tab name correction for cluster type

docs: tab name correction for cluster type

---

docs/user-guide/creating-application/secrets.md

External secret operator documentation

docs: External secret operator doc

---

docs/setup/install/installation-configuration.md

Docs for configuring resources for devtron microservices

docs: configure resources

---

client/argocdServer/k8sClient.go
client/gitSensor/GitSensorClient.go
client/grafana/GrafanaClient.go

Refactored error messages in some error logging statements. Helpful while debugging
Testing not needed

Correct error logs

---

docs/setup/install/install-devtron-with-cicd.md

Update install documentation with aws-ebs-csi-driver

Doc: Update install documentation with aws-ebs-csi-driver

---

README.md

Update Devtron Readme with tagline and added DevOps in a box in Readme.

DOC: Tagline changed & added DevOps in a Box

---

internal/util/GitServiceBitbucket.go

Fixed panic issue in bitbucket.

hotfix for bitbucket panic 

---

docs/user-guide/creating-application/deployment-template.md
docs/user-guide/creating-application/deployment-template/rollout-deployment.md
docs/user-guide/creating-application/environment-overrides.md

- Deployment Template section is modified.
- Added Basic GUI Configuration.

Docs: Added basic GUI for rollout deployment

---

pkg/pipeline/CdWorkflowService.go
pkg/pipeline/WorkflowDagExecutor.go

deployment release counter needed in env vars.
Fixes #2569

deployment release counter exposed in post stage

---

.github/ISSUE_TEMPLATE/feature.yaml

Fix: Updated username for Prakarsh

---

docs/setup/install/install-devtron-with-cicd.md

docs: Modified the devtron install cmd with gcp cloud

---

client/telemetry/TelemetryEventClientExtended.go

fix: updated wiring for TelemetryEventClientExtended.go

---

scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_3-13-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-12-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-14-0/templates/ingress.yaml
scripts/devtron-reference-helm-charts/reference-chart_4-15-0/templates/ingress.yaml

<!--
added deault pathType for ingress in 4.x reference chart ingress.yaml
!>

Fix ingress new-legacy issue

---

.github/workflows/create-release.yml

This PR updates the changes for release-notes as well as release creation based on nightly or stable release

chore: Release action update for new release process

---

pkg/user/casbin/rbac.go

App List API on dashboard is overriding old cache data. So, users which has access to very few projects are facing this issue.
Fixes #2607
```release-note
```

Enforcer RBAC Cache Override Fix

---

pkg/app/AppService.go

fix: deploymentApp creation check update

---

.github/workflows/create-release.yml

Removed changelog section from action

chore: Removed changelog section from action

---

docs/FAQs/devtron-troubleshoot.md
docs/README.md
docs/setup/install/installation-configuration.md
docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
docs/user-guide/creating-application/workflow/ci-pipeline-legacy.md
docs/user-guide/deploying-application/triggering-ci.md
docs/user-guide/global-configurations/authorization/README.md
docs/user-guide/global-configurations/external-links.md
docs/user-guide/integrations/README.md
docs/user-guide/integrations/argocd.md
docs/user-guide/integrations/build-and-deploy-ci-cd.md
docs/user-guide/integrations/clair.md
docs/user-guide/integrations/grafana.md
docs/user-guide/integrations/notifications.md
docs/user-guide/use-cases/README.md

doc: broken hyperlinks in doc fix

---

.github/workflows/create-release.yml

fixed release title for stable releases

chore: fixed release title for stable releases

---

pkg/user/UserAuthService.go

Fixes #2628
-
```release-note
```

fix: corrected health url in auth whitelist list

---

scripts/devtron-reference-helm-charts/reference-chart_4-15-0/templates/deployment.yaml

feat: Exposed Devtron docker image in container as variable

---

api/restHandler/CoreAppRestHandler.go

Updated check for build type in app create api for buildpack story backward compatibility.
Fixes #2653 
```release-note
```

fix:updated ciBuildType check in app create

---

docs/README.md

docs: updated url for the license file

---

pkg/pipeline/CiHandler.go
pkg/pipeline/CiService.go
pkg/pipeline/PipelineBuilder.go

Reverts devtron-labs/devtron#2636

Revert "fix: checking git material active status for multiple places"

---

README.md

- docs - The PR contains Documentation ONLY changes. 
- README. md file update: Credentials updated for Devtron version v0.6.0 higher and lesser than v0.6.0 versions

docs: devtron readme - credentials update

---

manifests/release.txt

chore: bump beta release to stable

---

charts/devtron/Chart.yaml
charts/devtron/values.yaml

chore: Fix release version

---

docs/FAQs/devtron-troubleshoot.md

docs: deleted extra spaces from grafana commands

---

pkg/cluster/ClusterService.go
pkg/cluster/ClusterServiceExtended.go
util/k8s/ClusterCronService.go
util/k8s/wire_k8sApp.go

Fixed bug in which cluster connection status was not being updated when the config is updated.
Fixes #2688
```release-note
```

fix: updated cluster connection status for update api

---

internal/sql/repository/appWorkflow/AppWorkflowRepository.go
pkg/appWorkflow/AppWorkflowService.go
pkg/bulkAction/BulkUpdateService.go

Fixed bug where workflow was being deleted when user updates it. Also, for bulk cd pipeline deletion ci pipelines with no cd pipelines attached were being included too in the impacted objects when user opts for deleting workflows and ci pipeline too.
Fixes #2694
```release-note
```

fix: wf deletion bug and bulk cd pipeline req

---

pkg/pipeline/WebhookService.go
pkg/pipeline/WorkflowDagExecutor.go

Fixes #https://github.com/devtron-labs/devtron/issues/2665
```release-note
```

Fix:  External ci webhook response for api token.

---

api/appbean/AppDetail.go
api/restHandler/CoreAppRestHandler.go
pkg/chart/ChartService.go
pkg/pipeline/PropertiesConfig.go
specs/app_create_api.yaml

Updated app create api for deployment template editor view data.
Fixes #2700
```release-note
```

fix: deployment template editor view support in create app api

---

docs/user-guide/creating-application/workflow/ci-pipeline.md

docs - The PR contains Documentation ONLY changes.

docs: webhook updates links

---

docs/user-guide/creating-application/workflow/ci-pipeline.md
docs/user-guide/global-configurations/external-links.md

- Minor Updates: External Link (input from Dev)
- Minor Updates: External CI (input from marketing)

docs: minor updates

---

pkg/pipeline/PipelineBuilder.go

updated check for setting deployment app types in cd pipeline creation request.
Fixes #2724
```release-note
```

fix: refactored deployment app type handling for empty data in payload

---

client/gitSensor/GitSensorClient.go
client/lens/LensClient.go
pkg/pipeline/CiCdPipelineOrchestrator.go

Getting error message on deleting linked CI pipeline
Fixes https://github.com/devtron-labs/devtron/issues/2731
```release-note
```

Fix: getting error message on deleting linked ci pipeline

---

api/bean/GitOpsConfig.go
internal/sql/repository/GitOpsConfigRepository.go
internal/util/ChartService.go
internal/util/GitService.go
internal/util/GitServiceGitlab.go
pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
pkg/appStore/deployment/service/InstalledAppService.go
pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
pkg/chart/ChartService.go
pkg/gitops/GitOpsConfigService.go
pkg/pipeline/PipelineBuilder.go
scripts/sql/99_alter_gitop_config.down.sql
scripts/sql/99_alter_gitops_config.up.sql

feat: added BE support for allowing insecure tls connection in gitOps

---

docs/setup/getting-started/getting-started.md
docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
docs/setup/install/install-devtron-with-cicd-with-gitops.md
docs/setup/install/install-devtron-with-cicd.md
docs/setup/install/install-devtron.md

- The PR contains Documentation ONLY changes. 
- Fixed broken links.

docs: fixed broken links

---

docs/user-guide/creating-application/deployment-template.md
docs/user-guide/creating-application/deployment-template/deployment.md
docs/user-guide/creating-application/deployment-template/job-and-cronjob.md
docs/user-guide/creating-application/deployment-template/rollout-deployment.md

The PR contains Documentation ONLY changes for description for charts.

docs: description for charts

---

docs/SUMMARY.md

The PR contains Documentation ONLY changes. 
- Minor updates

docs: deployment updates

---

charts/devtron/Chart.yaml

Update Chart.yaml for security update

fix: Update Chart.yaml for security integration chart fix

---

docs/SUMMARY.md
docs/user-guide/creating-application/deployment-template.md
docs/user-guide/creating-application/deployment-template/deployment.md

- This PR contains the doc fixes for doc v0.5.
- Deployment template is included for v0.5 also.

docs: deployment-docs-v0.5

---

docs/FAQs/devtron-troubleshoot.md
docs/SUMMARY.md
docs/user-guide/deploying-application/triggering-ci.md
docs/user-guide/global-configurations/docker-registries.md
docs/user-guide/global-configurations/external-links.md

Fixed Broken Links in the sections below: This PR must be merged in docv0.5, not main.
- Container Registries (v0.5)
- External Link (v0.5)
- Troubleshooting (v0.5)
- Triggering CI (v0.5)

docs: broken links doc v0.5

---

docs/SUMMARY.md

Minor Updates: Uninstall Devtron section.

docs: uninstall minor updates

---

util/k8s/k8sCapacityService.go

This change includes clusterName passed in node metadata list.
Fixes #2803 
```release-note
```

fix: cluster name passed in node metadata list

---

docs/setup/install/ingress-setup.md

docs: minor correction in ingress yaml

---

client/k8s/application/Bean.go
internal/util/K8sUtil.go
util/k8s/k8sApplicationService.go

Reverts devtron-labs/devtron#2836

Revert "Resource browser rbac"

---

internal/util/K8sUtil.go

safe check added if cell value is not found in resource list
```release-note
```

fix: safe check added if cell value is not found in resource list

---

docs/user-guide/clusters.md
docs/user-guide/global-configurations/authorization/permission-groups.md
docs/user-guide/global-configurations/authorization/user-access.md
docs/user-guide/resource-browser.md

- Minor updates on resource browser and cluster sections
- Broken links fixed.

docs: updated broken links and minor updates (resource browser)

---

scripts/sql/106_sonarqube_plugin_polling.up.sql

fix: updated sonarqube plugin script

---

pkg/user/casbin/rbac.go

verify token and get email function use is required outside scope of this. made this function public
Fixes #
```release-note
```

feat: verify token function scope made public

---

api/restHandler/CoreAppRestHandler.go

sending appName in the response of getAppWorkflow API
Fixes #2878 
```release-note
```

fix: sending appName in the response of getAppWorkflow API

---

pkg/pipeline/ConfigMapService.go
pkg/pipeline/history/bean.go

Fixes #2903 
```release-note
```

task: added new fields for eso secrets

---

api/router/pubsub/ApplicationStatusUpdateHandler.go
client/cron/CdApplicationStatusUpdateHandler.go
pkg/app/AppService.go
pkg/pipeline/CdHandler.go

Updated log types for better debuggability. 
```release-note
```

fix: updated log type for pipeline status methods

---

pkg/pipeline/CdHandler.go
pkg/pipeline/WorkflowDagExecutor.go

Fixed the bug of finishedOn time in deployment of an image. Earlier the start time was same as the end time. 
Fixes # [issue](https://github.com/devtron-labs/devtron/issues/2927)
Tested on localhost as well as in a VM by inspecting the API calls.
```release-note
```

fix: finished on time update fix

---

docs/user-guide/creating-application/overview.md

- Added info to mount PVC for app level and pipiline to optimize build time.

docs: mount pvc

---

pkg/app/AppListingViewBuilder.go

Sorting app environment containers in app listing api based on last deployed time
Fixes #2934 
```release-note
```

fix: sorting app environment containers in app listing api 

---

docs/SUMMARY.md
docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md

- Added Preset plugins (Codacy & Semgrep)
- Modified and added existing preset-plugins

docs: Added preset plugins

---

client/argocdServer/k8sClient.go
pkg/app/AppService.go
pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
scripts/argo-assets/APPLICATION_TEMPLATE.JSON

Fixes #2378
```release-note
```

feat - Use cluster-name instead of server url in Argo cd application objects

---

api/restHandler/app/DeploymentPipelineRestHandler.go
api/router/PipelineConfigRouter.go
internal/sql/repository/pipelineConfig/PipelineRepository.go
pkg/bean/app.go
pkg/pipeline/PipelineBuilder.go

With this PR, an API is being added to change the deployment app for all the pipelines in an environment.
Note: In this PR changing deployment app only from argocd to helm is supported.

feat: add api to change deployment app type for all cd pipelines in an environment
