- api/restHandler/app/DeploymentPipelineRestHandler.go
- api/router/PipelineConfigRouter.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- internal/sql/repository/pipelineConfig/mocks/PipelineRepository.go
- pkg/bean/app.go
- pkg/pipeline/PipelineBuilder.go
- specs/deployment_app_type_change_api.yaml
> feat: deployment app type change api

- internal/sql/repository/pipelineConfig/PipelineRepository.go
> fixed pg query issue

- api/appStore/InstalledAppRestHandler.go
- api/appbean/AppDetail.go
- api/restHandler/AppListingRestHandler.go
- api/restHandler/ChartGroupRestHandler.go
- api/restHandler/CoreAppRestHandler.go
- api/restHandler/app/DeploymentPipelineRestHandler.go
- api/router/PipelineConfigRouter.go
- client/cron/CdApplicationStatusUpdateHandler.go
- docs/setup/configurations/configurations-overview.md
- docs/setup/install/ingress-setup.md
- internal/sql/repository/app/AppRepository.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- internal/sql/repository/pipelineConfig/mocks/PipelineRepository.go
- pkg/app/AppService.go
- pkg/appStore/deployment/repository/ChartGroup.go
- pkg/appStore/deployment/service/ChartGroupService.go
- pkg/bean/app.go
- pkg/bulkAction/BulkUpdateService.go
- pkg/pipeline/PipelineBuilder.go
- specs/app_create_api.yaml
- specs/deployment_app_type_change_api.yaml
- util/NumberParserUtil.go
- wire_gen.go
> Feat deployment app type change api

- util/version.go
Removed server mode hardcoding.
Fixes #
```release-note
```
> removed server mode hardcoding

- docs/SUMMARY.md
- docs/user-guide/global-configurations/chart-repo.md
- docs/user-guide/global-configurations/manage-notification.md
- docs/user-guide/global-configurations/sso-login.md
- SSO Login Services - Doc improvements
> docs: sso login doc

- internal/sql/repository/pipelineConfig/PipelineRepository.go
For Helm apps the bulk pipeline delete request was failing
Fixes #
Modified the pg query to include app and environment details
> bug: resolve failing bulk pipeline delete api

- scripts/sql/118_alter_installed_apps.down.sql
- scripts/sql/118_alter_installed_apps.up.sql
fixing migration script for deployment app partial delete.
Fixes #3048 
```release-note
```
> fix: fixing migration script for acd app partial delete

- pkg/app/AppService.go
> fix: helm app deployment failed

- docs/SUMMARY.md
- docs/user-guide/creating-application/eso/aws-eso.md
- docs/user-guide/creating-application/eso/gcp-eso.md
> docs: doc for GCP external secret

- api/cluster/EnvironmentRestHandler.go
Fixes https://github.com/devtron-labs/devtron/issues/3098
```release-note
```
> fix: getting all environmets for super admin only

- api/restHandler/AppListingRestHandler.go
- api/restHandler/app/AutoCompleteRestHandler.go
- api/restHandler/app/BuildPipelineRestHandler.go
- api/restHandler/app/DeploymentPipelineRestHandler.go
- api/restHandler/app/PipelineConfigRestHandler.go
- api/router/JobsRouter.go
- internal/sql/repository/AppListingRepository.go
- internal/sql/repository/app/AppRepository.go
- internal/sql/repository/appStatus/AppStatusRepository.go
- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
- internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
- internal/sql/repository/security/CveStoreRepository.go
- pkg/app/AppCrudOperationService.go
- pkg/app/AppListingService.go
- pkg/appClone/AppCloneService.go
- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/bean/app.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/CiHandler.go
- pkg/pipeline/PipelineBuilder.go
- pkg/security/ImageScanService.go
- pkg/security/policyService.go
- scripts/sql/115_jobs.down.sql
- scripts/sql/115_jobs.up.sql
- specs/jobs.yaml
> Job feature branch app type test

- api/appStore/deployment/CommonDeploymentRestHandler.go
- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
> fix: added otel for deployment history info api

- internal/sql/repository/GlobalCMCSRepository.go
- pkg/pipeline/GlobalCMCSService.go
json Unmarshall panic error fix
Fixes https://github.com/devtron-labs/devtron/issues/3111
```release-note
```
> fix: json unmarshal panic error temperory fix.

- pkg/sql/connection.go
PG prom metrics not getting exported when PG query logging is disabled. Move out the PG prom metrics export of the PG log query block
```release-note
```
> fix: pg prom metrics not getting exported when pg query logging is disabled

- pkg/pipeline/CdWorkflowService.go
Global secrets will not be injected if _run in application environment_ is set as True.
Fixes #3093 
1) Checked that if run in application environment is selected then global secrets are not injected in pre/post CD.
```release-note
```
> feat: Disabling global secrets for application environment.

- pkg/pipeline/PipelineBuilder.go
This PR fixes bad gateway error when _"select image"_ is clicked in CD pipeline.
Fixes #3135 
```release-note
```
> fix: ci artifacts not coming for linked CI pipeline

- .github/workflows/enterprise-repo-sync.yaml
Added enterprise-repo-sync action yaml
> chore:  enterprise-repo-sync.yaml

- pkg/pipeline/CdWorkflowService.go
This PR makes Kubernetes external secret accessible as environment variable.
Fixes #3142 
```release-note
```
> fix: kubernetes external secret not accessible

- api/restHandler/app/DeploymentPipelineRestHandler.go
- pkg/bean/app.go
Enable option to opt for auto deployment trigger after bulk deployment app change is done.
Fixes #3114 
NO
```release-note
```
> feat: enable auto deployment trigger option after deployment app change

- .github/workflows/azure-devops-issue-sync.yml
Description:
Github action changes to sync github issues with ADO.
> chore: ADO-sync github action changes

- .github/workflows/azure-devops-issue-sync.yml
Description
Github actions for syncing the github issues in ADO
> chore: ado-sync workflow changes 

- .github/workflows/azure-devops-issue-sync.yml
> chore: ado-sync workflow

- api/connector/Connector.go
This PR fixes log api panic due to index out of bound error.
Fixes #3158 
```release-note
```
> fix: log api panic

- .github/workflows/azure-devops-issue-sync.yml
Description:
version upgrade of the ado-sync workflow
> chore: version upgrade of github action (ado-sync)

- .github/ISSUE_TEMPLATE/feature.yaml
- .github/workflows/azure-devops-issue-sync.yml
> chore: ADO sync action changes

- api/restHandler/GitOpsConfigRestHandler.go
We should update the token from database if token is empty during update request and during validation.
Fixes #https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2518
[x] Tested the code by deploying on cluster
> fix: Gitops validate and update with empty token

- util/k8s/k8sCapacityService.go
> fix: eks nodegroup label added

- scripts/sql/123_alter_installed_apps.down.sql
- scripts/sql/123_alter_installed_apps.up.sql
Migration file added for storing notes.txt in db 
Fixes [AB2484](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2484)
It has been tested locally
> feat:migration files for notes.txt

- .github/workflows/azure-devops-issue-sync.yml
> chore: Discord notification for a specific label ("pager-duty")

- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/history/CiPipelineHistoryService.go
- pkg/pipeline/history/GitMaterialHistoryService.go
Updated condition which was resulting into panic due to invalid object in one condition.
Fixes #3242 
```release-note
```
> fix: updated condition for handling linked ci creation with parent ci docker config overriden

- pkg/pipeline/PipelineBuilder.go
Fixes #3297 
```release-note
```
> fix: jobs trigger not working

- .github/workflows/azure-devops-issue-sync.yml
merge after merging --  https://github.com/devtron-labs/action-discord/pull/1
Also create new ENV Variable for Webhook.
```
GH_ISSUE_DISCORD_WEBHOOK. --- for normal channel
PAGERDUTY_DISCORD_WEBHOOK --- for forum channel
```
> chore: added workflow for notification on discord forum

- .github/workflows/azure-devops-issue-sync.yml
https://github.com/devtron-labs/devtron/pull/3300
```
DISCORD_WEBHOOK: ${{ secrets.GH_ISSUES_DISCORD_WEBHOOK }}
DISCORD_WEBHOOK_FORUM: ${{ secrets.PAGERDUTY_DISCORD_WEBHOOK }}
```
> chore: added workflow for notification on discord forum ENV_NAME changes

- scripts/devtron-reference-helm-charts/deployment-chart_1-2-0/templates/metrics-service-monitor.yaml
> fix: replace rollouts-pod-template-hash with pod-template-hash in reference  chart 4.18.0

- scripts/sql/129_git_sensor_node_sharding.up.sql
A sql script related to git-sensor sharding was deleted earlier. Restoring that 
NO
```release-note
```
> fix: restore deleted sql script

- pkg/app/AppService.go
> fix: helm install error, nil pointer fix

- docs/setup/install/install-devtron-helm-3.md
- docs/setup/upgrade/devtron-upgrade-to-beta.md
> docs: beta docs added

- docs/user-guide/global-configurations/cluster-and-environments.md
> docs: updated command for generating credentials to add cluster

- pkg/pipeline/CiService.go
> fix: job trigger fail

- pkg/pipeline/CiService.go
Fixes #3387 
```release-note
```
> fix: ci pipeline trigger bad gateway

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
> chore: Updated Github ISSUE-TEMPLATE

- api/user/RbacRoleRestHandler.go
Updated status code for role fetch api to avoid FE redirection for 401 status code.
```release-note
```
> task: updated status code for role fetch api

- api/appStore/discover/AppStoreRestHandler.go
> fix:  Search option should not be case sensitive in case of clusters, preset values, chart store

- pkg/appClone/AppCloneService.go
- pkg/pipeline/CiConfig.go
- pkg/pipeline/CiService.go
- pkg/pipeline/WorkflowService.go
> fix: Build context disable

- docs/FAQs/devtron-troubleshoot.md
> docs: how to refresh the argocd certificate

- docs/user-guide/use-cases/prometheus-stack-over-devtron.md
> docs: prometheus docs added

- scripts/sql/146_helm_package.up.sql
fixes sql migration up script for virtual cluster
Fixes #
```release-note
```
> fix: sql script fix

- docs/user-guide/creating-application/workflow/cd-pipeline.md
> docs: updated doc for incluster

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/appStore/deployment/service/InstalledAppService.go
chart group - bulk chart deploy api not working 
Fixes #3476 
#3477 
```release-note
```
> fix: bulk-chart-deploy-fix

- pkg/app/AppService.go
Fixes #3489
```release-note
```
> fix: image pull secret

- docs/user-guide/global-configurations/authorization/user-access.md
> docs: helm-charts permissions correction

- pkg/chartRepo/ChartRepositoryService.go
- pkg/team/TeamService.go
> Fix : field validation and projects and chart repo fields

- util/k8s/k8sApplicationRestHandler.go
Modified ValidateResource Condition for Deleting Resources for Helm Apps
Fixes #3551 
```release-note
```
> fix: ACD helm app release not found when deleting resource

- docs/user-guide/creating-application/deployment-template/deployment.md
> docs: yaml for deployment chart

- docs/SUMMARY.md
- docs/user-guide/creating-application/deployment-template/statefulset.md
> docs: StatefulSets chart doc

- api/restHandler/CoreAppRestHandler.go
Fixes: https://github.com/devtron-labs/devtron/issues/3560
```release-note
```
> fix: bulk wokflow create bug fix ent 

- pkg/appClone/AppCloneService.go
Previously whenever we were cloning an app which is containing the exclude/include filter ,the cloned app was not containing the exclude/include filter.
Fixes #
1. After adding the Filter pattern filed to the cloned app request ,I have deployed the code on my cluster and tested it.
2.I have cloned an app from an app which was containing the exclude/include filter, and I was able to find the filter in the cloned app as well.
```release-note
```
> Fix: Exclude/Include feature not available in cloned apps

- pkg/sql/connection.go
- pkg/sso/SSOLoginService.go
After saving any SSO configuration it's getting saved correctly, but after refreshing the page it shows some fixed values for all the SSO login services.
Fixes #3581 
```release-note
```
> fix: SSO configuration gets change after refreshing the page

- pkg/notifier/WebhookNotificationService.go
To introduce one new variable DevtronContainerImageRepo for getting repo
Fixes [#AB3590](https://github.com/devtron-labs/devtron/issues/3590)
Tested done by deploying image on vm
```release-note
```
> feat: devtronContainerImageRepo variable added

- pkg/pipeline/DockerRegistryConfig.go
This PR fixes the CI build config error for container registry for devtron applications.
```release-note
```
> fix: updated ValidateRegistryStorageType for OCI registry configs

- pkg/pipeline/CiConfig.go
- pkg/pipeline/CiService.go
- pkg/pipeline/bean/CiBuildConfig.go
Need an option/flag to pass the build platform globally.
Fixes #3531 
```release-note
```
> feat: Flag to pass build platform globally

- api/restHandler/CoreAppRestHandler.go
- pkg/appWorkflow/AppWorkflowService.go
Fixes https://github.com/devtron-labs/devtron/issues/3646
```release-note
```
> feat: enhancement app workflow clone, added specific deployment clone in workflow

- internal/util/K8sUtil.go
In resource browser there is no column appearing for the Nodes. So, create an output in resource browser where we are able to see every pod running on which node.
Fixes https://github.com/devtron-labs/devtron/issues/3650
```release-note
```
> feat: flag for node

- pkg/pipeline/WorkflowService.go
> fix: blob storage upload failed due to USE_BLOB_STORAGE_CONFIG_IN_CI_WORKFLOW flag

- pkg/pipeline/CiCdPipelineOrchestrator.go
When the scripts are migrated to steps form from yaml format, and when there are 2 cds, both set to auto, the 2nd cd is not getting triggered when set to auto and this pr aims to fix that issue. 
Fixes #3678 
```release-note
```
> fix: auto deploy fix for migrated pre/post cd steps where inly one is configured

- docs/SUMMARY.md
> docs: added devtron release note in summary.md

- pkg/appStore/deployment/repository/InstalledAppVersionHistory.go
- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
Fixes #3660 
```release-note
```
> fix: manifest output is not in sync with selected chart version and wrong manifest coming in deployment history

- api/restHandler/AppListingRestHandler.go
- pkg/appStore/deployment/service/InstalledAppService.go
> fix: resource tree error handling miss

- docs/SUMMARY.md
- docs/setup/install/devtron-backup.md
> docs: disaster recovery docs

- pkg/k8s/application/k8sApplicationService.go
Fixes - We were unable to fetch resource List for particular namespace for K8s resources.
```release-note
```
> fix : Resource list fetch for K8s

- .github/workflows/pr-issue-validator.yaml
> feat: workflow to validate PRs if an issue is linked or not

- .github/workflows/pr-issue-validator.yaml
> chore: Removed path-ignore section in pr-issue-validator

- .github/workflows/pr-issue-validator.yaml
> chore: Update pr-issue-validator.yaml

- api/restHandler/AppListingRestHandler.go
- pkg/appStore/deployment/service/InstalledAppService.go
- pkg/k8s/K8sCommonService.go
Fixes #3776 
```release-note
```
> fix: resource tree panic fix

- docs/user-guide/creating-application/deployment-template/deployment.md
> docs: container lifecycle 

- pkg/chartRepo/ChartRepositoryService.go
Adding logs in chart repo save flow for debugging purpose. In some clusters there is issue in saving chart repo. These logs will help in debugging that issue.
```release-note
```
> chore: adding logs in chart repo code

- pkg/pipeline/WorkflowService.go
External cm and secret in jobs not getting added as env variable in container
Fixes #3814 
```release-note
```
> fix: External cm and secret in jobs not getting added as env variable in container

- pkg/pipeline/PipelineStageService.go
- pkg/pipeline/WorkflowDagExecutor.go
Fixes #3826 
```release-note
```
> fix: deleting pipeline stage and related data if no stage steps are found

- .github/workflows/azure-devops-issue-sync.yml
This GH action will find the potential duplicate GH issues and marked then duplicate by adding a lable of potential-duplicate and commenting duplicate issues with there ID.
> chore: find potential-duplicate issues 

- scripts/sql/168_virtual_cluster_v3.up.sql
Updated migration script for virtual cluster v3
Fixes #3867 
Verified by QA
```release-note
```
> fix: migration script for virtual cluster v3

- docs/SUMMARY.md
- docs/reference/graviton.md
Docs: Add 'Devtron on Graviton' doc in Resources section of doc portal
> doc: draft version of Graviton benchmark

- pkg/pipeline/WorkflowDagExecutor.go
Mark CD/ CD Stages trigger status failed for vulnerable image deployment. 
Fixes #
For Devtron App and App Group
```release-note
```
> fix: block trigger for vulnerable image

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
Updated error message for invalid installed app version for helm chart upgrade API
Fixes #
```release-note
```
> fixed: updated invalid installed version error message

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/appStore/deployment/service/InstalledAppService.go
- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
Updated error message for helm apps API
Fixes #
```release-note
```
> feat: updated error message for installed app

- pkg/security/ImageScanService.go
> vulnerability permission fix

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/cluster/EnvironmentUtil.go
> fix: Deployment is breaking due to invalid environment name

- pkg/pipeline/CiConfig.go
- pkg/pipeline/CiService.go
- pkg/pipeline/bean/CiBuildConfig.go
Fixes #3918 
```release-note
```
> feat: added configurable provenance flag for buildx builds

- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/values.yaml
> Feat: Updated the bom.yaml for migration 

- .github/workflows/pager-duty-issue-escalate.yaml
> chore: added workflow to escalate pager-duty issue

- .github/workflows/pager-duty-issue-escalate.yaml
> chore: changed loop from for to while

- .github/workflows/pager-duty-issue-escalate.yaml
> chore: scheduled escalate pager duty issue workflow

- pkg/appClone/AppCloneService.go
Fixes #1548 
```release-note
```
> fix: Clone App Scanning enabled flag 

- api/restHandler/CoreAppRestHandler.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
> fix: revert app and workflow creation in case of error

- api/restHandler/ChartGroupRestHandler.go
> fix: Unable to edit chart-group with edit access

- pkg/pipeline/WorkflowDagExecutor.go
Updated previous deployment status incase of deployment failed due to vulnerable image.
Fixes #
```release-note
```
> fix: updated previous deployment status

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
updated delete installed app error message if the app is already deleted
```release-note
```
> feat: updated delete installed app error message

- pkg/pipeline/WorkflowDagExecutor.go
Fixed auto trigger issue:  
workflow is not getting created incase of Pre CD and Post CD. This PR fixes the issue.
```release-note
```
> fix: workflow not created for auto trigger

- api/appStore/deployment/AppStoreDeploymentRestHandler.go
Updated helm app delete error message
```release-note
```
> fix: helm app delete error

- internal/util/BasicProviders.go
added log config for dev mode
Fixes # 
```release-note
```
> chore: added log config for dev mode

- scripts/devtron-reference-helm-charts/deployment-chart_4-18-0/app-values.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-18-0/values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_5-0-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_5-0-0/values.yaml
> chore: minor correction in devtron reference charts

- internal/sql/repository/security/ImageScanDeployInfoRepository.go
Fixes #3546 
```release-note
```
> fix: Security Pagination Count wrong fix

- docs/SUMMARY.md
- docs/user-guide/app-details/ephemeral-containers.md
Doc: Launching ephemeral containers
> docs: Ephemeral Container Doc

- api/k8s/capacity/k8sCapacityRestHandler.go
- pkg/cluster/ClusterCronService.go
- pkg/cluster/ClusterService.go
- pkg/cluster/ClusterServiceExtended.go
- pkg/cluster/repository/ClusterRepository.go
- pkg/k8s/capacity/bean/bean.go
- pkg/k8s/capacity/k8sCapacityService.go
removed virtual environments from unnecessary places
```release-note
```
> feat: removed virtual environments from unnecessary places

- docs/user-guide/creating-application/overview.md
- docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
docs - The PR contains Documentation ONLY changes.
> docs: Snapshot updation in PVC docs + PreBuild CI-CD

- .github/workflows/pr-issue-validator.yaml
pr-issue-validator permissions fix
> chore: pr-issue-validator permissions fix

- scripts/sql/174_container_image_update.down.sql
- scripts/sql/174_container_image_update.up.sql
Handling for Iam roles
Fixes #3975 
```release-note
```
> fix: Iam role handling script for plugin pull image from CR

- api/router/pubsub/ApplicationStatusHandler.go
- pkg/app/AppService.go
- pkg/app/integrationTest/AppService_test.go
- pkg/pipeline/CdHandler.go
- pkg/pipeline/WorkflowDagExecutor.go
Post cd not working in case of multiple parallel gitOps pipeline. 
Fixes #4019
```release-note
```
> fix: auto post cd not working in case of multiple parallel gitOps pipeline

- pkg/pipeline/PipelineBuilder.go
Refactoring is done around pipelineBuilder, Methods are clubbed according to target objects like Application, CI, CD, Artifacts etc.
self review has been performed 
```release-note
```
> chore: refactoring around PipelineBuilder

- api/restHandler/app/DeploymentPipelineRestHandler.go
- pkg/pipeline/PropertiesConfig.go
save history for env reset
Fixes #3002 
```release-note
```
> fix: save history for env reset

- pkg/app/AppService.go
Fixes #4086 
```release-note
```
> fix: env for specific deployment

- pkg/pipeline/BuildPipelineConfigService.go
Fixes #4094
```release-note
```
> fix: update build configuration fix

- pkg/cluster/EnvironmentService.go
- pkg/cluster/repository/EnvironmentRepository.go
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/6101
- tested with multiple combinations of env name and namespace name. before and after updating the cluster name
```release-note
```
> fix: able to add same ns after updating cluster name fix

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
fixed chart group delete when no rows are found
Fixes #4130 
```release-note
```
> fix: helm chart delete when no rows are found

- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/values.yaml
- manifests/installation-script
features:
- Removed Lens and Gitsensor from installation-script, and moved it to charts/devtron
- also updated position of lens in values.yaml
- removed rollout, dashboard script from installation-script.
improved installation process by removing lens and git-sensor.
test-cases
```release-note
```
> chore: Removed lens and git-sensor from inception

- .github/workflows/pr-issue-validator.yaml
> chore: skip validation for release PRs

- scripts/sql/181_remove_index_image_scan_deploy_info.down.sql
- scripts/sql/181_remove_index_image_scan_deploy_info.up.sql
- scripts/sql/181_remove_index_image_scan_deploy_info_up.sql
Fixes #4145
```release-note
```
> chore: fix sql 181 script 

- pkg/app/AppService.go
Fixes #4095
```release-note
```
> fix: valuesOverrideResponse

- pkg/app/AppService.go
Fixes #4151
```release-note
```
> fix: error handling in image scan

- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
These changes add "NOT DEPLOYED" filter in app list.
Fixes #3559 
```release-note
```
> feat: added not deployed filter in app list 

- api/restHandler/app/BuildPipelineRestHandler.go
- pkg/pipeline/BuildPipelineConfigService.go
These changes add a check for existing pipeline name, which prevents building ci-pipeline with duplicate name.
Fixes [#](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/6098/)
```release-note
```
> fix: [prod]able to build ci-pipeline with the name of already existing pipeline 

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
- manifests/yamls/devtron.yaml
Fix release for not able to edit cluster
> release: Release v0.6.24 fix for not able to edit cluster

- api/restHandler/app/BuildPipelineRestHandler.go
- internal/sql/repository/pipelineConfig/CiPipelineRepository.go
- pkg/pipeline/BuildPipelineConfigService.go
> fix: Not able to Delete CI stage for both the Linked pipeline and Source pipeline.

- internal/sql/repository/pipelineConfig/CiPipelineRepository.go
- pkg/pipeline/BuildPipelineConfigService.go
> fix: not able to delete ci for any app

- internal/sql/repository/security/ImageScanDeployInfoRepository.go
Fixes #4196 
```release-note
```
> fix: ImageScanDeployInfo not initialized while fetching from db

- pkg/dockerRegistry/DockerRegistryIpsConfigService.go
Fixes #4213
```release-note
```
> fix: setting cipipelineId to parent ci-pipelines id for linked ci's

- pkg/pipeline/CiCdPipelineOrchestrator.go
Fixes #4213 
```release-note
```
> fix: update docker config overridden flag in linked ci's

- docs/user-guide/creating-application/deployment-template/deployment.md
- docs/user-guide/creating-application/deployment-template/rollout-deployment.md
- docs/user-guide/creating-application/deployment-template/statefulset.md
> docs: Updated chart parameters in doc for deployment and rollout deployment chart

- pkg/pipeline/CiHandler.go
Fixes #4324 
```release-note
```
> fix: Message not updating for Ci

- pkg/bulkAction/BulkUpdateService.go
fixes the case where bulk unhibernation is getting inititated for already unhibernated apps
Fixes #
```release-note
```
> fix: unhibernation is getting initiated for already unhibernated apps

- api/restHandler/ConfigMapRestHandler.go
Fixes #4351 
* [] I've updated documentation as required by this PR.
* []  I have added all the required unit/api test cases.
```release-note
```
> fix: cm-env override

- api/helm-app/HelmAppService.go
- pkg/appStore/deployment/service/InstalledAppService.go
Fixes #4360 
```release-note
```
> fix: added missing clusterConfig in releaseIdentifier request

- charts/devtron/Chart.yaml
- charts/devtron/templates/devtron.yaml
Disabled artifact api listing v2
> release: Disabled artifact api listing v2

- .github/ISSUE_TEMPLATE/feature.yaml
- .github/ISSUE_TEMPLATE/pager-duty.yaml
> chore: Update pager-duty Issue template

- docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
Added Multi Arch  
Why - To run the same application on different CPU architectures (ARM, x86, etc) without creating separate images for each architecture
How - Appended a flag in the code snippet
Fixes #
```release-note
```
> doc: Update Install-devtron-on-Minikube-Microk8s-K3s-Kind.md

- scripts/sql/207_ci_external.down.sql
- scripts/sql/207_ci_external.up.sql
linked ci failing for null pipeline_type
Fixes #4442
test are performed locally .
```release-note
```
> fix: linked ci failing for null pipeline_type

- pkg/pipeline/CiHandler.go
Fixes #4419 
```release-note
```
> fix: empty pod name

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
- .github/ISSUE_TEMPLATE/pager-duty.yaml
> chore: Update Issues template and codeowners

- docs/SUMMARY.md
- docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
- Added a video tutorial covering e2e process of Devtron installation on Minikube
- Restructured the doc
- Other fixes
This will help us close: [2554](https://github.com/devtron-labs/devtron/issues/2554) and [2566](https://github.com/devtron-labs/devtron/pull/2566)
> doc: Added Minikube Tutorial + Restructured Doc

- api/restHandler/AppListingRestHandler.go
Fixed error handling for resource tree call. 
Fixes #4549
```release-note
```
> fix: resource tree err handling

- pkg/auth/authorisation/casbin/Adapter.go
- pkg/sql/connection.go
Fixes #4528
```release-note
```
> feat: introduced CASBIN_DATABASE env to make casbin db configurable

- scripts/sql/220_exposing_sonarqube_image.down.sql
- scripts/sql/220_exposing_sonarqube_image.up.sql
Expose the Docker image utilized in the SonarQube script to allow users without accessibility to Docker Hub to specify their custom image.
> chore:  Enhanced SonarQube Script by exposing Docker Image

- client/argocdServer/application/Application.go
Fixes #4614 
```release-note
```
> fix: resource tree bad gateway handle

- api/restHandler/AppListingRestHandler.go
- api/router/AppListingRouter.go
- internal/sql/repository/AppListingRepository.go
- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
- pkg/app/AppListingService.go
Fixes https://github.com/devtron-labs/devtron/issues/4629
```release-note
```
> chore: clean appListing api

- pkg/gitops/GitOpsConfigService.go
- pkg/util/TokenCache.go
- util/argo/ArgoUserService.go
Fixes #4529 
```release-note
```
> feat: added support for multiple gitops configurations on shared clusters

- pkg/deployment/gitOps/git/GitServiceGithub.go
Fixes #4656 
```release-note
```
> feat: added proxy in github transport

- internal/sql/repository/DeploymentTemplateRepository.go
- pkg/pipeline/WorkflowDagExecutor.go
Fixes #4655
```release-note
```
> fix: chartRef fetch in historical deployment triggers

- .gitbook.yaml
Redirections added for:
> /global-configurations/sso-login
> /user-guide/creating-application/workflow/ci-pipeline2
> doc: Added redirection with file type

- docs/FAQs/devtron-troubleshoot.md
added troubleshooting guide for exit status 128
> doc: added troubleshooting guide for exit status 128

- docs/SUMMARY.md
- docs/user-guide/global-configurations/build-infra.md
- Build Infra Doc added with snapshots
- Covered single and bulk actions
- Added link to GitHub issue for more infra config support
- CPU and Memory unit ref included in Extras
> doc: Added Build Infra Doc

- .github/semantic.yml
- .github/workflows/pr-issue-validator.yaml
> doc: Updated PR Validator

- pkg/pipeline/types/Workflow.go
Data Volume mount is not working in case of Jobs.
Fixes https://github.com/devtron-labs/devtron/issues/4690
```release-note
```
> fix: job workflow req volume mount

- docs/setup/install/install-devtron-with-cicd-with-gitops.md
- docs/setup/install/install-devtron-with-cicd.md
- docs/setup/install/installation-configuration.md
- docs/user-guide/creating-application/deployment-template/deployment.md
- docs/user-guide/creating-application/deployment-template/statefulset.md
- docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
- docs/user-guide/creating-application/workflow/ci-pipeline.md
- docs/user-guide/deploying-application/triggering-cd.md
- docs/user-guide/global-configurations/custom-charts.md
- docs/user-guide/plugins/README.md
- docs/user-guide/plugins/copy-container-image.md
- Fixed incorrect links
- Incorporated a correction pointed by DevOps team in one [JSON](https://docs.devtron.ai/global-configurations/custom-charts#id-2.-create-the-image-descriptor-template-file-.image_descriptor_template.json)
- Corrected the typos
> doc: Link corrections and Fixes

- .github/CODEOWNERS
Update new codeowners for migration scripts
> misc: Updated new codeowners for migration scripts

- api/util/logger.go
Added request method in Audit Logger.
Now request method like GET, PUT, POST... will also be logged with other details.
Fixes https://github.com/devtron-labs/devtron/issues/4793
> feat: added request method in audit logger

- pkg/auth/user/UserCommonService.go
- pkg/auth/user/bean/bean.go
Fixes #4822 
```release-note
```
> fix:  rolefilters correction with all applications and particular application selected.

- pkg/pipeline/types/CiCdConfig.go
Fixes #4827 
```release-note
```
> fix: panic on re-trigger ci if pod deleted on BuildTriggerObject

- pkg/dockerRegistry/DockerRegistryIpsConfigService.go
When image pull secret injection is enabled in all clusters in global config, then at the time of cd trigger the code flow looks for creating a secret in that  namespace while interacting with k8s API server , then this ns not exist error (StatusError-> k8s specific err struct ) is thrown. This pr handles that case when that scenario arises we should throw whatever status error code k8s has gives us instead of 5xx.
Fixes #4798 
```release-note
```
> fix: ns not found in case ips is being injected in cluster (in global config)

- .github/ISSUE_TEMPLATE/pager-duty.yaml
> misc: Update pager-duty.yaml

- .github/workflows/github_pagerduty_score_calculation.yml
> misc: Update github_pagerduty_score_calculation.yml

- .github/CODEOWNERS
- scripts/utilities/github_pagerduty_issue_score_calculation.py
Modified the Python script for calculating the score of pagerduty issues
> misc: Refactoring Pagerduty Issue Calculator script

- go.mod
- go.sum
- vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
- vendor/github.com/devtron-labs/authenticator/oidc/oidc.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/4893
```release-note
```
> fix: use join cookie logic to extract token

- scripts/sql/237_devtron_ci_trigger_plugin.down.sql
- scripts/sql/237_devtron_ci_trigger_plugin.up.sql
Fixes #4830
Added the plugin to trigger CI pipeline of Devtron Applications
> feat: Added the Devtron CI Trigger Plugin

- pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
Not able to link external helm charts to chart store
Fixes https://github.com/devtron-labs/devtron/issues/4920
```release-note
```
> fix: link external helm app to chart store

- pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
* fix: link external helm app to chart store
* chore: added if else blocks
Not able to link external helm charts to chart store
```release-note
```
> fix: link external helm app to chart store (#4919)

- api/appStore/deployment/AppStoreDeploymentRestHandler.go
Fixes https://github.com/devtron-labs/devtron/issues/4936
```release-note
```
> fix: removed unused dependency

- api/helm-app/service/HelmAppService.go
Fixes #4964 
```release-note
```
> fix: helm secret default value

- go.mod
- go.sum
- vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/applicationset_types.go
- vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/generated.proto
- vendor/github.com/argoproj/argo-cd/v2/util/helm/client.go
Updated the versions for depenadbot security. 
Fixes #4839
> fix: dependabot version upgrade

- api/bean/AppView.go
- internal/sql/repository/AppListingRepository.go
- wire_gen.go
Added fields cdPipelinId,  deploymentAppType, triggerType, ciPipelineId and parentEnvironmentName in app details api
Fixes #4975
> feat: added fields in app details api

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
- pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Cluster name fetched in installed app details api
Fixes #4975 
> feat: fetch cluster name 

- pkg/appStore/chartGroup/ChartGroupService.go
- pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
- pkg/appStore/discover/service/AppStoreService.go
latest flag removed from app_store_application_version
Fixes #4986 
> fix: latest flag dependency removed

- scripts/casbin/8_artifact_promoter.down.sql
- scripts/casbin/8_artifact_promoter.up.sql
- scripts/sql/238_artifacts_promotion.down.sql
- scripts/sql/238_artifacts_promotion.up.sql
oss migration scripts
Fixes #4674
```release-note
```
> feat: image promotion migration

- scripts/sql/238_artifacts_promotion.down.sql
- scripts/sql/238_artifacts_promotion.up.sql
Fixes #4995
```release-note
```
> fix: image promotion sql script

- pkg/gitops/GitOpsConfigService.go
Gitops update updated
Fixes #5056
> fix: gitops update updated

- pkg/gitops/GitOpsConfigService.go
Gitops update updated
Fixes #5056
> fix: argocd config update fix

- api/bean/gitOps/GitOpsConfig.go
- api/restHandler/GitOpsConfigRestHandler.go
- api/util/errorUtils.go
Fixes #5083 
```release-note
```
> chore: gitops validation in api

- api/bean/gitOps/GitOpsConfig.go
- api/restHandler/GitOpsConfigRestHandler.go
- api/util/errorUtils.go
> gitops validation in api (#5082)

- api/helm-app/service/HelmAppService.go
- pkg/appStore/installedApp/service/AppStoreDeploymentService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
- pkg/pipeline/DeploymentPipelineConfigService.go
Fixes #4959
```release-note
```
> fix:resolved PR review comments also remove check for virtual cluster

- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/remoteConnection/bean/bean.go
- vendor/modules.txt
Fixes #5167
```release-note
```
> chore: updated vendor

- go.mod
- pkg/deployment/manifest/deploymentTemplate/chartRef/ChartRefService.go
- pkg/generateManifest/DeploymentTemplateService.go
- pkg/generateManifest/helper.go
- wire_gen.go
Fixes https://github.com/devtron-labs/devtron/issues/5297
```release-note
```
> fix: restart workloads fix in app group

- DockerfileEA
change go version in DockerfileEA
Fixes #
https://github.com/devtron-labs/devtron/issues/5326
```release-note
```
> chore: updated go version in EA dockerfile

- go.mod
- go.sum
- vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/5334
```release-note
```
> chore: update common-lib tag version

- README.md
Fixes #5336 
```release-note
```
> docs: fixed broken link in readme

- api/helm-app/service/HelmAppService.go
- internal/sql/repository/chartConfig/PipelineOverrideRepository.go
- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- internal/sql/repository/pipelineConfig/PipelineStatusSyncDetailRepository.go
- pkg/appStore/installedApp/repository/InstalledAppRepository.go
- pkg/chartRepo/repository/ChartsRepository.go
- scripts/sql/265_migration_deployed_app.down.sql
- scripts/sql/265_migration_deployed_app.up.sql
> feat: Cd pipeline migration sql and query usage update

- .gitbook.yaml
- docs/user-guide/resource-browser.md
1. Redirection added for Blob Storage doc
2. Added image links to quickly identify placeholder values for RB doc
> doc: Blob Storage Redirection + Other Fixes

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/5254
```release-note
```
> chore: common-lib upgrade for nats replicas

- api/k8s/application/k8sApplicationRestHandler.go
Fixes https://github.com/devtron-labs/devtron/issues/5417
```release-note
```
> fix: override clusterRbac with direct allow behaviour for super admin

- pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
Fixes #5429 
```release-note
```
> fix: EA mode wire fix

- api/restHandler/ImageScanRestHandler.go
Fixes #5491 
```release-note
```
> fix: handle nil check image scanning

- api/restHandler/ImageScanRestHandler.go
- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
- pkg/appWorkflow/AppWorkflowService.go
- pkg/bean/app.go
> fix: patch ci rbac fix

- pkg/pipeline/DeploymentPipelineConfigService.go
>  fix: skip deploymentConfig creation for external ci switch

- docs/FAQs/devtron-troubleshoot.md
- docs/SUMMARY.md
- docs/user-guide/global-configurations/image-promotion-policy.md
- docs/user-guide/plugins/plugin-list.md
- docs/user-guide/resource-browser.md
1. Added the FAQ shared by Rishabh through Bhushan ([Link](https://docs.google.com/document/d/1StWsB64hG6eWyxjVS2HpNC4sdDNf6Keuzo3eQfYvtO0/edit))
2. Added the missing entry in SUMMARY.md for [GoLang-migrate doc](https://github.com/devtron-labs/devtron/blob/main/docs/user-guide/plugins/golang-migrate.md) pushed by Jatin in https://github.com/devtron-labs/devtron/pull/5347
3. Fixed the codeblock in image promotion policy doc <img width="1415" alt="image" src="https://github.com/user-attachments/assets/b1014e83-4123-4677-bccf-12b7c63bb1bf">
> doc: Added FAQ no. 28 + GoLang-migrate Link + Code Block Fix

- docs/SUMMARY.md
- docs/user-guide/application-groups.md
- docs/user-guide/deploying-application/image-labels-and-comments.md
- docs/user-guide/sdh/release-hub.md
- docs/user-guide/sdh/tenants.md
Requested by Badal: https://discord.com/channels/769482988882493450/865151043839197186/1250423878216318976
> doc: Created Image Label + Comments Doc

- pkg/resourceGroup/ResourceGroupService.go
Fixes #5542
```release-note
```
> fix: panic handling for deleted app in app group and env group filters

- internal/sql/repository/security/ImageScanHistoryRepository.go
- pkg/security/ImageScanService.go
Fixes #5550 
```release-note
```
> fix: security time fix when scanning is passed

- go.mod
- go.sum
- vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/generated.proto
- vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/openapi_generated.go
- vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/types.go
- vendor/github.com/skeema/knownhosts/NOTICE
- vendor/github.com/skeema/knownhosts/README.md
- vendor/github.com/skeema/knownhosts/knownhosts.go
- vendor/modules.txt
Bumps [github.com/argoproj/argo-cd/v2](https://github.com/argoproj/argo-cd) from 2.8.17 to 2.8.19.
Fixes #
```release-note
```
> fix: ArgoCD Vulnerable to Use of Risky or Missing Cryptographic Algorithms in Redis Cache

- pkg/k8s/K8sCommonService.go
- pkg/k8s/capacity/k8sCapacityService.go
Fixes https://github.com/devtron-labs/devtron/issues/5606
```release-note
```
> feat: panic in sync pod cron and terminal not opening fix

- pkg/deployment/gitOps/git/GitFactory.go
- pkg/deployment/gitOps/git/GitOpsHelper.go
- pkg/deployment/gitOps/git/commandManager/bean.go
Fixes https://github.com/devtron-labs/devtron/issues/5611
```release-note
```
> fix: tls enabled flag not getting passed

- .github/workflows/github_pagerduty_score_calculation.yml
> misc: added action for discrod webhook

- .github/workflows/github_pagerduty_score_calculation.yml
Reverts devtron-labs/devtron#5615
> misc: Revert "misc: added action for discrod webhook"

- scripts/sql/273_system_controller.down.sql
- scripts/sql/273_system_controller.up.sql
Fixes #5638
```release-note
```
> feat: system network controller sql script

- scripts/sql/270_plugin_parent_metadata.down.sql
- scripts/sql/271_alter_plugin_metadata.down.sql
- scripts/sql/274_improved_image_scan_plugin.down.sql
- scripts/sql/274_improved_image_scan_plugin.up.sql
Fixes #5662
```release-note
```
> chore: Plugin script fix oss

- pkg/pipeline/CiService.go
Fixes https://github.com/devtron-labs/devtron/issues/5647
```release-note
```
> fix: validation in CiJob for external Artifact

- pkg/pipeline/CiService.go
Fixes https://github.com/devtron-labs/devtron/issues/5645
```release-note
```
> fix: nil check for ciBaseBuildConfigBean

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/5676
```release-note
```
> fix: updated common lib

- scripts/sql/275_policy_criteria_table.down.sql
- scripts/sql/275_policy_criteria_table.up.sql
> chore: added config sql script

- pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
- pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
> fix: notes api for oci gitops flow

- pkg/app/AppCrudOperationService.go
- pkg/app/helper.go
- pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
- pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Fixes https://github.com/devtron-labs/devtron/issues/5547
.
> chore: ea fixes for helm app

- scripts/sql/277_insert_devtron_resource_searchable_key_table.down.sql
- scripts/sql/277_insert_devtron_resource_searchable_key_table.up.sql
Fixes https://github.com/devtron-labs/devtron/issues/5710
```release-note
```
> fix: migration syn with ent

- scripts/sql/276_scan_policies.down.sql
- scripts/sql/276_scan_policies.up.sql
> chore: remove sql script

- pkg/app/AppCrudOperationService.go
- pkg/app/helper.go
- pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
- pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Reverts devtron-labs/devtron#5652
> chore: Helm apps entries in Ea mode

- .gitbook.yaml
- docs/SUMMARY.md
- docs/reference/glossary.md
- docs/user-guide/creating-application/deployment-template.md
- docs/user-guide/global-configurations/README.md
- docs/user-guide/global-configurations/deployment-charts.md
**getting-started/global-configurations/custom-charts**: **user-guide/global-configurations/deployment-charts.md**
> doc: Redirection of old entry in gitbook.yaml

- scripts/sql/281_update_scan_tool_metadata.down.sql
- scripts/sql/281_update_scan_tool_metadata.up.sql
Fixes #5302 
```release-note
```
> fix: scan tool active check removed

- scripts/sql/281_update_scan_tool_metadata.down.sql
- scripts/sql/281_update_scan_tool_metadata.up.sql
Fixes #5302
```release-note
```
> fix: Scan tool migration fix develop

- pkg/auth/user/repository/UserAuthRepository.go
Fixes #5784 
```release-note
```
> fix: Sql injection fix develop

- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/servicemonitor.yaml
Added support to enable servicemonitor for extra container ports as well
Fixes #5762
> feat: Added multiple features support in servicemonitor

- docs/setup/install/ingress-setup.md
> docs: modifying route in ingress doc

- docs/setup/install/ingress-setup.md
> docs: modified the anchorlink in ingress.md

- pkg/auth/user/repository/UserAuthRepository.go
Fixes #5784 
```release-note
```
> fix: Sql injection fix

- internal/sql/repository/AppListingRepository.go
Fixes #5824 
```release-note
```
> fix: app details page

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/constants/constants.go
- vendor/github.com/devtron-labs/common-lib/middlewares/recovery.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/metrics/metrics.go
- vendor/modules.txt
Suppressing the reverse proxy panic noises
Fixes https://github.com/devtron-labs/devops-sprint/issues/843 
```release-note
```
> fix: reverse proxy panic noises

- api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
- pkg/pipeline/PipelineStageService.go
Fixes https://github.com/devtron-labs/devtron/issues/5819
```release-note
```
> fix: plugin ip variables value getting changed 

- api/helm-app/service/HelmAppService.go
- internal/sql/repository/app/AppRepository.go
- pkg/app/AppCrudOperationService.go
- pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Fixes https://github.com/devtron-labs/devtron/issues/5547
```release-note
```
> fix: pg multiple rows in EA mode (cherry pick ref - #5865)

- api/appStore/InstalledAppRestHandler.go
Fixes #5870 
```release-note
```
> fix: app overview panic for helm app

- .github/CODEOWNERS
> misc: Update CODEOWNERS

- scripts/sql/288_slack_notification_template.down.sql
- scripts/sql/288_slack_notification_template.up.sql
> misc: added migration to fix default image in slack notification template

- pkg/security/ImageScanService.go
> fix: send image in executionDetail api 

- pkg/pipeline/CiService.go
> fix: nil ptr extra env vars fix

- Dockerfile
- DockerfileEA
- Makefile
> fix: Docker and makefile fix

- pkg/pipeline/CiService.go
Fixes https://github.com/devtron-labs/devtron/issues/5927
```release-note
```
> fix: nil ptr fix in copying extraEnvVars

- client/telemetry/TelemetryEventClient.go
> fix: telemetry dashboard event packet fixes

- Dockerfile
- DockerfileEA
- api/appStore/deployment/CommonDeploymentRestHandler.go
- api/auth/user/UserRestHandler.go
- api/helm-app/HelmAppRestHandler.go
- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
- cmd/external-app/wire_gen.go
- internal/sql/repository/dockerRegistry/DockerArtifactStoreRepository.go
- internal/sql/repository/pipelineConfig/bean/cdWorkflow/bean.go
- pkg/apiToken/ApiTokenService.go
- pkg/appStore/bean/bean.go
- pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
- pkg/appStore/installedApp/service/AppStoreDeploymentService.go
- pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
- pkg/auth/user/RoleGroupService.go
- pkg/auth/user/UserCommonService.go
- pkg/auth/user/UserService.go
- pkg/auth/user/repository/RoleGroupRepository.go
- pkg/auth/user/repository/UserAuthRepository.go
- pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
- pkg/delete/DeleteService.go
- pkg/delete/DeleteServiceFullMode.go
- pkg/resourceQualifiers/helper.go
- scripts/sql/029000_019_release_rbac.down.sql
- scripts/sql/029000_019_release_rbac.up.sql
- scripts/sql/029100_019_notification_settings.up.sql
- scripts/sql/029100_019_notification_stettings.down.sql
- scripts/sql/029200_019_helm_app_deployment_message.down.sql
- scripts/sql/029200_019_helm_app_deployment_message.up.sql
> fix: develop main sync oss

- pkg/argoApplication/ArgoApplicationServiceExtended.go
> fix: Appdetails oss nil fix rc

- pkg/argoApplication/ArgoApplicationServiceExtended.go
> fix: appdetails fix

- api/auth/user/UserRestHandler.go
- api/auth/user/util/util.go
- pkg/auth/user/RoleGroupService.go
- pkg/auth/user/UserService.go
- pkg/auth/user/helper/helper.go
> fix: auth role group fix

- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
> fix:  last deployed filter fix

- pkg/bulkAction/BulkUpdateService.go
- util/SQLUtil.go
> fix: Bulk cm edit fix

- internal/sql/repository/AppListingRepository.go
> fix: app details oss 

- internal/sql/repository/AppListingRepository.go
> fix: oss-app-details

- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
> fix: app status filter for not deployed

- pkg/deployment/manifest/ManifestCreationService.go
> fix: rollback fix

- pkg/pipeline/pipelineStageVariableParser.go
> misc: copy container image version

- client/events/EventBuilder.go
- client/events/EventClient.go
- pkg/app/AppService.go
- pkg/app/DeploymentEventHandler.go
- pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
- pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/CiHandler.go
- pkg/pipeline/CiService.go
- pkg/workflow/dag/WorkflowDagExecutor.go
> fix: notification cluster filter issue

- go.mod
- go.sum
> chore: Common lib update on rc20

- pkg/plugin/repository/GlobalPluginRepository.go
- vendor/modules.txt
> misc: isLatest field in plugin_metadata tag changed to not_null

- pkg/plugin/repository/GlobalPluginRepository.go
- vendor/modules.txt
> misc: Main sync 14 oct 2024

- go.mod
- go.sum
- vendor/modules.txt
> fix: deployment window FIXED type

- pkg/pipeline/DeploymentPipelineConfigService.go
> misc: removed deployment group validation when deleting CD pipelines

- scripts/casbin/10_terminal.down.sql
- scripts/casbin/10_terminal.up.sql
Fixes #5897  
```release-note
```
> feat: terminal role casbin policy

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
> fix: Helm app list cluster filter

- pkg/auth/user/UserCommonService.go
Fixes https://github.com/devtron-labs/devops-sprint/issues/1041
```release-note
```
> misc: permission access getting clubbed

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/grafana.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/values.yaml
> feat: added support for extraconfigs in app-sync and increased the job ttl to 1000

- pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
- pkg/appStore/installedApp/service/FullMode/deployment/DeploymentStatusService.go
- pkg/generateManifest/DeploymentTemplateService.go
> fix: rollback and manifest output

- .github/CODEOWNERS
> misc: code owner modified

- .github/CODEOWNERS
> misc: Main sync rc22 nov7

- .github/CODEOWNERS
> chore: Update codeowner

- scripts/sql/29902300_mandatory_plugin_v2.down.sql
- scripts/sql/29902300_mandatory_plugin_v2.up.sql
Fixes https://github.com/devtron-labs/sprint-tasks/issues/970
```release-note
```
> chore: Mandatory plugin policy v2.0 migration

- pkg/app/AppService.go
- pkg/app/integrationTest/AppService_test.go
- pkg/eventProcessor/in/DeployedApplicationEventProcessorService.go
Fixes https://github.com/devtron-labs/devops-sprint/issues/1223
```release-note
```
> fix: remove unnecessary status update call

- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/statefulset.yaml
* refchart fixes
* changes in service yaml file
* changes in refchart
* changes in value yaml
* changes in custom labels
* changes in sts chart
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1234
```release-note
```
> fix: custom match labels (#2044)

- pkg/cluster/ClusterService.go
> fix: cluster namespace list informer

- pkg/module/ModuleCacheService.go
> fix: module installation fix

- pkg/server/ServerCacheService.go
- pkg/server/ServerService.go
- pkg/server/config/ServerEnvConfig.go
- wire_gen.go
> fix: server version fix  

- internal/sql/repository/AppListingRepository.go
- pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
- pkg/cluster/EnvironmentService.go
- pkg/cluster/repository/EnvironmentRepository.go
- pkg/externalLink/ExternalLinkIdentifierMappingRepository.go
- pkg/security/policyService.go
> fix: external links not visible in case of external helm apps 

- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/statefulset.yaml
- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/values.yaml
> fix: refrence chart protocol fix

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
Fixes #
- k8s.io/kubernetes from v1.29.6 to v1.29.7
- golang-jwt/jwt/v4 from v4.5.0 to v4.5.1
Changes:-
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#changelog-since-v1296
https://github.com/golang-jwt/jwt/releases/tag/v4.5.1
```release-note
```
> chore: depandabot fixes

- .github/CODEOWNERS
> misc: Update codeowner

- api/restHandler/ImageScanRestHandler.go
- internal/sql/repository/app/AppRepository.go
- util/rbac/EnforcerUtil.go
> chore: implemented Rbac enforcer in batch

- pkg/pipeline/CiCdPipelineOrchestrator.go
> chore: ciTemplateReadService fix

- internal/sql/repository/security/ImageScanDeployInfoRepository.go
> security filter fix

- pkg/pipeline/WorkflowService.go
> misc: Main sync devlop nov22

- internal/sql/repository/bulkUpdate/BulkUpdateRepository.go
Fixes: https://github.com/devtron-labs/sprint-tasks/issues/1335
```release-note
```
> misc: bulk update cm/cs name reference update fix

- go.mod
- go.sum
- vendor/github.com/devtron-labs/authenticator/client/oidcClient.go
- vendor/github.com/devtron-labs/authenticator/oidc/oidc.go
- vendor/modules.txt
Fixes: https://github.com/devtron-labs/sprint-tasks/issues/1318
```release-note
```
> misc: authenticator panic fix

- .github/pull_request_template.md
updates pr template to fix pr validation action
Fixes #
```release-note
```
> misc: Update pull_request_template.md

- .github/pull_request_template.md
- .github/workflows/pr-issue-validator.yaml
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1361
```release-note
```
> fix: Update pr-issue-validator.yaml

- pkg/pipeline/CiMaterialConfigService.go
Fixes https://github.com/devtron-labs/devtron/issues/5537
> fix: delete git repo without pipeline config

- Makefile
- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/git-manager/GitCliManager.go
- vendor/github.com/devtron-labs/common-lib/git-manager/util/Util.go
- vendor/modules.txt
> chore: vendor update runtime, changes in makefile

- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
- api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
- pkg/pipeline/CiHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1454
```release-note
```
> fix: panic handling for get workflow logs

- wire_gen.go
> misc: fix wire_gen

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
> chore: panic fix

- internal/sql/repository/bulkUpdate/BulkUpdateRepository.go
- pkg/bulkAction/BulkUpdateService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1565
```release-note
```
> fix: bulk edit fix for global override

- pkg/pipeline/CiService.go
> fix: ci wf runner fail update method

- go.mod
- go.sum
- vendor/modules.txt
> misc: common lib and authenticator lib updated

- api/restHandler/CoreAppRestHandler.go
- api/restHandler/NotificationRestHandler.go
- api/restHandler/app/appList/AppFilteringRestHandler.go
- api/restHandler/app/appList/AppListingRestHandler.go
- api/restHandler/app/pipeline/configure/PipelineConfigRestHandler.go
- api/team/TeamRestHandler.go
- api/team/wire_team.go
- cmd/external-app/wire_gen.go
- internal/sql/repository/app/AppRepository.go
- pkg/appStore/chartGroup/ChartGroupService.go
- pkg/commonService/CommonService.go
- pkg/delete/DeleteService.go
- pkg/delete/DeleteServiceExtended.go
- pkg/eventProcessor/celEvaluator/WorkFlowTriggerEvent.go
- pkg/notifier/NotificationConfigService.go
- pkg/team/TeamService.go
- pkg/team/adapter/adapter.go
- pkg/team/bean/bean.go
- pkg/team/read/readService.go
- pkg/team/repository/TeamRepository.go
- util/rbac/EnforcerUtil.go
- util/rbac/EnforcerUtilHelm.go
- wire_gen.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1120
```release-note
```
> chore: read service for team

- scripts/sql/31002500_devtron_CD_trigger_v1.2.0.down.sql
- scripts/sql/31002500_devtron_CD_trigger_v1.2.0.up.sql
Fixes https://github.com/devtron-labs/devtron/issues/6204
> feat: Support to trigger with same hash in CD trigger plugin 

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
> fix: Sql query fix dec

- manifests/release.txt
Fixes chart sync action not accepting major minor release
> release: Fix chart sync action

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
> misc: Main sync develop 30dec

- scripts/sql/31402600_approval_policy.down.sql
- scripts/sql/31402600_approval_policy.up.sql
> chore: sql script sync

- scripts/sql/31502600_devtron_CD_trigger_v1.3.0.down.sql
- scripts/sql/31502600_devtron_CD_trigger_v1.3.0.up.sql
Fixes #6234
```release-note
```
> chore: Changes in CD trigger plugin condition v1.3.0

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/imageScan/bean/bean.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
- vendor/modules.txt
> misc: Vendor update on rc26

- pkg/cluster/ClusterService.go
> misc: isProd in cluster

- pkg/app/AppListingService.go
> fix: error handling when artifact is nil

- go.mod
- go.sum
- internal/middleware/instrument.go
- pkg/infraConfig/service/infraConfigService.go
- vendor/github.com/devtron-labs/common-lib/utils/CommonUtils.go
- vendor/github.com/devtron-labs/common-lib/utils/bean/bean.go
- vendor/modules.txt
> sync: Pg enable init fix

- internal/middleware/instrument.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1587
```release-note
```
> fix: remove unused variable causing double register in prometheus

- pkg/policyGovernance/security/imageScanning/ImageScanService.go
> fix: put len check on parentCiArtifactIds in scan list

- pkg/policyGovernance/security/imageScanning/ImageScanService.go
> fix: IsErrNoRows check on image and imageDigest

- scripts/devtron-reference-helm-charts/deployment-chart_4-19-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-19-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-19-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-19-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/service.yaml
Fix the app metrics issue where latency and throughput metrics were not available.
Fixes https://github.com/devtron-labs/devtron/issues/6281
```release-note
```
> chore: fix for app metrics issue

- client/argocdServer/connection/Connection.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1782
```release-note
```
> fix: removing gitops configured check

- go.mod
- go.sum
- vendor/modules.txt
> sync: vendor update

- pkg/deployment/manifest/ManifestCreationService.go
> chore: nil check in envOverride.chart

- api/restHandler/app/appList/AppListingRestHandler.go
- api/restHandler/app/appList/AppListingRestHandler_ent.go
> chore: updated ApplistingRestHandler oss/ent function

- pkg/policyGovernance/security/imageScanning/ImageScanService.go
- pkg/policyGovernance/security/imageScanning/ImageScanService_ent.go
> feat: oss ent changes in image scan service

- api/restHandler/app/appList/AppListingRestHandler_ent.go
Fixes https://github.com/devtron-labs/devtron/issues/6323
```release-note
```
> fix:  appDetail data override change

- client/argocdServer/repoCredsK8sClient/repoCreds.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1825
```release-note
```
> fix: error in deleting chart repo from global config

- scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0/schema.json
- scripts/devtron-reference-helm-charts/cronjob-chart_1-4-0/schema.json
- scripts/devtron-reference-helm-charts/cronjob-chart_1-5-0/schema.json
> misc: Fix typo: Cronjob → CronJob

- pkg/auth/user/UserCommonService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1848
```release-note
```
> fix: role group k8s permissions duplication

- pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1861
```release-note
```
> fix: role group listing fix

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
- vendor/modules.txt
> misc: common-lib change

- pkg/pipeline/workflowStatus/repository/WorkflowStageRepository.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1824
```release-note
```
> sync: Workflow execution stage fix

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/CdHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1824
```release-note
```
> fix: workflow status fix for pre and post cd

- pkg/pipeline/workflowStatus/WorkflowStageStatusService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1824
```release-note
```
> fix: Unknown event fix

- go.mod
- go.sum
- vendor/modules.txt
> sync: vendor update on release 29

- internal/sql/repository/pipelineConfig/PipelineRepository.go
Fixes https://github.com/devtron-labs/devtron/issues/6374
```release-note
```
> fix: devtron apps deployed via helm showing in helm apps list

- api/bean/gitOps/GitOpsConfig.go
- pkg/appClone/AppCloneService.go
- pkg/chart/ChartService.go
- pkg/chart/read/ChartReadService.go
- pkg/deployment/common/adapter/adapter.go
- pkg/deployment/common/bean/bean.go
- pkg/deployment/common/deploymentConfigService.go
- pkg/deployment/common/helper.go
- pkg/deployment/common/read/deploymentConfigReadService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/DeploymentPipelineConfigService.go
> chore: deployment config refactorings

- Dockerfile
- DockerfileEA
Fixes https://github.com/devtron-labs/devops-sprint/issues/1546
```release-note
```
> fix: Base update

- pkg/pipeline/BuildPipelineConfigService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1905
```release-note
```
> fix: panic fixes 

- USERS.md
Fixes #6416 
```release-note
```
> doc: Fix Typo in Users.MD file

- USERS.md
Fixes #6416 
```release-note
```
> doc: Fixed Typo in Users.md

- go.mod
- go.sum
- vendor/modules.txt
> sync: vendor update in main

- cmd/external-app/wire_gen.go
- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
- vendor/modules.txt
- wire_gen.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1939
```release-note
```
> chore: common lib version bump

- pkg/pipeline/CiCdPipelineOrchestrator.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1868
```release-note
```
> fix: createDockerRepoIfNeeded error handling

- go.mod
- go.sum
- pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
- vendor/modules.txt
> sync: Main sync develop 10mar

- pkg/userResource/logicRouteService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1827
```release-note
```
> fix: ea mode helm app list 

- pkg/pipeline/DeploymentPipelineConfigService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2001
```release-note
```
> fix: onboard acd app

- pkg/cluster/ClusterServiceExtended.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1901
```release-note
```
> fix: in CreateGrafanaDataSource

- api/bean/ConfigMapAndSecret.go
- pkg/bean/configSecretData.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1960
```release-note
```
> fix: external secret

- internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
- pkg/pipeline/CiHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2023
```release-note
```
> fix: optimisation in workflow status api

- pkg/pipeline/CdHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1994
```release-note
```
> fix: force abort for pre/post cd 

- go.mod
- go.sum
- pkg/cluster/ClusterServiceExtended.go
- vendor/github.com/devtron-labs/authenticator/client/oidcClient.go
- vendor/modules.txt
> sync: Main sync develop 8apr

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/CommonUtils.go
- vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go
- vendor/github.com/devtron-labs/common-lib/utils/bean/bean.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2084
```release-note
```
> fix: postgresql skip unique constraints error and handle network connection error

- go.mod
- go.sum
- vendor/modules.txt
> sync: main sync and vendor update

- api/cluster/EnvironmentRestHandler.go
- api/cluster/EnvironmentRouter.go
- client/grafana/GrafanaClient.go
- cmd/external-app/wire.go
- cmd/external-app/wire_gen.go
- go.mod
- go.sum
- internal/sql/repository/chartConfig/EnvConfigOverrideRepository.go
- pkg/chart/ChartService.go
- pkg/cluster/ClusterServiceExtended.go
- pkg/cluster/environment/EnvironmentService.go
- pkg/cluster/environment/bean/bean.go
- pkg/deployment/manifest/deploymentTemplate/read/chartEnvConfigOverride.go
- vendor/modules.txt
- wire_gen.go
> sync: Main sync develop

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/blob-storage/AwsS3Blob.go
- vendor/github.com/devtron-labs/common-lib/blob-storage/BlobUtils.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2095
```release-note
```
> fix: added support for IAM role S3 blob client

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/constants/constants.go
- vendor/modules.txt
> sync: Vendor update develop

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/CdHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1828
```release-note
```
> fix: re trigger cd when pod deleted fix

- scripts/sql/33003500_update_chart_ref.down.sql
- scripts/sql/33003500_update_chart_ref.up.sql
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2127
```release-note
```
> fix: chart name fixed in chart reference table

- api/bean/ConfigMapAndSecret.go
- api/bean/ConfigMapAndSecret_ent.go
- go.mod
- go.sum
- pkg/deployment/trigger/devtronApps/preStageHandlerCode.go
- pkg/executor/WorkflowService.go
- pkg/pipeline/ArgoWorkflowExecutor_test.go
- pkg/pipeline/PipelineStageService.go
- pkg/pipeline/bean/pipelineStage.go
- pkg/pipeline/bean/pipelineStage_ent.go
- pkg/pipeline/bean/workFlowRequestBean.go
- pkg/pipeline/bean/workFlowRequestBean_ent.go
- pkg/pipeline/executors/adapter/adapter.go
- pkg/pipeline/executors/adapter/adapter_ent.go
- pkg/pipeline/executors/argoWorkflow.go
- pkg/pipeline/executors/bean.go
- pkg/pipeline/executors/systemWorkflow.go
- pkg/pipeline/executors/utils.go
- pkg/pipeline/types/Workflow.go
- pkg/pipeline/types/Workflow_ent.go
- util/sliceUtil/SliceUtil.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
- vendor/github.com/devtron-labs/common-lib/workflow/bean.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2110
```release-note
```
> feat: mount file type variable in ci-runner through cm

- scripts/sql/32903500_alter_pipeline_timeline.up.sql
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1829
```release-note
```
> chore: updated pipeline timeline index sql change

- .github/workflows/auto-label.yml
- charts/devtron/Chart.yaml
- charts/devtron/templates/configmap-secret.yaml
- go.mod
- go.sum
- vendor/modules.txt
> sync: Main sync RC

- go.mod
- go.sum
- vendor/modules.txt
> sync: Vendor update for packet 35

- scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/servicemonitor.yaml
Fixes https://github.com/devtron-labs/devops-sprint/issues/1820
```release-note
```
> feat: added support for relabelings in servicemonitor

- pkg/deployment/manifest/ManifestCreationService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2231
```release-note
```
> fix: deployment with specific trigger for rollout chart 

- pkg/server/ServerCacheService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2164
```release-note
```
> fix: stack manager break fix

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/utils/SqlUtil.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2248
```release-note
```
> fix: Remove funtionName from labels from pg_query_duration_seconds_* metrics

- .github/workflows/pr-issue-validator.yaml
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1311
```release-note
```
> fix: centralised PR validator

- pkg/app/AppService.go
- pkg/argoApplication/helper/deploymentStatusHelper.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2271
```release-note
```
> fix: deployment status is stuck is progressing for parallel deployments in devtron application

- pkg/pipeline/DeploymentPipelineConfigService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2116
```release-note
```
> fix: Change ci to webhook fix

- internal/sql/repository/pipelineConfig/CiTemplateOverrideRepository.go
- pkg/build/pipeline/CiTemplateReadService.go
- pkg/pipeline/CiMaterialConfigService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2330
```release-note
```
> fix: prevent deletion of git material used in overridden CI templates

- go.mod
- go.sum
- internal/sql/repository/pipelineConfig/CiTemplateOverrideRepository.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- pkg/appWorkflow/AppWorkflowService.go
- pkg/build/pipeline/CiTemplateReadService.go
- pkg/bulkAction/service/BulkUpdateService.go
- pkg/deployment/manifest/deploymentTemplate/DeploymentTemplateHistoryService.go
- pkg/pipeline/CdHandler.go
- pkg/pipeline/CiMaterialConfigService.go
- pkg/pipeline/DeploymentPipelineConfigService.go
- pkg/pipeline/DevtronAppConfigService.go
- pkg/pipeline/history/repository/DeploymentTemplateHistoryRepository.go
- scripts/sql/33403601_alter_deployment_template_history.down.sql
- scripts/sql/33403601_alter_deployment_template_history.up.sql
- vendor/modules.txt
> sync: Release candidate v0.37.0 main sync

- pkg/appWorkflow/AppWorkflowService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2365
```release-note
```
> fix: app workflow cd pipleine check

- scripts/sql/33503700_gpu_workload_chart.down.sql
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2272
```release-note
```
> fix: Down script for gp workload fixed

- pkg/appClone/AppCloneService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2400
```release-note
```
> fix: app clone panic

- client/cron/CdApplicationStatusUpdateHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2428
```release-note
```
> fix: timeline cron change

- pkg/deployment/common/bean/bean.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2448
```release-note
```
> fix: argo sync

- api/restHandler/TelemetryRestHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2452
```release-note
```
> fix: telemetry panic fix

- pkg/deployment/trigger/devtronApps/postStageHandlerCode.go
> chore: post trigger 

- internal/sql/repository/NotificationSettingsRepository.go
- pkg/k8s/application/k8sApplicationService.go
> misc: notification table fix

- pkg/workflow/status/WorkflowStatusService.go
> misc: Timeout main notification

- api/cluster/ClusterRestHandler.go
- pkg/cluster/ClusterService.go
- pkg/cluster/bean/bean.go
> chore: Fix cluster and environment page

- pkg/pipeline/DeploymentPipelineConfigService.go
> flux ns missing fix

- client/telemetry/TelemetryEventClient.go
- cmd/external-app/externalApp.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2558
```release-note
```
This pull request enhances error handling in the telemetry client and external application by introducing asynchronous processing for cloud provider identification and telemetry event sending, improving reliability and responsiveness.
</div>
> fix: error handler correction

- internal/util/ChartTemplateService.go
- scripts/devtron-reference-helm-charts/reference-chart-proxy/Chart.yaml
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2595
```release-note
```
This pull request fixes a bug in handling custom charts with dependencies in Devtron applications by refining the logic for chart metadata processing. It also adds a new chart YAML file that includes the required API version and description, improving chart configuration clarity.
</div>
> fix: Custom chart with dependencies are not working in Devtron Applications
