devtron-labs/devtron

- internal/sql/repository/DockerArtifactStoreRepository.go
- pkg/pipeline/PipelineBuilder.go
create docker repo only when repo type is ECR
Fixes #309 
> repo create only when provider type ecr

- pkg/cluster/ClusterService.go
cluster listing default component installedAppId comes wrong, fixed in this release.
https://github.com/devtron-labs/devtron/issues/377
> HOTFIX: cluster listing default component id fixed

- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/.helmignore
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/.image_descriptor_template.json
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/Chart.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/env-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/pipeline-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/release-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/secrets-test-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/NOTES.txt
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/_helpers.tpl
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/configmap.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/generic.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/hpa.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/metrics-service-monitor.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/poddisruptionbudget.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/pre-sync-job.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/prometheusrules.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/service.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/servicemonitor.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/sidecar-configmap.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/test_values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/values.yaml
This PR contains changes in `ingress.yaml` to support configuration of multiple hosts/paths.
Fixes #375 
Configurations can be done in `values.yaml` to test various cases:
> Feature enhancement to support #375

- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml
Configmap as volume - Volume creation fails if the Configmap name has a dot #438 
Fixes # (issue) https://github.com/devtron-labs/devtron/issues/438
> Hotifx chart 3.11 volume name validation

- api/restHandler/ApplicationRestHandler.go
- api/router/ApplicationRouter.go
> all all resource type deletion

- api/restHandler/EnvironmentRestHandler.go
- api/restHandler/UserAuthHandler.go
- api/restHandler/UserRestHandler.go
- pkg/cluster/ClusterService.go
bugfixes bugathon - soft delete cluster list, user role , group api error response structure
Fixes # (issue) https://github.com/devtron-labs/devtron/issues/210
https://github.com/devtron-labs/devtron/issues/476
https://github.com/devtron-labs/devtron/issues/478
> FIX: Hotfixes epic bugathon 02 ISSUE: user auth issues, api error response , cluster soft delete 

- pkg/pipeline/PipelineBuilder.go
Currently, in the Docker Build Config section, if a user specifies a Docker repository name, then the repo is never created. Devtron only creates a new Docker repo in the registry if that field is left blank. This is very confusing to the user, as on saving the config, the user expects a repo to be created.
Proposal
Specifying a Docker repo name should always be an upsert operation. If there is no repo in registry with the same name, a new repo should be created. If there is already an existing repo with same name, UI can display a warning message to the user: Proceed/Rename, with a suggestion like: You can leave the Docker repo name as blank, and we will create it for you as devtron/app_name.
Fixes #441 
Manually
> FEATURE: Specifying Docker repo should be an upsert operation

- docs/user-guide/creating-application/deployment-template.md
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml
This enhancement lets users adds Pod annotation on their deployments.
Included documentation for Pod Annotations and Pod Labels. 
Fixes #532 
Tested locally with helm template command
> FEATURE: Chart 3.11.0 Pod Annotations support

- manifests/installation-script
- manifests/yamls/grafana.yaml
This PR fixes grafana metrics not visible on devtron dashboard issue and removes dependency on Prometheus datasource
- Changed default datasource name from Prometheus-devtron to Prometheus-devtron-demo as required by our default namespace name and the API was also using this name to fetch
- Removed Prometheus datasource from yaml file as we had to Manually update Prometheus datasource to show the metrics on dashboard
> FIX: Changed grafana datasource name and removed Prometheus datasource

- client/argocdServer/k8sClient.go
- internal/sql/repository/appstore/chartGroup/ChartGroupDeployments.go
- pkg/appstore/AppStoreDeploymentService.go
When you deploy a chart multiple times after deleting again and again, one of the deployments gets stuck and it isn't deleted from argocd side so you see multiple deployments of the same and isn't able to delete from the UI too.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/679
successfully.
> FIX: chart duplicate installation

- docs/user-guide/global-configurations/gitops.md
In order to validate GitOps configuration `delete_repo` permission on access token is needed. Without it, I get the following error:
```
DELETE https://api.github.com/repos/<my_org>/devtron-sample-repo-<random_string>: 403 Must have admin rights to Repository.
```
Fixes #725 
- [y] Bug fix (non-breaking change which fixes an issue)
- follow the steps from the issue related to this PR
* [y] The title of the PR states what changed and the related issues number (used for the release note).
* [y] Does this PR require documentation updates?
* [y] I've updated documentation as required by this PR.
> DOC: Add `delete_repo` in documentation on what perrmissions are needed in GitOps PAT

- go.mod
Helm version has been fixed in go.mod file.
While installing dependencies, got this error for helm - 
```
go: errors parsing go.mod:
/Users/abhi/go/src/github.com/devtron/go.mod:109:2: require k8s.io/helm: version "v2.12.3" invalid: should be v0 or v1, not v2
```
changing the version in go.mod file solved the issue
> FIX: Helm version fixed

- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/Cronjob.yaml
In case of passing more than one podLabels podLables other than 1st one faces indentation error
> Updated Cronjob.yaml

- manifests/installation-script
- manifests/yamls/external-secret.yaml
- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-10-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-8-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-9-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/secret.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/secret.yaml
- Updated Kubernetes External secret CRDs
- Sync Kubernetes External chart from latest chart (8.5.1)
- Fixed ExternalSecret roleARN issue
Fixes #1068 
Tested on a k8s 1.22 cluster
> Fix Kuberntes External secret k8s 1.22 compatibility issue

- manifests/yamls/rollout.yaml
This PR fixes the issues with app-metrics or envoy configmap not being able to be mounted or configmaps and secrets not being able to be applied as data-volume
> FIX: Fixed Rollout CRDs for configmaps

- util/rbac/EnforcerUtil.go
Issue Fixed
Issue: Not able to see charts for permission project:devtron-demo; cluster:demo1; All apps; permission: view & edit even though there are helm apps available for selected permission.
> environment identifier fixed for helm apps rbac

- internal/sql/repository/CiArtifactRepository.go
- pkg/pipeline/CiService.go
- pkg/pipeline/WorkflowService.go
- pkg/security/policyService.go
When image scanning is enabled, user is not able to view scan results data when selecting image in cd pipeline. This bug is in the case when parent is ci pipeline. The query for finding artifacts from ci pipeline does not select data columns for image scan bool, which leads to the bug.
> FIX : image scan bug

- client/k8s/informer/K8sInformerFactory.go
- pkg/cluster/ClusterService.go
- pkg/cluster/ClusterServiceExtended.go
Requirement is to stop or close informer runner forcefully on cluster deletion or any cluster config update.
- added informer sync function,  triggered when config modified for any cluster.
- added in both ea and full mode.
- code refactored for buildInformer from Add and Update cluster request.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/1165
> fix: Namespace informer cache object close on config update

- pkg/user/casbin/Adapter.go
- pkg/user/casbin/rbac.go
In the release #1128, a customised function in casbin enforcer was added for matching keys. This function was being added at runtime for every auth enforcer request. This was causing concurrent write and read operation in the map containing all the key matching functions. Fixed this and removed this function from runtime.
> FIX : auth bug causing panic

- scripts/sql/35_alter_old_db.down.sql
- scripts/sql/35_alter_old_db.up.sql
Old database for orchestrator in some clusters contains redundant tables which are not used and are blocking other features due to some constraints they have. Create and drop queries of these tables are not present in earlier scripts, and they are either formed due to manual changes or wrong migration which are not reverted. Added script for dropping these tables if they exist. The tables are - 
1. casbin_role
2. casbin
3. external_apps
4. pipeline_config
> FIX : drop redundant tables in database

- client/telemetry/TelemetryEventClient.go
- client/telemetry/TelemetryEventClientExtended.go
Description
Sending Devtron mode for both Full mode and Hyperion mode
Cause: Payload didn't have Devtron mode
CounterMeasure: Added Devtron mode in payload
Fixes # (issue) 1122
Type of change
[ Yes] Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
How Has This Been Tested?
Test case A: Tested it by installing EA mode (Updated PostHog API key value to send events to mine) and have seen the events send to my PostHog server and also checked again re-running the pod which will not send the event as we store the value in config map and ignore if it is already sent
Test case B: Tested by sending …
> fix: Send Devtron mode for events[EA2][1122]

- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/app-values.yaml
- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/Cronjob.yaml
- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/templates/job.yaml
- scripts/devtron-reference-helm-charts/cronjob-chart_1-2-0/test_values.yaml
Currently in Job and CronJob manifest there is no option to add security context. 
Updated the Job and CronJob manifests to support security context.
> Job Cronjob security context

- docs/setup/install/install-devtron-helm-2.md
- docs/setup/install/install-devtron-helm-3.md
- docs/setup/install/install-devtron-using-kubectl.md
- docs/user-guide/creating-application/deployment-template/rollout-deployment.md
Updates in documentation:
1. Added how we can see logs of devtron installer while installing devtron.
2. Added how we can apply liveness & readiness probes by executing commands.
3.  Added `pathType` in ingress.
> DOC: Documentation updates for devtron installation, ingess, liveness and readiness probe

- client/k8s/informer/K8sInformerFactory.go
Getting error while application startup, as k8s factory gives nil pointer. fixed rest client variable initialisation. 
> FIx: hotfix k8s factory cluster config nil pointer issue

- api/appStore/deployment/AppStoreDeploymentRestHandler.go
- pkg/appStore/deployment/AppStoreDeploymentService.go
If Linking an external helm chart gives error (from helm) then db operation should be rollback.
Fixes # https://github.com/devtron-labs/devtron/issues/1381
by linking kubewatch chart
> fix:  Rollbacking DB operation if helm operation fails during linking with devtron chart

- docs/user-guide/creating-application/config-maps.md
- docs/user-guide/debugging-deployment-and-monitoring.md
- docs/user-guide/security-features.md
- docs/user-guide/use-cases/connect-django-with-mysql-database.md
- docs/user-guide/use-cases/connect-expressjs-with-mongodb-database.md
- docs/user-guide/use-cases/connect-springboot-with-mysql-database.md
- docs/user-guide/use-cases/devtron-generic-helm-chart-to-run-cron-job-or-one-time-job.md
Changed images used in documentation and some other corrections.
> Doc: Image change in documentation

- docs/hyperion/user-guide/global-configurations/sso-login.md
- docs/user-guide/global-configurations/sso-login.md
Changed image URL for the sso-login page(Hyperion).
> docs: Changed image url for sso-login page(hyperion)

- docs/user-guide/creating-application/app-details.md
- docs/user-guide/global-configurations/external-links.md
Fixing the image resizing in **Global Configurations > External links** page. The markdown styling resized the images. So removing the extra space.
Also adding the missing image captions in **Global Configurations > App Details** page.
> docs: Fixing image resizing on external links page

- docs/user-guide/global-configurations/external-links.md
Fixing table rendering in **Global Configurations > External links** page.
> Docs: Fixing table spacing in External links page

- pkg/pipeline/PipelineBuilder.go
Updated limit from 30 to 10 in PipelineBuilder.go
Changed line number 1751 from PipelineBuilder.go to change limit from 30 to 10. Currently when we open select image in deployment pipeline we should all the images which have been built using the system, we need to restrict it to 10
fixes: #1593
> Update PipelineBuilder.go limit to 10

- .github/workflows/chart-sync.yaml
Updated the script to run on pull request merge events with the release-bot branch in main.
> Updated chart-sync workflow

- README.md
The installation status is specific to installing the Devtron with CI/CD integration alone.
Making the installation section a sub-heading to CI/CD integration.
Install Devtron without CI/CD integration with the following command:
```bash
helm repo add devtron https://helm.devtron.ai
helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd
```
As the installation is pretty quick, the installation status returns no output:
```bash
kubectl -n devtroncd get installers installer-devtron \
-o jsonpath='{.status.sync.status}'
```
> Updating installation status info for CI/CD

- docs/user-guide/creating-application/app-details.md
- docs/user-guide/global-configurations/external-links.md
The external links are visible only at the configured resource level. Updating the document with a clear message on the External links page.
The feature has been tested on the staging env dashboard under **Global configurations > External links** page.
> docs: Updating the messaging for viewing external links

- docs/user-guide/creating-application/deployment-template.md
- docs/user-guide/creating-application/workflow/ci-pipeline.md
- docs/user-guide/global-configurations/custom-charts.md
A super admin can now create your helm charts and upload them as custom charts. All users can use the custom charts. 
Tested on demo dashboard under **Global Configurations > Custom charts**.
> docs: Adding docs for custom charts (BYOC)

- pkg/app/AppService.go
- pkg/chartRepo/repository/ChartRepoRepository.go
App deployment status is stuck at "Starting" sometime on build and history page for some apps.
Create an app with all the configurations. In "Charts" table it would insert an entry. Now delete that app and create app with same name with all the configurations. In "Charts" table it would again insert an entry. So "Charts" table would have two rows with active=true and latest=true and git_repo_url=<>'. This is creating the problem. So need to check app active state.
Fixes  https://github.com/devtron-labs/devtron/issues/1652
By hitting DB queries and manually
> fix: App deployment status is stuck at "Starting" sometime on build and history page for some apps

- pkg/pipeline/BulkUpdateService.go
Fix for - 
1. bulk update panic when user does not provides **excludes** field.
2. updated secret bulk edit handling - secret' values are encoded & decoded on FE side for save/update operations. Handled this on BE for bulk update.
> fix: bulk edit panic and secret update

- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/test_values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/test_values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/env-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/test_values.yaml
Added `workingDir:` parameter in rollout-chart 4-xx onwards. It will help users to set their working directory and execute commands in it if any.
Fixes #1860
> FEAT: Added workingDir parameter in reference-chart_4-xx

- api/apiToken/ApiTokenRestHandler.go
description can be empty while creating/updating api-token
Fixes  https://github.com/devtron-labs/devtron/issues/1893
By hitting api-token create/update with description empty and non-empty
> fix : description can be empty while creating/updating api-token

- client/argocdServer/application/Application.go
In case of multiple rollouts | deployments, pods of one rollout or deployment are showing in "Old" tab on app details page. They should be shown in "New" tab as they are new pods.
Fixes  https://github.com/devtron-labs/devtron/issues/1913
app detail resource tree test (specially pods and its old/new status) for multiple rollouts, multiple deployments, single rollout, single deployment
> fix: Pods of one rollout are showing in "Old" tab in resource tree in case of multiple rollouts

- internal/sql/repository/appWorkflow/AppWorkflowRepository.go
Ci pipeline deletion throws error that cd pipeline exists when there a cd pipeline with id = ciPipelineId and has a children cd. This makes the check of having children pass even when there is none. Updated the query to check children of ci pipeline independent of other pipelines.
> fix: ci pipeline deletion bug fix

- manifests/yamls/argocd.yaml
Fixed default namespaces of serviceAccounts in argocd.yaml which were getting binded to clusterrolebindings from argocd to devtroncd
> [FIX] Changed Argocd clusterrolebinding namespaces to devtroncd

- internal/util/ChartService.go
When cd is triggered, currently 2 commits are pushed to git repo (gitops). 
1)  Chart
2) Release file
Chart should be pushed only if chart is not present on git i.e. first commit should be conditional. 
Fixes  https://github.com/devtron-labs/devtron/issues/2060
By checking gitops repo content on : 
1) first cd trigger
2) multiple cd trigger
3) cd trigger after changing chart version in env override.
> fix: multiple commits in git-repo fix

- pkg/notifier/NotificationConfigBuilder.go
- pkg/notifier/NotificationConfigService.go
In notification create and update request, destination is override. removed that part. now only destination being sent in API would be honoured. 
by hitting apis
> fix : destination fix in notification for smtp and ses for custom recipients for create and update request

- App.go
- pkg/user/casbin/Adapter.go
- pkg/user/casbin/rbac.go
- pkg/user/casbin/rbac_test.go
- pkg/user/casbin/rbacpolicy.go
Earlier we introduced Enforcer Caching on Dashboard List APIs which has improved the Dashboard load time but there are other areas that are also impacted by Enforcer.
Following Scenarios has been tested.
> Enforcer cache For all the remaining APIs

- api/user/UserRestHandler.go
- api/user/UserRouter.go
- pkg/user/casbin/Adapter.go
- pkg/user/casbin/rbac.go
- pkg/user/casbin/rbac_test.go
Error from Enforcer is getting diluted and its response is getting updated in Cache, which should not be the idle behavior. Along with this, we have exposed 2 APIs invalidate & cacheDump which can only be accessed by SuperAdmin Users.
Fixes #2072
> enforcer invalidate & cache dump API exposed

- pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
- scripts/sql/66_app_store_application_version_index.down.sql
- scripts/sql/66_app_store_application_version_index.up.sql
Performance issue fix while getting the Data from DB for chart versions for a particular chart : 
1) DB query optimised
2) Index created in DB. earlier query plan was using Seq scan which was slow. hence created index to use Index scan
Fixes  https://github.com/devtron-labs/devtron/issues/2109
by checking the performance of the API
> fix: Performance optimisation while getting the Data from DB for chart versions for a particular chart

- api/restHandler/ArgoApplicationRestHandler.go
- api/router/ApplicationRouter.go
- pkg/app/AppService.go
- pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
With the updated argo stack, users are faced with the issue in which new pod after a deployment goes into terminating state for a while and the old pod(of the old replicaset) gets up again. It takes a while before the new revision is applied stably. 
Fixes #2186 
In orhestrator, we used to invoke the api for manual trigger to remove any lags, which in some cases caused the revision to revert back(as argo apps are auto sync enabled and revision is not updated by auto sync).
> fix: New pod goes into terminating state for sometime before getting up again

- pkg/pipeline/CiHandler.go
Currently CI can be triggered by giving githash from another branch which is a security issue. fixed that issue. 
Fixes  https://github.com/devtron-labs/devtron/issues/2131
By testing manual CI trigger API by giving another branch githash. it is giving error now. 
Happy case is also working.
> fix : able to trigger ci using git hash from another branch

- docs/user-guide/global-configurations/cluster-and-environments.md
Updated documentation for generating bearer token and getting server url to add cluster over devtron. Also addded command for the same for microk8s cluster.
> docs: get bearer token and server url doc update

- api/bean/AutocompleteConfig.go
- api/cluster/EnvironmentRestHandler.go
- api/team/TeamRestHandler.go
- util/CommonConstant.go
made auth config driven using a flag. user can set flag through config map, when flag is set auth is bypassed for autocomplete APIs of projects and environments.
Fixes #2283
> Autocomplete data config driven

- api/user/UserRestHandler.go
- pkg/user/UserService.go
user service isSuperAdmin API deprecated, from now onwards this will be driven through enforcer.
Fixes #2287
> api deprecated + superadmin handling added

- api/restHandler/TelemetryRestHandler.go
Telemetry API has a super-admin auth check, removing this check so that non-super admin data could also be collected.
Fixes #1972
> admin auth check removed

- pkg/module/ModuleService.go
If any new module extracted out from cicd, then for that module, handling status as installed if cicd was installed before introducing that
By checking the status of futuristic modules
> fix: generic handling for module status in future scope

- pkg/module/ModuleService.go
- pkg/module/util/ModuleUtil.go
- pkg/server/ServerService.go
If any module has multiple implementation, for eg : security has two impl (clair, trivy), then in that case while updating helm release security.enabled and security.clair.enabled should be true
By checking the status of futuristic modules
> fix : generic module status handling : eg - security module handling security.enabled and security.clair.enabled

- internal/sql/repository/security/CvePolicyControle.go
When we update security policy for an application of a particular env, it updates the property for a particular app and env id but it is showing value for all the environments.
Fixes #2349
> App Level Security Policy Override Issue

- pkg/chartRepo/ChartRepositoryService.go
- pkg/chartRepo/ManualAppSyncYaml.go
- pkg/server/config/ServerEnvConfig.go
Fixing app sync manual job resource limit based on some environment variable.
APP_SYNC_JOB_RESOURCES_OBJ={"limits" :{"cpu" : "50m","memory": "200Mi"},"requests" : {"cpu" : "50m","memory": "200Mi"}}
In cm-
APP_SYNC_JOB_RESOURCES_OBJ: '{"limits" :{"cpu" : "50m","memory": "200Mi"},"requests"
: {"cpu" : "50m","memory": "200Mi"}}'
By generating the manifest for both cases- variable true and false
> fix: limiting resources for app sync manual job

- Dockerfile
- DockerfileEA
Changes required for multi-arch build for devtron with and without CICD mode
Fixes #1473
> FIX: Changes for multi-arch build

- api/restHandler/app/DeploymentPipelineRestHandler.go
- api/router/PipelineConfigRouter.go
- internal/sql/repository/DeploymentGroupRepository.go
- internal/sql/repository/appWorkflow/AppWorkflowRepository.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- pkg/bean/app.go
- pkg/pipeline/PipelineBuilder.go
- specs/bulk-env-delete.yaml
Support for cd pipeline bulk deletion on basis of appIds and projectIds.
Fixes #2545
> feat: added support for cd pipelines bulk deletion

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
- .github/pull_request_template.md
Updated issue template
Updated PR template
> chore: Updated issue and pr template

- pkg/module/Bean.go
- pkg/module/ModuleCronService.go
- pkg/module/ModuleService.go
If devtron is installed with cicd then cicd module status should go in installing. 
Fixes #2571
1) cicd module should be installable from UI if devtron is installed without cicd. and its status should be updated to installed if installed successfully.
2) cicd module should be shown as installing if devtron is installed with cicd and user logged in dashboard before installation completes. and after sometime the status should change to installed when installation finishes.
3)  cicd module should be shown as installed if user logged into dashboard after installation completes.
> fix: showing cicd module status as installing if devtron is installing with cicd module

- scripts/sql/91_create_chart_metadata.up.sql
Fixed the semicolon missing in sql scripts
Fixes #
```release-note
```
> fix: sql script semicolon fix

- api/appbean/AppDetail.go
- api/restHandler/CoreAppRestHandler.go
- wire_gen.go
Recently we have modified Ci Build Config in which we have added support for Buildpack and managed docker file feature, which impacted app creation API, so dockerBuildConfig param is still existing for backward compatibilty.
Fixes #2561 
```release-note
```
> Ci Build config API backward compatibilty

- .github/semantic.yml
- .github/workflows/update-release-notes.yml
This action will automatically update the closed PR title and number in release notes file so that it can be used during release creation
```release-note
```
> chore: Created update-release-notes.yml github action

- api/restHandler/AppListingRestHandler.go
- client/argocdServer/application/Application.go
In acd resource tree response, health is coming as nil for nodes which are in missing state but health is coming as expected in another API of acd. so overriding health in resource tree nodes for which health is nil in resource tree and not nil in the other API. 
Fixes #2593 
resource tree response for Apps for which some of the nodes are in missing state
```release-note
```
> fix: health fix for nodes in resource tree for missing state

- docs/user-guide/creating-application/secrets.md
> docs: updated doc for aws secret manager 

- pkg/pipeline/CiService.go
Dockerfile checkout path was not working for earlier created apps. Checkout path was getting appended twice to actual dockerfile path
Fixes #2617 
```release-note
```
> Docker checkout path Fix

- pkg/app/AppService.go
- scripts/devtron-reference-helm-charts/reference-chart_3-10-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-12-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_3-12-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-13-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_3-13-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_3-9-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-10-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-11-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-12-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-13-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-13-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-14-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-14-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-15-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-15-0/templates/ingress.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-15-0/test_values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-15-0/values.yaml
Updated all the charts with schema.json and some fixes in the reference chart to smoothly update from the old reference chart version.
> fix: updated devtron-reference-chart directory

- scripts/sql/93_update_chart_metadata.down.sql
- scripts/sql/93_update_chart_metadata.up.sql
Changed description for charts for all the chart type in the base deployment template (Cronjob and Job, Rollout Deployment, Knative and Deployment). Written sql scripts for updating the chart types description.
Fixes #
```release-note
```
> fix: changed the description for chart types, written update sql scripts

- pkg/user/UserService.go
When we create user with same email id as deleted user,  won't allow to create with super admin permission. this PR will fix this issue.
Fixes #: #2640
```release-note
```
> Fix: user re create with super admin permission fix.

- contrib-chart/reference-chart_4-15-0/.helmignore
- contrib-chart/reference-chart_4-15-0/.image_descriptor_template.json
- contrib-chart/reference-chart_4-15-0/Chart.yaml
- contrib-chart/reference-chart_4-15-0/README.md
- contrib-chart/reference-chart_4-15-0/app-values.yaml
- contrib-chart/reference-chart_4-15-0/env-values.yaml
- contrib-chart/reference-chart_4-15-0/pipeline-values.yaml
- contrib-chart/reference-chart_4-15-0/release-values.yaml
- contrib-chart/reference-chart_4-15-0/schema.json
- contrib-chart/reference-chart_4-15-0/secrets-test-values.yaml
- contrib-chart/reference-chart_4-15-0/templates/NOTES.txt
- contrib-chart/reference-chart_4-15-0/templates/_helpers.tpl
- contrib-chart/reference-chart_4-15-0/templates/configmap.yaml
- contrib-chart/reference-chart_4-15-0/templates/deployment.yaml
- contrib-chart/reference-chart_4-15-0/templates/externalsecrets.yaml
- contrib-chart/reference-chart_4-15-0/templates/generic.yaml
- contrib-chart/reference-chart_4-15-0/templates/hpa.yaml
- contrib-chart/reference-chart_4-15-0/templates/ingress.yaml
- contrib-chart/reference-chart_4-15-0/templates/keda-autoscaling.yaml
- contrib-chart/reference-chart_4-15-0/templates/metrics-service-monitor.yaml
- contrib-chart/reference-chart_4-15-0/templates/poddisruptionbudget.yaml
- contrib-chart/reference-chart_4-15-0/templates/pre-sync-job.yaml
- contrib-chart/reference-chart_4-15-0/templates/prometheusrules.yaml
- contrib-chart/reference-chart_4-15-0/templates/secret.yaml
- contrib-chart/reference-chart_4-15-0/templates/service.yaml
- contrib-chart/reference-chart_4-15-0/templates/serviceaccount.yaml
- contrib-chart/reference-chart_4-15-0/templates/servicemonitor.yaml
- contrib-chart/reference-chart_4-15-0/templates/sidecar-configmap.yaml
- contrib-chart/reference-chart_4-15-0/test_values.yaml
- contrib-chart/reference-chart_4-15-0/values.yaml
Signed-off-by: Kunal Verma <vkunal321@gmail.com>
Adds a Deployment Helm-chart
Fixes #2389 
I tested the chart locally with - `helm template --debug . -f test_values.yaml`
Here is the output file - [output.txt](https://github.com/devtron-labs/devtron/files/9635452/output.txt)
> Feat: Adding a Deployment Helm-chart

- api/restHandler/AppListingRestHandler.go
- util/k8s/k8sApplicationService.go
Fixed the access denied issue while fetching urls of service and manifest for non super-admins.
Fixes #2660
test-cases
```release-note
```
> Ingress Urls User level access Issue

- pkg/pipeline/WorkflowDagExecutor.go
Pre cd auto trigger not working when cd is set as manual trigger type. 
Fixes #2669 
```release-note
```
> fix: unblocked pre cd auto trigger in case of manual cd 

- internal/sql/repository/app/AppRepository.go
- pkg/bulkAction/BulkUpdateService.go
- pkg/bulkAction/bean.go
- pkg/cluster/repository/EnvironmentRepository.go
- specs/bulk-env-delete.yaml
Added support for bulk deleting pipelines and workflows by environment, app and project names.
Fixes #2692 
```release-note
```
> added support for giving names in wf bulk deletion req

- scripts/sql/98_alter_external_links.up.sql
External links can now be configured at cluster level and app level.
Fixes #1991 
> sql migration error fix

- docs/SUMMARY.md
- docs/user-guide/creating-application/app-details.md
- docs/user-guide/creating-application/overview.md
- docs/user-guide/global-configurations/external-links.md
-docs - The PR contains Documentation ONLY changes. 
-The changes are related to external link feature.
> docs: external-links-docs

- pkg/appClone/AppCloneService.go
Skip external ci webhook clone while app clone
Fixes #https://github.com/devtron-labs/devtron/issues/2665
```release-note
```
> Fix: Skip external ci webhook clone while app clone

- scripts/sql/84_alter_ci_cd_workflow.down.sql
fix: migration down sql for 84
it fails if we rollback
> fix: migration down sql for 84

- api/appbean/AppDetail.go
- pkg/chart/ChartService.go
- pkg/pipeline/PropertiesConfig.go
Removed required validation check for deployment template.
Fixes #2714 
```release-note
```
> fix: removed required validation for deployment template

- docs/user-guide/creating-application/workflow/ci-pipeline.md
- docs/user-guide/global-configurations/authorization/api-tokens.md
docs - The PR contains Documentation ONLY changes for webhook CI feature.
> docs: webhook ci documentation updates

- api/bean/GitOpsConfig.go
- internal/sql/repository/GitOpsConfigRepository.go
- internal/util/ChartService.go
- internal/util/GitService.go
- internal/util/GitServiceGitlab.go
- pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
- pkg/appStore/deployment/service/InstalledAppService.go
- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
- pkg/chart/ChartService.go
- pkg/gitops/GitOpsConfigService.go
- pkg/pipeline/PipelineBuilder.go
- scripts/sql/99_alter_gitop_config.down.sql
- scripts/sql/99_alter_gitops_config.up.sql
Reverts devtron-labs/devtron#2738
> Revert "feat: added BE support for allowing insecure tls connection in gitOps"

- charts/devtron/templates/NOTES.txt
- charts/devtron/templates/notifier.yaml
Updated notes and labels for new release
> feat: Updated notes and labels for new release

- docs/SUMMARY.md
- docs/user-guide/creating-application/deployment-template.md
- Link directing to GitHub page fixed.
> docs: deployment template doc

- docs/SUMMARY.md
- docs/setup/install/install-devtron.md
- docs/setup/install/uninstall-devtron.md
- Install Devtron - minor correction
- Uninstall Devtron command - minor correction
> docs: install command corrected

- docs/user-guide/global-configurations/docker-registries.md
- Broken Links fixed in https://docs.devtron.ai/global-configurations/docker-registries for v0.6.
> docs: broken links fixed in doc v0.6

- docs/FAQs/devtron-troubleshoot.md
Updated devtron admin password reset doc
> docs: Updated devtron admin password reset doc

- docs/FAQs/devtron-troubleshoot.md
- This part of container registries "https://docs.devtron.ai/global-configurations/docker-registries#how-to-resolve-if-deployment-status-shows-failed-or-degraded" is added in the Troubleshooting section and removed from Container Registries.
> docs: added deployment status shows failed or degraded in troubleshooting section

- docs/user-guide/global-configurations/cluster-and-environments.md
- Updated commands for K8s and microk8s clusters server URL.
> docs: updated cluster server url

- scripts/sql/106_sonarqube_plugin_polling.down.sql
- scripts/sql/106_sonarqube_plugin_polling.up.sql
Fixes #2847
```release-note
- Users will have the option to use the sonar properties file from the source code
- Now users can configure whether they want to quit the build based on the sonar analysis report.
```
> feat: Sonarqube polling script update

- api/restHandler/CoreAppRestHandler.go
app create api gives error if chart version is different for any of the environment override from global deployment template
Fixes #2850  
```release-note
```
> fix: app create api bug fix if chart ref is different

- scripts/sql/106_sonarqube_plugin_polling.up.sql
> fix: updated the description in sonarqube migration

- docs/SUMMARY.md
- docs/user-guide/creating-application/eso/README.md
- docs/user-guide/creating-application/eso/aws-eso.md
- docs/user-guide/creating-application/secrets.md
> docs: updated aws external secret doc

- pkg/cluster/ClusterService.go
- specs/cluster_api_spec.yaml
When we click on the Resource Browser tab, there is no information about the cluster i.e if the cluster is active or has died on the upfront so that user can see it on the home page. So the error in connecting with the cluster is not being sent int hte api response for the frontend to handle.
```release-note
```
> fix: cluster not reachable handling

- docs/SUMMARY.md
- docs/user-guide/creating-application/container-registry-override.md
- docs/user-guide/global-configurations/docker-registries.md
- Target platform override option updated.
> docs: updated target platform

- pkg/app/AppService.go
- pkg/pipeline/CdHandler.go
Updated logic for adding health status timeline for gitOps pipelines. Instead of checking sync.status in application object, updated using operationState.Phase for marking kubectl apply synced complete and then health status timeline.
Fixes #2889 
```release-note
```
> task: updated logic for adding health status timeline

- docs/SUMMARY.md
- docs/user-guide/create-application.md
- docs/user-guide/creating-application/overview.md
- Manage tags
- Create app (propagate tags)
> docs: added manage tags

- charts/devtron/README.md
> docs: Updated README.md file for Devtron chart

- docs/setup/install/install-devtron-with-cicd-with-gitops.md
- docs/setup/install/install-devtron-with-cicd.md
> docs: removed command to install a particular version of Devtron

- docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
- docs/setup/install/ingress-setup.md
- docs/setup/install/install-devtron-with-cicd-with-gitops.md
- docs/setup/install/install-devtron-with-cicd.md
- docs/setup/install/install-devtron.md
- Added annotation in ingress yaml file.
- Devtron less than v0.6.0, details for credentials are made collapsible.
> docs: minor updates ingress

- pkg/pipeline/PipelineBuilder.go
Issues On deleting cd pipeline which have no deployment app created, 404 for app status, trying to delete app status which is not present till deployment app created.  made check there.
Fixes #
```release-note
```
> fix: cd pipeline delete, 404 issue

- Dockerfile
- DockerfileEA
- api/connector/Connector.go
- util/k8s/k8sApplicationRestHandler.go
Added close to stream and moved from scanner to reader for log stream fetch. Also, downgraded go version to 1.18.
Fixes #2947 
```release-note
```
> fix: k8s log stream cpu issue

- docs/setup/configurations/configurations-overview.md
- docs/setup/install/ingress-setup.md
URL at these page are not correctly redirecting to their destination.
https://docs.devtron.ai/configurations-overview 
Intention of yaml file 
metadata:
annotations: nginx.ingress.kubernetes.io/app-root: /dashboard
Fixes #
```release-note
```
> docs: Some correction in Documentation at install devtron/ configuration / ingress setup

- api/appStore/InstalledAppRestHandler.go
- api/restHandler/ChartGroupRestHandler.go
- internal/sql/repository/app/AppRepository.go
- pkg/appStore/deployment/repository/ChartGroup.go
- pkg/appStore/deployment/service/ChartGroupService.go
Added check so that user cannot create chart group with mentioned condition.
Create chart group with name 'ch' or 'cha' or 'char', i.e. less than 5 characters.
Try to create one more chart group with same name that you used earlier.
User can't deploy multiple instances of charts with duplicate name.
Fixes https://github.com/devtron-labs/devtron/issues/1290
Fixes https://github.com/devtron-labs/devtron/issues/1289
```release-note
```
> fix: duplicate name in charts and chart Group

- api/restHandler/AppListingRestHandler.go
- pkg/app/AppService.go
- pkg/bean/app.go
- pkg/bulkAction/BulkUpdateService.go
- pkg/pipeline/CdHandler.go
- pkg/pipeline/WorkflowDagExecutor.go
- util/NumberParserUtil.go
- wire_gen.go
> fix: helm deploy hibernate fix

- api/appbean/AppDetail.go
- api/restHandler/CoreAppRestHandler.go
- client/cron/CdApplicationStatusUpdateHandler.go
- pkg/app/AppService.go
- specs/app_create_api.yaml
Added support for deployment app type configuration support in app create api and separated cron time for helm pipeline from acd pipeline status fetch.
```release-note
```
> fix: added deployment app type support for app create api, separated cron time for helm app status update

- pkg/app/AppService.go
Updating condition for saving health timeline and status. 
Fixes #3004
```release-note
```
> fix: fixed condition for updating health timeline and status

- pkg/pipeline/PipelineBuilder.go
Updated userId for ci audit history. 
Fixes #3012
```release-note
```
> fi: fixed incorrect userId in ci audit entries

- pkg/sql/connection.go
Currently all queries are logged, with this PR we are introducing a feature to add a separate configuration for only logging queries which exceeds a threshold duration 
```release-note
```
> feat: add configuration for only logging pg queries exceeding a threshold duration

- api/restHandler/AppListingRestHandler.go
fetching urls throwing bad request error 
Fixes #3066 
```release-note
```
> fix: urls pipeline fetching bug fix

- pkg/pipeline/PipelineBuilder.go
For each particular artifact card shown in Select Image and Rollback section, now we are going to show form which git branch and repo the artifact was prepared.
Fixes #
1. Make a workflow with cd configured, now click on Select Image/ Rollback the api response, previously the branch name was not coming from the backend, but after the fix the branch name is also coming, for a particular cd-pipeline.
2. tested by looking into api response of diff cd-workflows configured from diff branches, the branch data was coming as correct.
```release-note
```
> feat: branch name field added in API response for a cd Artifact material

- client/argocdServer/k8sClient.go
- pkg/app/AppService.go
- pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
- scripts/argo-assets/APPLICATION_TEMPLATE.JSON
Use cluster `destination.name` instead of `destination.server` in Argocd application object to extend cluster portability.
Fixes #2378 
For testing merged this branch to demo_latest branch and checked the changes on demo
Present
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: guestbook
namespace: argocd
spec:
project: default
source:
repoURL: https://github.com/argoproj/argocd-example-apps.git
targetRevision: HEAD
path: guestbook
destination:
server: https://kubernetes.default.svc
namespace: guestbook
```
Proposed
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: guestbook
namespace: argocd
spec:
project: default
source:
repoURL: https://github.com/argoproj/argocd-example-apps.git
targetRevision: HEAD
path: guestbook
destination:
name: …
```
> feat - Use cluster-name instead of server url in Argo cd application objects 

- pkg/pipeline/PipelineStageService.go
- pkg/pipeline/bean/pipelineStage.go
- pkg/pipeline/bean/workFlowRequestBean.go
- pkg/pipeline/repository/PipelineStageRepository.go
- scripts/sql/120_trigger_post_ci_if_ci_fail.down.sql
- scripts/sql/120_trigger_post_ci_if_ci_fail.up.sql
Option to run post-ci scripts even if build fails
Fixes #3061    
```release-note
```
> feat: Option to run post-ci scripts even if build fails

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
- vendor/modules.txt
Upgrade common-lib dependency
New environment variable introduced:
-   NATS_CONSUMER_CONFIG with default value of `{\"ackWaitInSecs\":3600}`
Tested on demo cluster and confirmed NATs related configuration changes
> chore: upgrade common-lib dependency

- api/cluster/EnvironmentRestHandler.go
- pkg/pipeline/WorkflowDagExecutor.go
Fixes https://github.com/devtron-labs/devtron/issues/3100
```release-note
```
> fix: cd metrics nil ptr fix

- pkg/app/AppService.go
Updated condition for getting/adding kubectl apply synced timeline.
```release-note
```
> fix: updated condition for adding kubectl apply synced timeline

- internal/middleware/instrument.go
- pkg/sql/connection.go
Expose pg query metrics to prometheus
- PG_EXPORT_PROM_METRICS - Flag to enable/disable pg query metrics
NO
```release-note
```
> feat: export pg query metrics to prometheus

- client/cron/CdApplicationStatusUpdateHandler.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- internal/sql/repository/pipelineConfig/mocks/PipelineRepository.go
- pkg/app/AppService.go
- pkg/pipeline/CdHandler.go
Restricted deployment status updation cron to get pipelines(not having terminal status and) that are deployed within some hours. Exposed environment variable: `DEPLOY_STATUS_CRON_GET_PIPELINE_DEPLOYED_WITHIN_HOURS` (integer value, in hours; default value=12) to configure if needed.
```release-note
```
> task: restricted deployment status updation cron to fetch pipelines deployed within hours

- pkg/pipeline/CdHandler.go
Apps deployed with helm whose release were not created are in `Progressing` state indefinitely.
Fixes #3136 
NO
```release-note
```
> fix: apps in progressing state indefinitely

- internal/sql/repository/app/AppRepository.go
onlyDevtronCharts flag changed type from boolean to integer
Fixes #
```release-note
```
> fix: onlyDevtronCharts flag changed type from boolean to integer

- api/helm-app/HelmAppService.go
- internal/util/K8sUtil.go
- pkg/appStore/deployment/service/InstalledAppService.go
This  PR aims to fix the notes.txt generation error (as shown below) when charts require special KubeVersion.
Fixes [AB2520](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2520)
1. I have done testing this via image deployment on vm.
2. I have checked for all possible test cases.
Test cases are:-
a.deployed  helm chart when no apps is present.
b. deployed  same helm chart again when above app  is present.
c.deployed helm chart via gitOps.
4. I have also done testing by applying multiple breakpoint for checking data is coming or not.
> fix:notes.txt throws error when charts require special KubeVersion

- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
- pkg/app/AppListingViewBuilder.go
Previously we had an option of only sorting according to the app-name and now we are adding the feature of sorting according to the deployed time.In the case of ascending order we will get the latest deployed apps first and in case of descending order we will get the latest deployed apps at last.And in the applist the ,for a particualr app the latest deployed app shoukd be displayed in the applist.
Fixes [#AB2358](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2358)
- 1.I have created various apps with various at various instances and sorted them according to deployed time.
- …
> feat:Sorting applist according to deployed time

- api/appStore/InstalledAppRestHandler.go
- api/helm-app/HelmAppService.go
- api/restHandler/AppListingRestHandler.go
- internal/middleware/instrument.go
- internal/sql/repository/AppListingRepository.go
- pkg/app/AppListingService.go
- pkg/appStore/deployment/service/InstalledAppService.go
Show the timer/counter metrics for App List using Prometheus.
Fixes: #https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2537
Github issue: https://github.com/devtron-labs/devtron/issues/3022
> feat: Add timer telemetry for App List

- api/restHandler/app/BuildPipelineRestHandler.go
- internal/sql/repository/pipelineConfig/CiPipelineMaterial.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/PipelineBuilder.go
Handled nil pointer access for pipeline deletion, added updation with not null for ci pipeline materials update method.
Fixes #3198
```release-note
```
> fix  - handled nil pointer access, fixed not null constraint for git material deletion

- pkg/dockerRegistry/DockerRegistryIpsConfigService.go
…or type
In Image pull secret service, type assertion was not handled which resulted into causing nil pointer panic, 
Fixes #
```release-note
```
> fix: handled case for failed type assertion

- api/router/pubsub/CiEventHandler.go
- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
We were fetching cd workflow runners by using appId and envId but were not checking pipeline deleted status. Updated query to get runners for active pipeline only.
```release-note
```
> fix: updated query for getting workflow runner by appId and envId for active pipelines only

- manifests/yamls/gitsensor.yaml
in manifest/yamls/gitsensor.yaml 
the indentation of initcontainer in wrong which is fixed in branch having tag: v0.6.114
> fix: git sensor initContainer indentation fix

- pkg/pipeline/PipelineBuilder.go
Added force deletion check in case of error when deleting helm deployed cd pipeline.
Fixes #3244 
```release-note
```
> fix: helm pipeline force delete check update

- pkg/sso/SSOLoginService.go
SSO Login credentials are sent null to secret if we save after obfuscation
Fixes #3246 
> fix: SSO Login credentials are sent null to secret if we save after obfuscation

- pkg/pipeline/DeploymentConfigService.go
pipeline strategy is not created for CronJob and Job Apps, added empty check.
Fixes #3247 
```release-note
```
> fix: Pipeline strategy empty check

- scripts/sql/129_git_sensor_node_sharding.down.sql
- scripts/sql/129_git_sensor_node_sharding.up.sql
> feat: add sharding sql scripts

- docs/user-guide/creating-application/workflow/ci-pipeline.md
> docs: cluster and environment url fix

- docs/FAQs/devtron-troubleshoot.md
> docs: devtron terminal connection timeout issue on gke cluster

- pkg/bulkAction/BulkUpdateService.go
- pkg/bulkAction/bean.go
Added option to set invalidate cache in bulk build API.
Fixes #3318 
```release-note
```
> fix: Invalidate cache configure bulk build

- internal/sql/repository/chartConfig/PipelineConfigRepository.go
- pkg/pipeline/PipelineBuilder.go
Fixes #3327
```release-note
```
> fix: deployment strategy no visible in build and deploy page

- scripts/devtron-reference-helm-charts/deployment-chart_1-2-0/README.md
- scripts/devtron-reference-helm-charts/deployment-chart_1-2-0/schema.json
- scripts/devtron-reference-helm-charts/deployment-chart_1-2-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_1-2-0/values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/README.md
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/schema.json
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/test_values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/values.yaml
Title: Add support for particular keys in rollout & deployment template cm/secret [Ref 4 18 0]
types: feat
feat: Add support for particular keys in rollout & deployment template cm/secret [Ref 4 18 0]
Added 2 fields that use to add EnvVariablesFrom SecretKeys and ConfigMapKey.
```
EnvVariablesFromSecretKeys: []
EnvVariablesFromCongigMapKeys: []
```
> feat: Add support for particular keys in rollout & deployment template cm/secret [Ref 4 18 0]

- scripts/sql/137_deployment_strategy_ref_mapping_removal.down.sql
- scripts/sql/137_deployment_strategy_ref_mapping_removal.up.sql
> fix: added deployment_strategy_ref_mapping_removal

- api/helm-app/HelmAppRestHandler.go
- api/helm-app/HelmAppService.go
- api/helm-app/bean.go
- pkg/app/AppService.go
- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
- pkg/webhook/helm/WebhookHelmService.go
Update method structure for updating application through kubelink apis. Renamed constants with better meaning.
```release-note
```
> task: changes for kubelink update application requests

- client/cron/CdApplicationStatusUpdateHandler.go
- internal/middleware/instrument.go
- pkg/pipeline/CdHandler.go
Made pipeline status update crons skip if old cycle is not completed. 
```release-note
```
> enhancement: made pipeline status crons cascading

- api/sso/SsoLoginHandler.go
whenever we create or update an sso login service the created by and updated by fields are not getting updated and are stored as null.
Fixes #[#AB2736](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2736)
```release-note
```
> fix: updated_by and created_by fields not getting updated in database for sso login services

- api/appStore/AppStoreStatusTimelineRestHandler.go
- pkg/app/status/PipelineStatusTimelineService.go
Deployment triggered time was not showing in case of pre-deployed helm apps, thsis pr fixes that issue
Fixes #
- tested by deploying my changes on demo cluster
```release-note
```
> fix: deployment triggered time handling for pre deployed apps

- pkg/appClone/AppCloneService.go
- pkg/pipeline/PipelineBuilder.go
Fixes #3398
```release-note
```
> fix: build-context-git-material is not being set for cloned apps

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
With the API optimization some APIs weren't replaced in devtron without cicd mode which caused the issue
Fixes #3434
> fix: 404 not found in devtron without cicd app list page

- api/router/pubsub/ApplicationStatusHandler.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- internal/sql/repository/pipelineConfig/mocks/PipelineRepository.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/PipelineBuilder.go
Audit log info for cd pipeline delete requests was not updating the user who did the action. Updated those fields in the db.
```release-note
```
> fix: updated audit info for cd pipeline delete req

- docs/user-guide/creating-application/eso/aws-eso.md
> docs: ESO AWS secrets manager using clustersecretstore

- internal/sql/repository/security/ImageScanResultRepository.go
- pkg/module/ModuleService.go
Fixes #
Enable Module Api for All users before it was just for oss users.
```release-note
```
> fix: enable api for all users for module

- docs/user-guide/global-configurations/cluster-and-environments.md
> docs: adding clusters on devtron using kubeconfig

- api/restHandler/CoreAppRestHandler.go
Panic handling for empty error in response writer and fixed deployment template override creation for workflow create api.
Fixes #3513
```release-note
```
> fix: app workflow creation api panic and app metrics update issue

- pkg/app/AppService.go
- util/helper.go
HPA handling for keda and fullnameOverride and nameOverride
Fixes https://github.com/devtron-labs/devtron/issues/3445
```release-note
```
> fix: HPA support for keda autoscaling and fixes for nameOverrides

- api/restHandler/CoreAppRestHandler.go
- pkg/appWorkflow/AppWorkflowService.go
Introduced an optional query param `workflowName` for getting specific workflow detail in an app. If not provided workflow will be fetched using appId only.
Fixes #3534 
```release-note
```
> task: updated workflow name provision in app workflow api

- docs/user-guide/creating-application/deployment-template/rollout-deployment.md
- docs/user-guide/creating-application/workflow/cd-pipeline.md
> docs: prerequisite for keda autoscaling using deployment template

- pkg/pipeline/PipelineBuilder.go
Issue:  we are fetching dashboard-cm to read a variable,but the name of the variable is not always same.this will cause error if the CM of dashboard is different(not devtron-cm).
Fix: now maintaining the variable in devtron-cm that is being fetched from dashboard-cm ,which will resolve the issue for now. later this variable will be removed from dashboard-cm and communicated to dashboard from orchestrator.
Fixes #
```release-note
```
> fix: getting force_security_scan value from devtron-cm

- pkg/cluster/EnvironmentService.go
- pkg/pipeline/PipelineBuilder.go
- pkg/pipeline/PipelineBuilder_test.go
> fix: handled no config exists case for enforced deployment app type

- scripts/devtron-reference-helm-charts/deployment-chart_4-18-0/templates/deployment.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/templates/deployment.yaml
- scripts/sql/152_deployment_chart_ref_4-18-0.up.sql
- scripts/sql/153_chart_ref_4-18.up.sql
> fix: removed extra condition in ref-chart 4.18

- util/k8s/k8sApplicationRestHandler.go
Fixes #3603 
tested by checking that secret is obfuscated or not 
```release-note
```
> fix: obfuscate secret for devtron/helm apps

- pkg/attributes/AttributesService.go
Deployment enforcement config not getting saved for first time in database.
Fixes #Deployment type enforcement config not getting saved for first time
```release-note
```
> fix: Deployment enforcement config save err

- pkg/plugin/GlobalPluginService.go
- pkg/plugin/bean.go
- pkg/plugin/repository/GlobalPluginRepository.go
Fixes #3633
```release-note
```
> task: updated plugin list to include i/o vars, refactored detail get api 

- client/cron/CdApplicationStatusUpdateHandler.go
- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
- internal/sql/repository/pipelineConfig/PipelineRepository.go
- pkg/pipeline/CdHandler.go
Fixes #
To reduce CPU load due to the DB query 
* select only required columns
* only get pipelines deployed within a fixed number of hours(configured) to ignore old stuck pipelines
tested on a local cluster deploying application 
```release-note
```
> Fix: optimizing when querying DB to get running Helm deployments

- api/appStore/AppStoreStatusTimelineRestHandler.go
- api/restHandler/PipelineStatusTimelineRestHandler.go
- pkg/app/status/PipelineStatusTimelineService.go
Added a query param in fetch deployment status  timeline api, saving multiple db calls where the data is not needed on UI
Fixes #
```release-note
```
> fix: optimized fetch deployment status timeline api

- docs/user-guide/global-configurations/cluster-and-environments.md
> docs: removed new line from token generation command

- pkg/k8s/application/k8sApplicationService.go
Fixes #3758 
```release-note
```
> fix: server version check for ephemeral suport bug fix

- pkg/user/UserService.go
Fixes #3685 
```release-note
```
> perf:  user update api concurrent request handling

- pkg/user/UserService.go
Fixes #3771
```release-note
```
> fix: updated user flow update api unlock condition

- pkg/pipeline/CiService.go
Fixes #3672
```release-note
```
> fix: remove use-buildx flag to use k8s buildx driver

- pkg/appStore/deployment/service/InstalledAppService.go
- pkg/util/TokenCache.go
Fixes #3789
```release-note
```
> perf: hibernate check optimisation

- docs/SUMMARY.md
- docs/user-guide/creating-application/eso/aws-eso.md
- docs/user-guide/creating-application/eso/hashicorp-eso.md
> doc: HashiCorp external secret operator

- docs/user-guide/security-features.md
> doc: security feature doc

- docs/user-guide/deploying-application/triggering-ci.md
> doc: ci-trigger documentation update

- docs/SUMMARY.md
- docs/user-guide/global-configurations/mandatory-tags.md
- docs/user-guide/global-configurations/tags-policy.md
> doc: mandatory tags feature

- docs/user-guide/creating-application/workflow/cd-pipeline.md
- docs/user-guide/deploying-application/triggering-cd.md
- docs/user-guide/global-configurations/user-access.md
> doc: manual image approval

- docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
- docs/setup/install/faq-on-installation.md
- docs/setup/install/install-devtron-helm-3.md
- docs/setup/install/install-devtron-with-cicd-with-gitops.md
- docs/setup/install/install-devtron-with-cicd.md
- docs/setup/install/install-devtron.md
Docs: Include the purpose of admin login in Devtron installation doc + FAQ
> doc: include the purpose of admin login in Devtron installation doc + FAQ

- pkg/appStore/deployment/repository/ChartGroupEntry.go
These changes fix the issue where users were unable to delete chart group with existing helm chart and had to delete all existing helm chart one by one in order to delete the chart group.
Fixes #3460
```release-note
```
> fix: Unable to delete chart group with existing helm chart

- docs/user-guide/creating-application/deployment-template/deployment.md
- docs/user-guide/creating-application/deployment-template/rollout-deployment.md
- scripts/devtron-reference-helm-charts/deployment-chart_1-0-0/README.md
- scripts/devtron-reference-helm-charts/deployment-chart_1-0-0/app-values.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_1-1-0/README.md
- scripts/devtron-reference-helm-charts/deployment-chart_1-1-0/app-values.yaml
- scripts/devtron-reference-helm-charts/deployment-chart_4-18-0/README.md
- scripts/devtron-reference-helm-charts/deployment-chart_4-18-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-16-0/README.md
- scripts/devtron-reference-helm-charts/reference-chart_4-16-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-17-0/README.md
- scripts/devtron-reference-helm-charts/reference-chart_4-17-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/README.md
- scripts/devtron-reference-helm-charts/reference-chart_4-18-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_5-0-0/README.md
- scripts/devtron-reference-helm-charts/reference-chart_5-0-0/app-values.yaml
- scripts/devtron-reference-helm-charts/reference-chart_5-0-0/env-values.yaml
Updated Devtron reference helm charts with podDisruptionBudget to show in README as well in Devtron UI
```release-note
Users using Rollout chart - 4-16-0, 4-17-0, 4-18-0 will now be able to see the podDisruptionBudget field in the Deployment template.
```
> doc: Update devtron-reference charts with pdb

- api/chartRepo/ChartRepositoryRestHandler.go
- pkg/chartRepo/ChartRepositoryService.go
- pkg/chartRepo/repository/ChartRepoRepository.go
Chart repo which is used to deploy helm app can be updated through postman, which should not happen.
Fixes #3455
```release-note
```
> fix: prevented chart updation when its in use

- pkg/app/AppService.go
Fixes #3783 
```release-note
```
> fix: deployment timelines fix for helm apps

- pkg/pipeline/PipelineBuilder.go
Fixes #3818
```release-note
```
> fix: added missing audit logs while deleting cd pipeline

- pkg/user/UserCommonService.go
Fixes #3825
```release-note
```
> fix: k8s permission and chart-group permission not getting deleted from orchestrator

- pkg/pipeline/CdConfig.go
- pkg/pipeline/CdWorkflowService.go
Fixes #3805 
```release-note
```
> fix: pre-cd pod not getting scheduled when node affinity is not present in external cluster.

- api/k8s/application/k8sApplicationRestHandler.go
- api/restHandler/AppListingRestHandler.go
- pkg/appStore/deployment/service/InstalledAppService.go
- pkg/k8s/K8sCommonService.go
- pkg/k8s/bean.go
- scripts/sql/166_webhook.down.sql
- scripts/sql/166_webhook.up.sql
Fixes #3829
```release-note
```
> fix: Port number fix in helm app

- .github/workflows/pr-issue-validator.yaml
added comments at relevant places
modified conditional logic to put label in case of invalid PR
Fixes #
```release-note
```
> chore: Update pr-issue-validator.yaml

- Makefile
- cmd/external-app/Makefile
Fixes #3853 
```release-note
```
> fix: Makefile correction

- pkg/appClone/AppCloneService.go
- pkg/pipeline/ConfigMapService.go
Fixes #3859 
```release-note
```
> fix: cloning app cmcs global boolean value fix

- pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
When a user has previously deployed any helm application and after that the user is deleted. Then post the user deletion  event the deployment history page of helm apps will break . It was Handled for devtron app where the deleted user is marked as anonymous but it is not handled  in helm apps. This PR will fix that issue
Fixes #3415 
```release-note
```
> fix: Helm app deployment history page breaking due to user details not found

- .github/workflows/azure-devops-issue-sync.yml
Adjusted github duplicate action threshold to 0.6
```release-note
```
> chore: adjust duplicate action threshold

- pkg/pipeline/CdHandler.go
This PR fixed the issue: If any app having pipe line with pre post CD and it is running healthy but if u again deploy the cd pipe line in devtron app then check the post CD status in App group
Fixes #3674 
```release-note
```
> fix: invalid post deployment status in App group

- internal/sql/repository/security/ImageScanDeployInfoRepository.go
- pkg/app/AppService.go
- scripts/sql/171_remove_index_image_scan_deploy_info_down.sql
- scripts/sql/171_remove_index_image_scan_deploy_info_up.sql
Fixes #3538 
For CD triggers in an app with multiple CD pipelines, data was being persisted for only app and first environment. The fix replaces the get call to fetch data on both app and env instead of just app and data flows separately for each environment
Tested manually for app with multiple CD with a repo containing vulnerabilities.
Banner was visible after a fresh trigger for all environments
```release-note
```
> fix: data not flowing into table ImageScanDeployInfo for triggers

- pkg/app/AppService.go
- pkg/gitops/GitOpsConfigService.go
- util/GlobalConfig.go
- wire_gen.go
Added an env variable to skip GitOps validation in Global configuration.
Fixes #3961
```release-note
```
> feat: added env variable to skip gitops validation on create/update

- pkg/appStore/deployment/service/AppStoreDeploymentService.go
- wire_gen.go
Running Deployment status of applications in chart groups is not synced. These changes fix the mentioned issue.
1: Create a chart group and add any 2 charts in the group .
2: deploy the chart group .
3: go to helm apps list page , you will see the apps you deployed though group .
4: delete those apps .
5: now again click on chart group , in running deployment section you can still see those apps you deleted .
6: click on delete icon of those apps , you will get warning no rows selected warning .
Expected : Apps should get removed from running deployment list of chart group
Fixes #
```release-note
```
> fix: Running Deployment status of applications in chart groups is not synced 

- pkg/pipeline/CiCdPipelineOrchestrator.go
- pkg/pipeline/CiConfig.go
Added **SKIP_CREATING_ECR_REPO** (defaults to false) env variable to configure ecr repo creation. If set true, then repo creation will not be tried and will be tried if set to false. 
Fixes #3965 
```release-note
```
> feat: added flag to configure ecr repo creation

- pkg/pipeline/WorkflowUtils.go
Instead of CI pod requests, limits were being set. Fixed that. 
Fixes #3983 
```release-note
```
> fix: ci pod request correction

- pkg/pipeline/WorkflowDagExecutor.go
For Post CD stage trigger, pipelineOverrideId was being sent instead of pipelineId causing post cd stage trigger to not work in automatic mode. 
Fixes #3985 
```release-note
```
> fix: pipelineOverride id being sent instead of pipelineId

- api/helm-app/HelmAppService.go
- api/helm-app/models/customErrors.go
- pkg/pipeline/PipelineBuilder.go
- util/k8s/K8sUtil.go
- util/k8s/K8sUtil_test.go
This pr aims at fixing the below issue:-
Create an env for namespace on devtron, and delete the namespace manually using kubectl.
Create a new cd-pipeline for the same environment and try to deploy it will fail as the namespace doesn't exist.
Now try to delete the cd-pipeline.
Fixes #3885 
tested the fix with multiple pipeline deploying the deleted namespace and then deleting the namespace with kubectl
- tested the fix with multiple pipeline deploying the deleted namespace and then deleting the namespace with kubectl
```release-note
```
> fix: not able to delete no-gitops cd pipeline fix

- pkg/variables/parsers/VariableTemplateParser.go
- pkg/variables/parsers/VariableTemplateParser_test.go
Fixes #4009 
The issue arose due to syntax conflict with HCL while parsing template for variables, which was in the format of %{some_value}
This syntax needed to be escaped before calling the parser so that HCL ignores this, since it was not intended by the user.
We made the current implementation of hcl parsing to also escape this format along with the already implemented escaping of the format @{some_value}
```release-note
```
> fix: Deployment Template HCL parsing with % keyword

- api/restHandler/AppListingRestHandler.go
Release status was being used in helm type cd pipeline but it breaks when a pipeline is migrated from gitOps to helm type and release is not created yet. 
Fixes #4017
```release-note
```
> fix: handled releaseNotExists case for helm type cd pipeline resource tree fetch

- pkg/pipeline/PipelineBuilder.go
In bulk trigger deploy service, there was one error check where nil error case was not handled. Handled that. 
Fixes #4031 
```release-note
```
> fix: handled error in bulk trigger deploy

- api/restHandler/AppRestHandler.go
- api/restHandler/bean/bean.go
- util/rbac/EnforcerUtil.go
The issue occurs when we have uppercase character in project or app Name and user doesn't have super admin access.
When we check the access of user we were not changing the name to lowercase.
Fixes #4042 
```release-note
```
> fix: The manager(non-admin user) of the application is unable to select a list of apps when assigning permissions.

- api/appbean/AppDetail.go
- api/restHandler/CoreAppRestHandler.go
- api/restHandler/app/BuildPipelineRestHandler.go
- pkg/pipeline/BuildPipelineConfigService.go
Adding support for creating Creating job using api "/orchestrator/core/v1beta1/application".
Fixes #4055 
test-cases
```release-note
```
> fix: ci job handling in app create api

- api/helm-app/HelmAppService.go
- pkg/bean/app.go
- pkg/pipeline/PipelineBuilder.go
Error message got changed in kubelink in recent release.
Fixes #4052 
```release-note
```
> fix: Deploying currently Active image using TriggerDeploy API from devtctl tool is broken

- api/appbean/AppDetail.go
- api/restHandler/CoreAppRestHandler.go
It bugs out when you hit workflow get API. Workflow GET api fetches the ci pipeline details and cd-pipeline details along with env overrides. But It doesn't fetches the CI pipeline override details. For example if container registry is overridden at ci-pipeline level then that would not be fetched.
Fixes #3671
All test are performed locally 
```release-note
```
> fix:Workflow GET API doesn't fetches the CI pipelines overrides and also remove sample from API

- docs/user-guide/global-configurations/okta.md
In Paid License or organization okta accounts /oauth2/default isn't enabled by default and the issuer url without /oauth2/default works for both organization as well as trial accounts as well as the recommended url for issuer
> doc: Fixed issuer url in okta docs

- pkg/variables/ScopedVariableService.go
- pkg/variables/utils/type-utils.go
Fixes #4011
```release-note
```
> feat: added deduction for system variables

- docs/SUMMARY.md
- docs/user-guide/creating-application/config-approval.md
doc: Contains documentation of **Protect Configuration** feature (Config Approval)
> docs: Config Approval Draft

- pkg/k8s/K8sCommonService.go
These changes correctly maps port list with service names in case of helm deployed applications
Fixes #4025 
```release-note
```
> fix: port service mapping

- docs/SUMMARY.md
- docs/user-guide/app-details/ephemeral-containers.md
- docs/user-guide/global-configurations/scoped-variables.md
doc: Contains documentation of Scoped Variables feature (Phase 1)
> docs: Scoped Variables Draft + Other Fixes (Ephemeral Doc Alignment)

- go.mod
- go.sum
- internal/sql/repository/CiArtifactsListingQueryBuilder.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/4248
```release-note
```
> fix: kubernetes events fix for resources

- scripts/sql/189_update_mvn_dependency_tracker_plugin.down.sql
- scripts/sql/189_update_mvn_dependency_tracker_plugin.up.sql
We had extented the Maven Dependency Tracker Plugin to skip the BuildTest.
> chore: update maven dependency tracker plugin

- scripts/sql/189_update_mvn_dependency_tracker_plugin.up.sql
This PR will change the plugin name from Dependency track for Maven & Gradle) to Dependency track for Maven & Gradle.
> chore: updating dependency tracker maven plugin name 

- go.mod
- go.sum
- pkg/pipeline/CdHandler.go
- pkg/pipeline/WorkflowDagExecutor.go
- vendor/modules.txt
DevtronApp Deployment Status update takes more time than expected.
Fixes https://github.com/devtron-labs/devtron/issues/4268
> fix: DevtronApp Deployment Status Fixed

- pkg/pipeline/CiHandler.go
Fixes #4270 
```release-note
```
> fix: No rows for rest config in case of Default namespace

- scripts/sql/193_copy_container_images_updated.down.sql
- scripts/sql/193_copy_container_images_updated.up.sql
fix: Added multi arc build support to copy container image plugin
Fixes https://github.com/devtron-labs/devtron/issues/4283
```release-note
```
> fix: updated copy container image plugin for multi arc build support

- internal/sql/repository/CiArtifactsListingQueryBuilder.go
- pkg/dockerRegistry/DockerRegistryIpsConfigService.go
- pkg/pipeline/AppArtifactManager.go
- pkg/pipeline/CiService.go
- pkg/pipeline/WebhookService.go
After enabling artifacts V2 flag, get material list API is breaking for external CI and job CI (Throwing error: `pg: no rows in result set`)
Fixes https://github.com/devtron-labs/devtron/issues/4290
Checklist:
```release-note
```
> fix: Get Artifacts list API is throwing pg no rows error 

- pkg/pipeline/AppArtifactManager.go
- pkg/pipeline/CiHandler.go
- pkg/pipeline/CiService.go
Fixes https://github.com/devtron-labs/devtron/issues/4297
```release-note
```
> fix: Job trigger throws error

- docs/user-guide/global-configurations/scoped-variables.md
Fix for image size in gitbook docs
> docs: img size fix

- pkg/cluster/EnvironmentService.go
- pkg/cluster/repository/EnvironmentRepository.go
Updated the sql query used in validating whether the namespace exists or not. Namespace is unique across a specific cluster and Environment name is unique across all cluster.
Fixes https://github.com/devtron-labs/devtron/issues/4329
```release-note
```
> fix: not able to add env in global configuration

- internal/sql/repository/pipelineConfig/PipelineRepository.go
- pkg/appWorkflow/AppWorkflowService.go
📜 Description
After changing deploymentType from argoCD to Helm or vice-versa and then triggering deployment from application groups breaks app details page, Build and Deploy page and workflow editor page for that particular application.
👟 Reproduction steps
Change the Application's Deploy Type from helm to argocd or vice-versa using devtctl tool.
Deploy the same application using application groups.
Go to the app details page, Build and Deploy page, or workflow editor page. All of them would be broken.
Fixes #4353
> fix: Inconsistent behaviour on deploying application from application group v/s devtron cli tool after changing deploymentType 

- internal/sql/repository/security/CveStoreRepository.go
- pkg/security/ImageScanService.go
Fix for CVE Policy search 
Fixes #4361
> fix:cve search 

- charts/devtron/Chart.yaml
- charts/devtron/templates/nats-server.yaml
**Remove the test hook annotation from devtron-nats-test-request-reply pod from nats-server.yaml .**
```release-note
```
> chore: Remove the annotation hook from devtron-nats-test-request-reply pod

- docs/user-guide/global-configurations/scoped-variables.md
The sample YAML file in the scoped variable doc had incorrect indentation, it has been fixed in this commit
> doc: Indentation fix in Scoped Variable Doc

- .gitbook.yaml
**Problem**:
The documentation URL in our tooltip (OCI) points to a non-existing page
**Solution**:
Tried adding a redirection in Gitbook (experimental)
> doc: Redirection added for OCI doc

- docs/user-guide/global-configurations/user-access.md
- docs/user-guide/jobs/workflow-editor-job.md
docs: Fix broken links in user-guide
Fixes #
```release-note
```
> docs: fix broken links

- pkg/pipeline/types/CiCdConfig.go
- pkg/pipeline/types/Workflow.go
> chore: share same nats url used by orchestrator

- config.md
- docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
- docs/setup/install/install-devtron-helm-3.md
- docs/setup/install/install-devtron-with-cicd-with-gitops.md
- docs/setup/install/install-devtron-with-cicd.md
- docs/setup/install/install-devtron.md
- docs/setup/install/installation-configuration.md
Description:
Refine the Helm installation process to ensure the latest version is installed, addressing an issue where an older version might be installed if the Helm repo is not updated. This modification includes adding the `helm repo update` command to refresh the repository before installation.
Changes:
- Previously: Helm repo was added, and installation was performed directly.
- Updated: Added `helm repo update devtron` command to ensure the latest version is fetched before installation.
```
helm repo add devtron https://helm.devtron.ai
helm repo update devtron
helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd \
--set installer.modules={cicd}
```
Additionally, the documentation now highlights the use of the `--reuse-values` flag during the helm …
> doc: Update Helm Installation Command

- charts/devtron/devtron-bom.yaml
- charts/devtron/values.yaml
Since argocd is not yet on the cluster at the time of installing Devtron, I'm trying to bootstrap Devtron using fluxcd v2. It installs on the cluster using regular helm just fine, but fluxcd validates the output in a stricter manner.
It complains of a duplicate key entry for RUN_HELM_INSTALL_IN_ASYNC_MODE.
In the kubelink.configs section values.yaml,  a default for RUN_HELM_INSTALL_IN_ASYNC_MODE  is defined as false. In [templates/kubelink.yam](https://github.com/devtron-labs/devtron/blob/bfa491b25e36c3b5dfb21d3e19f396fbebdcfa46/charts/devtron/templates/kubelink.yaml#L32-L36)l there is a conditional that appends that same key below, meaning in the rendered output it appears twice.
This causes fluxcd to throw the error. [This issue](https://github.com/fluxcd/helm-controller/issues/283) is …
> fix: Remove duplicate key value in helm chart for kubelink configs

- pkg/chartRepo/ChartRepositoryService.go
Fixes #4448 
```release-note
```
> fix: Manual sync job fix

- api/router/pubsub/ApplicationStatusHandler.go
- pkg/terminal/terminalSesion.go
handle argo delete event for charts and added socket config
Fixes #4465 
#3314 
```release-note
```
> fix: handle argo delete event for charts and added socket config

- pkg/appClone/AppCloneService.go
- pkg/pipeline/CiCdPipelineOrchestrator.go
For [linked ci, external ci, linked cd] cases, in app clone we were not setting ci build config data which is correct, but we were trying to access the same data in pipeline template creation without checking these types. The type was checked later when doing db operation. Moved the check before setting to avoid nil pointer panic.
Fixes #4520
```release-note
```
> fix: panic in app clone service for [linked ci, external ci, linked cd] cases

- internal/sql/repository/CiArtifactRepository.go
- pkg/pipeline/WorkflowDagExecutor.go
> Chore: updated ci_artifact.data_source migration condition

- .github/workflows/pr-issue-validator.yaml
This action is designed to check whether the SQL files located in the '/scripts/sql' directory are in the correct format, identify if there are any repeated files.
> chore: added sql-validator in git-hub action

- client/telemetry/TelemetryConfig.go
- client/telemetry/TelemetryEventClient.go
- client/telemetry/TelemetryEventClientExtended.go
- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/ProviderIdentifierService.go
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/alibaba.go
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/azure.go
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/digitalOcean.go
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/google.go
- vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/oracle.go
- vendor/modules.txt
Fixes #4594 
```release-note
```
> fix: implemented cache for storing cloud provider 

- .gitbook.yaml
As shown in the above snapshots, the link was pointing to a non-existing/old URL. Therefore, appropriate redirection has been added.
> doc: Redirection added for old SSO doc link

- api/restHandler/app/pipeline/status/PipelineStatusTimelineRestHandler.go
The Manual Sync API for deployment status is throwing nil pointer deference.
Fixes https://github.com/devtron-labs/devtron/issues/4677
```release-note
```
> fix: nil pointer issue in manual sync api

- .github/pull_request_template.md
> misc: Changed PR template

- api/chartRepo/ChartRepositoryRouter.go
Fixed chart-repos delete issue on Safari with an Error response `an EOF (Bad response)`. This issue was due to URL redirection from the browser.
Fixes https://github.com/devtron-labs/devtron/issues/4582
```release-note
```
> fix: chart repo delete routing

- go.mod
- go.sum
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
- vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
- vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
- vendor/modules.txt
upgrade common-lib version
Fixes #4713 
```release-note
```
> chore: nats common lib version upgrade

- docs/FAQs/devtron-troubleshoot.md
Have added the FAQ for the issue named: Git-sensor PVC- disk full 
Reason: The issue arises due to the limited storage of PVC. 
Solution Provided: The issue can be solved by increasing the size of the PVC.
> docs: Added the FAQ for the issue:Git-sensor PVC- disk full 

- pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
- pkg/appStore/util/util.go
- pkg/bean/app.go
- pkg/deployment/gitOps/git/commandManager/GitCliManager.go
Issues Fixed:
- It was caused by git CLI as we are storing the shortened git hash in the database; which fails to match in deployment status update flow.
- It is impacting helm apps install flow only as we perform that flow using git cli instead of (provider based APIs)
Fixes https://github.com/devtron-labs/devtron/issues/4727
```release-note
```
> fix: 28feb packet common bug fix

- api/restHandler/GitOpsConfigRestHandler.go
- client/argocdServer/ArgoClientWrapperService.go
- client/argocdServer/bean/bean.go
- pkg/app/ManifestPushService.go
- pkg/appStore/installedApp/repository/InstalledAppRepository.go
- pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
- pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
- pkg/chart/ChartService.go
- pkg/chart/bean.go
- pkg/chart/gitOpsConfig/DevtronAppGitOpsConfigService.go
- pkg/chartRepo/repository/ChartsRepository.go
- pkg/deployment/gitOps/git/GitOperationService.go
- pkg/deployment/gitOps/git/GitOpsHelper.go
- pkg/deployment/gitOps/git/GitServiceBitbucket.go
- pkg/pipeline/AppDeploymentTypeChangeManager.go
- pkg/pipeline/DeploymentPipelineConfigService.go
- util/retryFunc/RetryFunction.go
- wire_gen.go
> fix: review comment fixes for user defined GitOps repo url

- pkg/workflow/dag/WorkflowDagExecutor.go
- vendor/modules.txt
- wire_gen.go
Fixes #4740
```release-note
```
> fix: customTagService missing in workflowdagexec

- api/restHandler/app/workflow/AppWorkflowRestHandler.go
Fixes #4777 
```release-note
```
> fix: Not able to see workflow name in case of project with uppercase letters

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
This PR fixed the issue: Helm installed deployments stucked in queued for Devtron apps
Fixes https://github.com/devtron-labs/devtron/issues/4843
```release-note
```
> fix: helm deployments stucked in queued for devtron apps

- docs/user-guide/creating-application/deployment-template/deployment.md
> doc: Added EnvVariablesFromFieldPath in Deployment Template

- client/argocdServer/ArgoClientWrapperService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
Fixes https://github.com/devtron-labs/devtron/issues/4866
```release-note
```
> fix: update argo app repo url in patch

- pkg/eventProcessor/in/DeployedApplicationEventProcessorService.go
- wire_gen.go
fix: injected app-serveice dependency into DeployedApplicationEventProcessor service
Fixes https://github.com/devtron-labs/devtron/issues/4877
```release-note
```
> fix: injected app-serveice dependency into DeployedApplicationEventProcessor service

- internal/sql/repository/NotificationSettingsRepository.go
- internal/sql/repository/WebhookNotificationRepository.go
- pkg/notifier/WebhookNotificationService.go
- pkg/notifier/WebhookNotificationService_test.go
- scripts/sql/236_image_scan_notification.down.sql
- scripts/sql/236_image_scan_notification.up.sql
Migration changes for notification 
Fixes https://github.com/devtron-labs/devtron/issues/4725
```release-note
```
> chore: migration support for notification db changes

- scripts/sql/237_devtron_ci_trigger_plugin.up.sql
Fixes #4830 
Fixed the error while fetching the app name and pipeline name from CI_CD_EVENT variable
> fix: Corrected the error of fetching app name and pipeline name from CI_CD_EVENT

- client/events/EventClient.go
- internal/middleware/instrument.go
- pkg/clusterTerminalAccess/UserTerminalAccessService.go
- pkg/k8s/K8sCommonService.go
- pkg/terminal/constants.go
- pkg/terminal/terminalSesion.go
This Pr aims at several performance fixes related to GCing and channels and also exposing prometheus metrics for all terminal session activities.
Fixes #4883 
```release-note
```
> perf: memory optimizations and prom metrics on terminal session exposed

- scripts/sql/238_artifacts_promotion.up.sql
Fixes #4995 
```release-note
```
> fix: image-approval-migartion fix

- api/restHandler/app/appList/AppListingRestHandler.go
This issue was happening because we were fetching the app details of a helm app for an environment in which there was not even a single deployment triggered yet. Need to handle it from the code side by putting a check and not calling the GetAppDetail function in this case.
Fixes #5008
> fix: Kubelink Requests getting Failed for gRPC method GetAppDetails

- scripts/sql/241_devtronJobTrigger.down.sql
- scripts/sql/241_devtronJobTrigger.up.sql
> feat: Plugin to trigger Devtron Job

- api/helm-app/service/HelmAppService.go
- pkg/appStore/installedApp/service/AppStoreDeploymentService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
- pkg/pipeline/DeploymentPipelineConfigService.go
The issue was resolved by implementing a validation mechanism in the Devtron dashboard to check the existence of the namespace before creating a Continuous Deployment (CD). This validation step ensures that CD creation is blocked if the specified namespace does not exist, preventing the creation of deployments that would otherwise fail due to non-existent namespaces. This enhancement improves the reliability and stability of the CD process by preemptively identifying and preventing potential deployment failures caused by invalid namespace references.
Fixes #4959 
```release-note
```
> fix:handled namespace case if deleted by kubectl

- scripts/sql/245_remote_connection_config.down.sql
- scripts/sql/245_remote_connection_config.up.sql
Fixes #5107
```release-note
```
> feat: migration update for remote connection config

- docs/user-guide/resource-browser.md
- Section created in resource browser doc
- Added snaps and gifs wherever required
- Included sample kubeconfig content
- Linked to official kubectl docs wherever required
- Added session token method for non-superadmins
> doc: Added kubectl port-fwd section in RB

- go.mod
- go.sum
- scripts/sql/249_alter_trivy_fix.up.sql
Fixes https://github.com/devtron-labs/devtron/issues/5165
```release-note
```
> fix: trivy scan step command fix

- pkg/app/AppCrudOperationService.go
- pkg/app/helper.go
This pr fixes the issue when there are wrong regex present for extra labels that we are propagating. For Old data present on clients project names were having spaces hence k8s was unable to pass the label validation check. 
Fixes #5219 
```release-note
```
> fix: extra labels propagation based on k8s label regex matching

- pkg/appClone/AppCloneService.go
Fixes #5190
```release-note
```
> fix: App clone config map fix

- scripts/sql/256_custom_deployment_schema.down.sql
- scripts/sql/256_custom_deployment_schema.up.sql
Fixes #5011 
```release-note
```
> feat: chart ref schema db migration

- scripts/sql/260_gitops_ssh.down.sql
- scripts/sql/260_gitops_ssh.up.sql
Fixes #5140 
```release-note
```
> chore: migration for gitops config

- scripts/sql/261_alter_image_scan_execution_history.down.sql
- scripts/sql/261_alter_image_scan_execution_history.up.sql
- scripts/sql/262_alter_installed_app.down.sql
- scripts/sql/262_alter_installed_app.up.sql
- scripts/sql/263_code_scan_plugin.down.sql
- scripts/sql/263_code_scan_plugin.up.sql
- scripts/sql/264_image_scan_plugin.down.sql
- scripts/sql/264_image_scan_plugin.up.sql
Fixes https://github.com/devtron-labs/devtron/issues/5407
```release-note
```
> feat: new scripts added for rescan sbom support , helm manifest scan flag and git container links 

- docs/SUMMARY.md
- docs/setup/upgrade/README.md
- docs/setup/upgrade/devtron-upgrade-0.6.x-0.7.x.md
- Entry created in SUMMARY.md
- Entry created in upgrade/README.md
- Snapshot added
> doc: Added migration steps for 0.6 to 0.7 upgrade

- client/argocdServer/ArgoClientWrapperService.go
- pkg/appStore/installedApp/service/AppStoreDeploymentService.go
- pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
Fixes #5429 
```release-note
```
> fix: repo url and name handling with argocd

- api/restHandler/ImageScanRestHandler.go
- pkg/pipeline/DeploymentPipelineConfigService.go
> fix: external ci creation fix

- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
> fix: post cd auto trigger not working for helm type deployments

- pkg/pipeline/CiService.go
Fixes https://github.com/devtron-labs/devtron/issues/5515
```release-note
```
> feat: External Ci with Job giving run time param externalCiArtifact

- scripts/sql/269_alter_image_scan_execution_result_.down.sql
- scripts/sql/269_alter_image_scan_execution_result_.up.sql
Fixes #5576 
```release-note
```
> fix: add if not exists in migration script for avoiding any errors while rerunning scripts

- pkg/pipeline/BuildPipelineConfigService.go
- pkg/pipeline/bean/CiPipeline/CiBuildConfig.go
Fixes https://github.com/devtron-labs/devtron/issues/5077
```release-note
```
> fix: default PipelineType given

- pkg/k8s/informer/K8sInformerFactory.go
- wire_gen.go
Fixes https://github.com/devtron-labs/devtron/issues/5674
```release-note
```
> fix: for concurrent read and write and in buildInformerAndNamespaceList

- pkg/deployment/manifest/ManifestCreationService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
Fixes https://github.com/devtron-labs/devtron/issues/5667
```release-note
```
> fix: handling for HPA (autoscaling)

- scripts/sql/275_policy_criteria_table.down.sql
- scripts/sql/275_policy_criteria_table.up.sql
> chore: added config sql script

- pkg/deployment/manifest/ManifestCreationService.go
Fixes #5698
```release-note
```
> fix: refrain from checkin autoscalingCheckBeforeTrigger for virt clus

- pkg/deployment/gitOps/git/GitOpsHelper.go
- pkg/deployment/gitOps/git/GitServiceGithub.go
- pkg/deployment/gitOps/git/commandManager/GitCliManager.go
- pkg/deployment/gitOps/git/commandManager/GoGitSdkManager.go
- scripts/sql/276_alter_pipeline_stage_step_variable.down.sql
- scripts/sql/276_alter_pipeline_stage_step_variable.up.sql
Fixes https://github.com/devtron-labs/devtron/issues/5704
```release-note
```
> fix: script for pipelineStageStepVariable, making input value and default_value text from varchar255

- go.sum
> chore: fix go.sum file

- .gitbook.yaml
- docs/SUMMARY.md
- docs/reference/glossary.md
- docs/user-guide/creating-application/deployment-template.md
- docs/user-guide/global-configurations/README.md
- docs/user-guide/global-configurations/deployment-charts.md
- Video tutorial included
- RBAC added
- Enterprise tag added
- Doc renamed from Custom Charts to Deployment Charts
- Entry modified in SUMMARY.md
- Redirection added for Custom Charts to Deployment Charts
- Reference link added in Base Deployment Template doc
- All internal links to custom chart doc updated
> doc: Edit Deployment Chart Schema

- charts/devtron/Chart.yaml
- charts/devtron/devtron-bom.yaml
- charts/devtron/templates/_helpers.tpl
- charts/devtron/templates/app-sync-job.yaml
- charts/devtron/templates/casbin.yaml
- charts/devtron/templates/configmap-secret.yaml
- charts/devtron/templates/dashboard.yaml
- charts/devtron/templates/devtron-scc.yaml
- charts/devtron/templates/devtron.yaml
- charts/devtron/templates/dex.yaml
- charts/devtron/templates/gitsensor.yaml
- charts/devtron/templates/grafana.yaml
- charts/devtron/templates/install.yaml
- charts/devtron/templates/kubelink.yaml
- charts/devtron/templates/kubewatch.yaml
- charts/devtron/templates/lens.yaml
- charts/devtron/templates/migrator.yaml
- charts/devtron/templates/minio.yaml
- charts/devtron/templates/nats-server.yaml
- charts/devtron/templates/notifier.yaml
- charts/devtron/templates/postgresql.yaml
- charts/devtron/templates/scoop.yaml
- charts/devtron/templates/workflow.yaml
- charts/devtron/values.yaml
> feat: ServiceAccount Addition and Create ImagePullSecrets Function

- pkg/pipeline/ConfigMapService.go
> fix: Validate config cm cs

- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
- pkg/bean/app.go
1. RBAC fix for CI branch change request
Fixes https://github.com/devtron-labs/devtron/issues/5263
```release-note
```
> fix: ci patch rbac for branch update

- scripts/sql/282_user_group.down.sql
- scripts/sql/282_user_group.up.sql
> chore: sql scripts sync for 282

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
- pkg/appStore/installedApp/service/AppStoreDeploymentService.go
- pkg/deployment/gitOps/git/GitServiceGithub.go
- pkg/pipeline/CdHandler.go
- pkg/pipeline/CiHandler.go
- pkg/pipeline/CiLogService.go
- util/helper.go
Fixed Panic handling for get stage logs API
Fixes https://github.com/devtron-labs/devtron/issues/5774
```release-note
```
> fix: panic handlings and argocd app delete stuck in partial stage

- docs/setup/install/ingress-setup.md
> docs: added commands enable ingress during  helm installation

- docs/setup/install/ingress-setup.md
Restructured the doc for simplifying when Ingress is being set up: i.e., during Devtron installation or after Devtron installation
> doc: Revamped + Restructured Ingress Setup Doc

- api/cluster/EnvironmentRestHandler.go
- pkg/cluster/ClusterService.go
- pkg/cluster/EnvironmentService.go
chore: Refactoring for cluster cron service
```release-note
```
> misc: cron status update refactoring

- pkg/auth/user/repository/UserAuthRepository.go
Fixes # Cherry Pick Commit for https://github.com/devtron-labs/devtron/pull/5801
```release-note
```
> fix: sql injection bug fix

- api/helm-app/service/HelmAppService.go
- api/restHandler/DockerRegRestHandler.go
- pkg/pipeline/DockerRegistryConfig.go
- pkg/server/ServerCacheService.go
* fix: ignore error message got while checking devtron installation status
* fix: correct error messaging for docker creds
Fixes https://github.com/devtron-labs/devtron/issues/5855
```release-note
```
> fix: ignore kubelink errors in server startup (#5852)

- internal/sql/repository/AppListingRepository.go
Fixes https://github.com/devtron-labs/devtron/issues/5875
```release-note
```
> fix: oss-issues-on app detail page

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/pipelineStageVariableParser.go
- pkg/workflow/dag/WorkflowDagExecutor.go
Fixes #5877
```release-note
```
> fix: copy container image

- pkg/resourceQualifiers/helper.go
> fix: get with deduplicate in resource qualifier mapping

- scripts/sql/29302000_deployment_event.down.sql
- scripts/sql/29302000_deployment_event.up.sql
Fixes #5842 
```release-note
```
> feat: Feature release v9 sql scripts

- pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
Fixes https://github.com/devtron-labs/devtron/issues/5958
```release-note
```
> fix: modified the query for GetQueryForUserListingWithFilters

- api/auth/user/UserRestHandler.go
- api/auth/user/util/util.go
- client/events/EventBuilder.go
- client/events/EventClient.go
- go.mod
- go.sum
- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
- pkg/app/AppService.go
- pkg/app/DeploymentEventHandler.go
- pkg/auth/user/RoleGroupService.go
- pkg/auth/user/UserService.go
- pkg/auth/user/helper/helper.go
- pkg/bulkAction/BulkUpdateService.go
- pkg/deployment/gitOps/git/GitServiceGithub.go
- pkg/deployment/manifest/ManifestCreationService.go
- pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
- pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
- pkg/deployment/trigger/devtronApps/TriggerService.go
- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/CiHandler.go
- pkg/pipeline/CiService.go
- pkg/pipeline/pipelineStageVariableParser.go
- pkg/workflow/dag/WorkflowDagExecutor.go
- util/SQLUtil.go
> chore: Main sync develop

- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
Fixes #5992 
```release-note
```
> fix: helm deployment status 

- pkg/appStore/installedApp/repository/InstalledAppRepository.go
Fixes #6014
```release-note
```
> fix : multiple param of filter in helm app list

- pkg/plugin/GlobalPluginService.go
- pkg/plugin/repository/GlobalPluginRepository.go
Fixes https://github.com/devtron-labs/devtron/issues/6022
```release-note
```
> fix: plugin getByName method error handling

- pkg/chartRepo/repository/ChartsRepository.go
Fixes https://github.com/devtron-labs/devtron/issues/6017
```release-note
```
> fix: removed not null constraint for releaseOverride

- pkg/app/AppService.go
- pkg/app/integrationTest/AppService_test.go
- pkg/chartRepo/repository/ChartsRepository.go
- pkg/eventProcessor/in/DeployedApplicationEventProcessorService.go
Fixes https://github.com/devtron-labs/devops-sprint/issues/1223
```release-note
```
> misc: remove environment null check while getting chart via repo url

- pkg/module/ModuleCacheService.go
> fix: all module installation fix

- pkg/server/ServerCacheService.go
- pkg/server/ServerService.go
- pkg/server/config/ServerEnvConfig.go
- wire_gen.go
> fix: server version on updating fix

- internal/sql/repository/AppListingRepository.go
- pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
- pkg/cluster/EnvironmentService.go
- pkg/cluster/repository/EnvironmentRepository.go
- pkg/externalLink/ExternalLinkIdentifierMappingRepository.go
- pkg/pipeline/DeploymentPipelineConfigService.go
- pkg/security/policyService.go
Fixes https://github.com/devtron-labs/devops-sprint/issues/1166
```release-note
```
> misc: Sql query fixes

- api/argoApplication/wire_argoApplication.go
- api/helm-app/service/HelmAppService.go
- api/helm-app/service/read/HelmAppReadService.go
- api/helm-app/wire_helmApp.go
- api/restHandler/app/appList/AppListingRestHandler.go
- cmd/external-app/wire_gen.go
- pkg/appStore/installedApp/service/EAMode/deployment/EAModeDeploymentService.go
- pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
- pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
- pkg/argoApplication/ArgoApplicationService.go
- pkg/argoApplication/ArgoApplicationServiceExtended.go
- pkg/argoApplication/helper/helper.go
- pkg/argoApplication/read/ArgoApplicationReadService.go
- pkg/argoApplication/read/config/ArgoApplicationConfigService.go
- pkg/fluxApplication/FluxApplicationService.go
- pkg/generateManifest/DeploymentTemplateService.go
- pkg/generateManifest/helper.go
- pkg/k8s/K8sCommonService.go
- pkg/terminal/terminalSesion.go
- scripts/sql/30302300_buildx_infra.up.sql
- wire_gen.go
> feat: app details refactoring

- pkg/module/ModuleService.go
Fixes https://github.com/devtron-labs/devtron/issues/5160
```release-note
```
> fix: all modules installation fix

- .github/CODEOWNERS
- .github/workflows/pr-issue-validator.yaml
> misc:  adding pr validator for fork prs as gh command will not work

- go.mod
- go.sum
- vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
- vendor/modules.txt
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1397
```release-note
```
> misc: updated authenticator to c3254b79e386

- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
- api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
- pkg/pipeline/CiHandler.go
> misc: Main sync develop 16dec

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
> chore: panic fix

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
Currently, the repository has hundreds of open issues, making it difficult to manage and prioritize them effectively. It’s challenging to identify which issues are ready to be worked on. This lack of clarity slows down the triage process and creates inefficiencies in maintaining the backlog.
To address this, I propose automatically adding the `needs-triage` label to an issue as soon as it is created. If the issue is deemed valid or a feature worth pursuing, the `triage-accepted label` can be added, and the `needs-triage label` removed. The needs-triage label will serve as an indicator for issues that have not yet been reviewed or approved for work. This approach will help the team systematically review and categorize issues, ensuring each one is evaluated for its relevance and priority. …
> misc: add need-triage label as soon as the issue opens

- pkg/app/AppListingViewBuilder.go
- pkg/auth/user/UserService.go
- pkg/auth/user/helper/helper.go
- pkg/pipeline/pipelineStageVariableParser.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1593
```release-note
```
> fix: Copy image plugin panic

- .github/semantic.yml
- .github/workflows/pr-issue-validator.yaml
Changes made.
1. Added sync in semantic.yml
2. PR with sync: will be skipped for validation
3. Removed the condition of issue to be opened for a valid PR
> misc: skip for sync PRs, remove issue opened check for pr validator

- scripts/sql/31102502_switch_traffic_pco.down.sql
- scripts/sql/31102502_switch_traffic_pco.up.sql
> chore: add swap traffic sql scripts

- scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0/schema.json
- scripts/devtron-reference-helm-charts/cronjob-chart_1-4-0/schema.json
- scripts/devtron-reference-helm-charts/cronjob-chart_1-5-0/schema.json
> misc: added schme json for cronjobs

- pkg/variables/parsers/VariableTemplateParser.go
> misc: error handling when template is empty in ExtractVariables

- pkg/deployment/manifest/ManifestCreationService.go
> misc: nil check in envOverride.chart

- pkg/plugin/GlobalPluginService.go
- pkg/plugin/adaptor/adaptor.go
- pkg/plugin/bean/bean.go
- pkg/plugin/repository/GlobalPluginRepository.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1825
```release-note
```
> fix: plugin exposed flags default value

- .github/workflows/pr-issue-validator.yaml
- pkg/eventProcessor/bean/workflowEventBean.go
- pkg/eventProcessor/in/WorkflowEventProcessorService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1852
```release-note
```
> fix: Auto trigger even if pre-cd fails

- pkg/infraConfig/service/infraConfigService.go
- pkg/infraConfig/units/bean/memory_unit_type.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1867
```release-note
```
> fix: buildx driver opt using k8s driver even if not enabled

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
- pkg/pipeline/CdHandler.go
This pr handles the case when cd is set on auto and pre cd is also on auto, when ci completes then pre cd is triggered but cd is not triggered automatically, here handleCDStageCompleteEvent function was not placed correctly, this pr makes this func. independent of the check that terminal state of a workflow is reached or not also contains minor comments.
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1879
```release-note
```
> fix: fix for failure to trigger cd set on auto after pre-cd is success which is also on auto which got triggered after ci 

- pkg/appClone/AppCloneService.go
Fix for while cloning app or workflow when external secret is present in any pipeline then that pipeline is not cloned with error (both esoSecretData.esoDataFrom and esoSecretData.esoData can't be empty)
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1897
```release-note
```
> fix: fix for while cloning app or workflow when external secret is present in any pipeline then that pipeline is not cloned

- scripts/sql/32002900_build_worker_status.down.sql
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1824
```release-note
```
> fix: sql queries sequence

- api/restHandler/NotificationRestHandler.go
- api/router/NotificationRouter.go
- pkg/notifier/beans/beans.go
> misc: Notif back com

- internal/sql/repository/pipelineConfig/PipelineRepository.go
- pkg/workflow/dag/WorkflowDagExecutor.go
- pkg/workflow/dag/helper/helper.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1941
```release-note
```
> fix: auto pre-cd not getting triggered (if cd is manual) after webhook ci event is captured

- pkg/pipeline/CdHandler.go
- pkg/pipeline/DeploymentPipelineConfigService.go
> misc: pipeline listing in app Group

- pkg/cluster/ClusterServiceExtended.go
- pkg/cluster/repository/ClusterRepository.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2027
```release-note
```
> fix: cluster update issue

- go.mod
- go.sum
- pkg/cluster/ClusterServiceExtended.go
- pkg/cluster/repository/ClusterRepository.go
- vendor/modules.txt
> sync: Main sync develop

- pkg/deployment/manifest/ManifestCreationService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1999
```release-note
```
> fix: hpa permission denied error

- pkg/eventProcessor/in/WorkflowEventProcessorService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1828
```release-note
```
> fix: retrigger ci fails in case of AWF with global cm/cs

- pkg/chart/ChartService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2097
```release-note
```
> fix: error pg.ErrNoRow on base deployment template update

- api/appStore/deployment/AppStoreDeploymentRestHandler.go
- api/appStore/deployment/CommonDeploymentRestHandler.go
- api/auth/user/UserAuthHandler.go
- api/helm-app/HelmAppRestHandler.go
- api/k8s/application/k8sApplicationRestHandler.go
- api/restHandler/BatchOperationRestHandler.go
- api/restHandler/BulkUpdateRestHandler.go
- api/restHandler/GitOpsConfigRestHandler.go
- api/restHandler/ImageScanRestHandler.go
- api/restHandler/PolicyRestHandler.go
- api/restHandler/ReleaseMetricsRestHandler.go
- api/restHandler/WebhookEventHandler.go
- api/restHandler/app/appList/AppListingRestHandler.go
- api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2171
```release-note
```
> fix: rest handler missing return statements

- .github/workflows/auto-label.yml
> chore: update auto-label.yml

- .github/workflows/chart-sync.yaml
- .github/workflows/create-release.yml
1. The create-release action now handles both the tag creation as well as the release creation.
> misc: Updated the release creation action to create tag as well

- developers-guide/README.md
Fixes #6257 
```release-note
```
> docs: update development.md

- client/telemetry/TelemetryEventClient.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2277
```release-note
```
> fix: reverted telemetry connection error

- README.md
fix: removed multi-arch section from readme
> chore: removed multi-arch section from readme

- pkg/appStore/installedApp/service/EAMode/deployment/EAModeDeploymentService.go
- pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
- pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2322
```release-note
```
> fix: oci chart deployment values.yaml and requirement.yaml not compatible

- api/bean/AppView/AppView.go
- api/restHandler/app/pipeline/AutoCompleteRestHandler.go
- internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
- pkg/app/AppListingService.go
- pkg/pipeline/DevtronAppConfigService.go
- pkg/pipeline/PipelineBuilder.go
- wire_gen.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2194
```release-note
```
> feat: Enhancement clone UI support new

- pkg/appWorkflow/AppWorkflowService.go
- pkg/bulkAction/service/BulkUpdateService.go
- pkg/pipeline/CdHandler.go
- pkg/pipeline/DeploymentPipelineConfigService.go
- pkg/pipeline/DevtronAppConfigService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2342
```release-note
```
> fix: panic fix on concurrent deletion request

- internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
- pkg/deployment/trigger/devtronApps/deployStageHandlerCode.go
- pkg/workflow/cd/CdWorkflowRunnerService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2355
```release-note
```
> fix: waiting to start status in deployment status

- api/openapi/openapiClient/model_create_api_token_response.go
- api/openapi/openapiClient/model_update_api_token_response.go
- pkg/apiToken/ApiTokenService.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2477
```release-note
```
This PR resolves an API token visibility bug by implementing the HideApiToken flag across create and update response models. The changes include adding field declarations, methods, and JSON marshalling logic to ensure consistent and secure token visibility control in API responses. Configuration-driven modifications were made to the service layer.
</div>
> fix: send HideApiToken env var in api token create and update response

- specs/swagger/openapi.yaml
> misc: Update openapi spec

- pkg/deployment/trigger/devtronApps/bean/bean.go
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2516
```release-note
```
This pull request fixes a bug in the cron job configuration by updating the regex expression to correctly match version 6 of cron job charts, ensuring proper functionality in the deployment process.
</div>
> fix: cron job suspend

- specs/resourceRecommendation/ClusterResourceRecommendation.yaml
- specs/swagger/openapi.yaml
add resource recommendation APIs and update openapi.yaml
```release-note
```
This pull request introduces new APIs for resource recommendations in Kubernetes, enhancing existing functionality with detailed specifications for fetching, syncing, and retrieving metadata. The OpenAPI documentation has been updated to reflect these changes, including new required fields and improved object schemas for better usability.
</div>
> chore: add resource recommendation APIs and update openapi.yaml
